// Text to show as tooltips. It's divided by ~folders~ not by games
// null      = won't get a tooltip
// undefined = default name
const tooltips = {
    /* General marks */
    unknown:  "Unknown",
    corridor: "Unknown\nCorridor",
    dead_end: "Dead End",
    event:     undefined,
    center:   "Pokémon\nCenter",
    mart:     "Pokémon\nMart",
    one_way:   undefined,
    // Types left undefined
    1: null, 2: null, 3: null, 4: null,
    5: null, 6: null, 7: null, 8: null,
    "#ce4069": "Red",  "#ff9c54": "Orange", "#f3d23b": "Yellow", "#743683": "Purple", "#654321": "Brown", "#014f01": "Dark Green",
    "#4d90d5": "Blue", "#74cec0": "Cyan",   "#90c12c": "Green",  "#ec8fe6": "Pink",   "#5a5366": "Gray",  "#00146b": "Dark Blue",

    /* Crystal */
    team_rocket:  "Team\nRocket",
    c_rival:      "Silver\n(Rival)",
    c_gyarados:   "Red\nGyarados",
    c_legendary:  "Lugia\nHo-oh",
    burned_tower: "Burned\nTower",
    c_kurt:       "Kurt's\nHouse",
    c_unown:      "Unown\nRoom",
    c_train:      "Magnet\nTrain",
    dratini:      "Dragon's\nDen Room",
    c_bush:       "Blocked by\nCut",
    c_surf:       "Blocked by\nSurf",
    c_boulder:    "Blocked by\nStrength",
    c_darkness:   "Blocked by\nFlash",
    c_whirlpool:  "Blocked by\nWhirlpool",
    c_waterfall:  "Blocked by\nWaterfall",
    c_rock:       "Blocked by\nRock Smash",
    bike_needed:  "Blocked by\nBicycle Req.",
    c_trainer:    "Blocked by\nTrainer Fight",

    zephyr_badge:  "Zephyr Badge\n(Flash)",
    hive_badge:    "Hive Badge\n(Cut)",
    plain_badge:   "Plain Badge\n(Strength)",
    fog_badge:     "Fog Badge\n(Surf)",
    storm_badge:   "Storm Badge\n(Fly)",
    mineral_badge: undefined,
    glacier_badge: "Glacier Badge\n(Waterfall)",
    rising_badge:  "Rising Badge\n(Whirlpool)",
    // Kanto's badges left undefined
    c_will:  "Elite 4\nWill",
    c_koga:  "Elite 4\nKoga",
    c_bruno: "Elite 4\nBruno",
    c_karen: "Elite 4\nKaren",
    c_lance: "Champion\nLance",
    c_oak:   "Professor\nOak's Lab",
    c_red:   "Red\n(Post-Game)",
    hm_cut:       "HM 01\n(Cut)",
    hm_fly:       "HM 02\n(Fly)",
    hm_surf:      "HM 03\n(Surf)",
    hm_strength:  "HM 04\n(Strength)",
    hm_flash:     "HM 05\n(Flash)",
    hm_whirlpool: "HM 06\n(Whirlpool)",
    hm_waterfall: "HM 07\n(Waterfall)",
    hm_rocksmash: "TM 08\n(Rock Smash)",
    pokegear:       "Pokégear",
    radio_card:     undefined,
    expansion_card: undefined,
    squirt_bottle:  undefined,
    secret_potion:  undefined,
    card_key:       "Radio Tower\nCard Key",
    ss_ticket:      "S.S. Anne\nTicket",
    pass:           "Magnet Train\nPass",
    machine_part:   undefined,
    clear_bell:     undefined,
    rainbow_wing:   undefined,
    silver_wing:    undefined,
    basement_key:   undefined,
    lost_item:      undefined,
    red_scale:      undefined,
    mystery_egg:    undefined,
    pokedex:        "Pokédex",
    bike:           "Bicycle",
    blue_card:      "Buena's\nBlue Card",
    coin_case:      undefined,
    itemfinder:     undefined,
    old_rod:        undefined,
    good_rod:       undefined,
    super_rod:      undefined,
}