let crystal_fir = {
	debug: false,
    name: "crystal_fir",
	folder: "crystal_fir",
    start_location: "newbark_r29",
    font: "GameBoy_Font",
    font_size: "22px",
	is_item_tracker: true,

	// Config texts
	config_name: "Crystal Full Item Randomizer",
	//config_randomizer_author: "iFatRain",
	//config_randomizer_link: "https://github.com/iFatRain/pokemon-crystal-map-randomizer",
	config_tracker_author: "3nt0n", 
	//config_tracker_link: "",

	// Tracker information
    locations: {
        // Cities
		newbark_r29:			{x: 107, y: 72,  w: 16, h: 8,  name: "Newbark Town\nRoute 29"     			},
		azalea_r33_well:		{x: 51,  y: 96,  w: 8,  h: 8,  name: "Azalea Town\nWell / Route 33" 		},
		blackthorn:				{x: 115, y: 16,  w: 8,  h: 8,  name: "Blackthorn City"            			},
		celadon_r7_r16:			{x: 195, y: 40,  w: 24, h: 8,  name: "Celadon City\nRoutes 7 & 16"  		},
		cerulean_r5_r25:		{x: 227, y: 16,  w: 8,  h: 16, name: "Cerulean City\nRoutes 5 & 25" 		},
		cherrygrove:			{x: 83,  y: 72,  w: 8,  h: 8,  name: "Cherrygrove City"           			},
		cianwood:				{x: 3,   y: 72,  w: 8,  h: 8,  name: "Cianwood City"              			},
		cinnabar_r19_r20:		{x: 179, y: 104, w: 24, h: 8,  name: "Cinnabar Island\nRoutes 19 & 20" 		},
		ecruteak_tower_r37:		{x: 51,  y: 16,  w: 8,  h: 16, name: "Ecruteak City\nBurned / Route 37" 	},
		fuchsia_r18:			{x: 211, y: 88,  w: 16, h: 8,  name: "Fuchsia City\nRoute 18"    			},
		goldenrod:				{x: 35,  y: 64,  w: 8,  h: 8,  name: "Goldenrod City"             			},
		indigo_e4:				{x: 155, y: 8,   w: 8,  h: 8,  name: "Indigo Plateau\nElite 4"    			},
		lavender_r8_r10:		{x: 251, y: 40,  w: 16, h: 8,  name: "Lavender Town\nRoute 8"    			},
		mahogany_r44:			{x: 91,  y: 16,  w: 16, h: 8,  name: "Mahogany Town\nRoute 44"    			},
		olivine_r38_r39_r40:	{x: 19,  y: 24,  w: 8,  h: 16, name: "Olivine City\nRoutes 38, 39 & 40" 	},
		pallet:					{x: 179, y: 80,  w: 8,  h: 8,  name: "Pallet Town"      					},
		pewter:					{x: 179, y: 24,  w: 8,  h: 8,  name: "Pewter City"               			},
		saffron_tunnel:			{x: 227, y: 40,  w: 8,  h: 8,  name: "Saffron City\nUnderground Path" 	 	},
		vermilion_r6_diglett:	{x: 227, y: 56,  w: 8,  h: 8,  name: "Vermilion City\nDiglett / Route 6" 	},
		violet:					{x: 67,  y: 32,  w: 8,  h: 8,  name: "Violet City"                			},
		viridian_r1_r22:		{x: 179, y: 48,  w: 8,  h: 16, name: "Viridian City\nRoutes 1 & 22"   		},
		
		// Routes
		r2:						{x: 179, y: 36,  w: 8,  h: 8,  name: "Route 2"                 				},
		r11_r12_r13_r15:		{x: 259, y: 56,  w: 8,  h: 24, name: "Routes\n11, 12, 13 & 15" 				},
		r17:					{x: 195, y: 57,  w: 8,  h: 14, name: "Cycling Road"            				},
		r26_r27_tohjo:			{x: 137, y: 66,  w: 26, h: 14, name: "Routes 26 & 27\nTohjo Falls" 			},
		r30_r31:				{x: 83,  y: 44,  w: 8,  h: 14, name: "Route 30\nRoute 31"      				},
		r32:					{x: 67,  y: 67,  w: 8,  h: 14, name: "Route 32" 			   				},
		r34_ilex:				{x: 35,  y: 81,  w: 8,  h: 8,  name: "Route 34\nIlex Forest"   				},
		r35_r36_park:			{x: 35,  y: 32,  w: 14, h: 14, name: "Routes 35 & 36\nNational Park" 		},
		r41:					{x: 11,  y: 52,  w: 8,  h: 8,  name: "Route 41"                				},
		r45_r46:				{x: 107, y: 34,  w: 16, h: 28, name: "Route 45\nRoute 46"      				},
		ragelake_r43:			{x: 91,  y: 0,   w: 8,  h: 8,  name: "Lake of Rage\nRoute 43"  				},
		
		// Important locations
		celadonstore:			{x: 203, y: 32,  w: 8,  h: 8,  name: "Celadon\nDepartment Store"      		},
		darkcave:				{x: 96,  y: 44,  w: 8,  h: 8,  name: "Dark Cave"                      		},
		dragonsden:				{x: 124, y: 16,  w: 8,  h: 8,  name: "Dragon's Den"                   		},
		goldenrodstore:			{x: 46,  y: 57,  w: 8,  h: 8,  name: "Goldenrod\nDepartment Store"    		},
		goldenrodtunnel:		{x: 46,  y: 71,  w: 8,  h: 8,  name: "Goldenrod\nTunnel / Basement"   		},
		icepath1:				{x: 115, y: 6,   w: 8,  h: 8,  name: "Ice Path"                       		},
		icepath2:				{x: 124, y: 6,   w: 8,  h: 8,  name: "Ice Path"                       		},
		lighthouse:				{x: 22,  y: 44,  w: 8,  h: 8,  name: "Olivine's Lighthouse"           		},
		mtmoon_r3_r4:			{x: 213, y: 24,  w: 8,  h: 8,  name: "Mt. Moon\nRoutes 3 & 4"          		},
		mtmortar_r42:			{x: 67,  y: 16,  w: 8,  h: 8,  name: "Mt. Mortar Entrance\nRoute 42"     	},
		mtmortarb1f:			{x: 72,  y: 0,   w: 8,  h: 8,  name: "Mt. Mortar B1F"                 		},
		mtmortarback:			{x: 67,  y: 8,   w: 8,  h: 8,  name: "Mt. Mortar Back"               		},
		mtmortarf2:				{x: 62,  y: 0,   w: 8,  h: 8,  name: "Mt. Mortar F2"                  		},
		mtsilver_r28:			{x: 131, y: 40,  w: 20, h: 8,  name: "Mt. Silver\nRoute 28"    				},
		radiotower:				{x: 27,  y: 64,  w: 8,  h: 8,  name: "Radio Tower"                    		},
		rockethq:				{x: 99,  y: 8,   w: 8,  h: 8,  name: "Rocket Hideout"                 		},
		rocktunnel_r9_r10:		{x: 259, y: 28,  w: 8,  h: 8,  name: "Rock Tunnel\nRoutes 9 & 10"          	},
		ruinsofalph:			{x: 58,  y: 42,  w: 8,  h: 8,  name: "Ruins of Alph"                		},
		sprouttower:			{x: 75,  y: 24,  w: 8,  h: 8,  name: "Sprout Tower"                   		},
		ssaqua:					{x: 213, y: 66,  w: 8,  h: 8,  name: "S.S. Aqua"                      		},
		tintower:				{x: 51,  y: 6,   w: 8,  h: 8,  name: "Tin Tower"         					},
		unioncave:				{x: 67,  y: 96,  w: 8,  h: 8,  name: "Union Cave"                     		},
		victoryroad_reception:	{x: 155, y: 34,  w: 8,  h: 14, name: "Victory Road\nReception Gate" 		},
		whirlislands:			{x: 11,  y: 64,  w: 8,  h: 8,  name: "Whirl Islands"                  		},
		
		//for shopsanity
        shop_johto:            	{x: 137, y: 96,   w: 8,  h: 8, name: "Shops Johto"                    			},
        shop_kanto:            	{x: 145, y: 96,   w: 8,  h: 8, name: "Shops Kanto"                    			},
        
    },

    // Undefined fields:
    // - link_type:     "warp"        / "mark"
    // - link:          warp_name     / mark_name
    // - link_location: location_name / <garbage>
    warps: {
		// Cities
		newbark_r29: {
			r29_gate: 				{x: 166, y: 50,  name: "Route 29 (Newbark)"	},
			
			it_mom: 				{x: 599, y: 229, item: "overworld" 			},
        	it_aide_starter: 		{x: 516, y: 138, item: "overworld" 			},
        	it_aide_mystery_egg:	{x: 551, y: 138, item: "mystery_egg" 		},
        	it_elm_rising_badge: 	{x: 503, y: 50,  item: "rising_badge" 		},
        	it_elm_e4: 				{x: 531, y: 50,  item: "e4" 				},
        	it_potion: 				{x: 412, y: 55,  item: "overworld" 			},
        	it_berry: 				{x: 56,  y: 59,  item: "overworld" 			},
        	it_tuscany: 			{x: 216, y: 199, item: "zephyr_badge" 		},
			
			//nightmare
			it_elm_togepi:			{x: 475, y: 50,  item: "event" 				},
		},
		azalea_r33_well: {
			kurt:      				{x: 151, y: 335                                                   },
			center:    				{x: 248, y: 385                                                   },
			mart:      				{x: 344, y: 322                                                   },
			well:      				{x: 504, y: 428                                                   },
			gym:       				{x: 168, y: 482                                                   },
			charcoal:  				{x: 344, y: 519                                                   },
			gate:      				{x: 60,  y: 410                                                   },
			r33_cave:  				{x: 586, y: 398,                        name: "Route 33 (Azalea)" },
			well_up:   				{x: 267, y: 211, corridor: "well_down", name: "Slowpoke Well B1F" },
			well_down: 				{x: 109, y: 148, corridor: "well_up",   name: "Slowpoke Well B1F" },
			well_b2f:  				{x: 438, y: 145,			     		name: "Slowpoke Well B2F" },

			it_hidden: 				{x: 504, y: 360, item: "overworld" },
			it_r33_tree: 			{x: 613, y: 535, item: "overworld" },
			it_tree: 				{x: 136, y: 289, item: "overworld" },
			it_gym_badge: 			{x: 144, y: 519, item: "overworld" },
			it_gym_tm: 				{x: 194, y: 519, item: "overworld" },
			it_charcoal: 			{x: 374, y: 490, item: "farfetchd" }, //req: do farfetchd quest in ilex
			it_kurt: 				{x: 173, y: 362, item: "overworld" },
			it_well_potion: 		{x: 156, y: 23,  item: "overworld" },
			it_well_tm: 			{x: 535, y: 54,  item: "surf_strength" }, //req: both surf and strength
			it_well_kingsrock: 		{x: 375, y: 36,  item: "surf_strength" }, //req: both surf and strength
		},
		blackthorn: {
			den:         			{x: 330, y: 69  					},
			gym:         			{x: 294, y: 144 					},
			icepath:     			{x: 583, y: 114 					},
			botgym:      			{x: 216, y: 319 					},
			leftmart:    			{x: 148, y: 480 					},
			mart:        			{x: 247, y: 430 					},
			center:      			{x: 351, y: 500 					},
			rightcenter: 			{x: 472, y: 354 					},
			
			it_santos: 				{x: 390, y: 327, item: "overworld" 	},
		},
		celadon_r7_r16: {
			mart:       {x: 57,  y: 105                             	},
			tea:        {x: 249, y: 105                             	},
			backtea:    {x: 255, y: 18                              	},
			center:     {x: 456, y: 95                              	},
			gamecorner: {x: 279, y: 254                             	},
			prizes:     {x: 359, y: 321                             	},
			gym:        {x: 126, y: 415, name: "Celadon City (Gym)" 	},
			coincase:   {x: 391, y: 414                             	},
			r7_gate:    {x: 534, y: 129, name: "Route 7 (Celadon)"  	},
			r16_fly:    {x: 55,  y: 243, name: "Route 16 (Celadon)"		},
			r16_gate:   {x: 55,  y: 322, name: "Route 16 (Celadon)"   	},
			
			it_hidden:    {x: 583, y: 351, item: "overworld" 			},
			it_leftover:  {x: 411, y: 445, item: "overworld" 			},
			it_tophouse:  {x: 255, y: 69,  item: "overworld" 			},
			it_gym_badge: {x: 99,  y: 447, item: "cut"      			},
			it_gym_tm:    {x: 129, y: 447, item: "cut"       			},
		},
		cerulean_r5_r25: {
			candy:         	{x: 103, y: 193                                                        },
			robbed:        	{x: 440, y: 211                                                        },
			leftcenter:    	{x: 200, y: 255                                                        },
			center:        	{x: 295, y: 291                                                        },
			gym:           	{x: 471, y: 305                                                        },
			mart:          	{x: 392, y: 403                                                        },
            r5_daycare:    	{x: 312, y: 559, name: "Route 5 (Cerulean)"  	                       },
			r5_tunnel:     	{x: 424, y: 614, name: "Route 5 (Cerulean)"		                       },
			r5_gate:       	{x: 288, y: 660, name: "Route 5 (Cerulean)"		                       },
			r25_bill:      	{x: 399, y: 75,  name: "Route 25 (Cerulean)" 	                       },
			bill_grandpa:	{x: 532, y: 96,  name: "Bill's Grandpa",      corridor: "bill_grandpa" },
			gym_inside:		{x: 539, y: 663, name: "Cerulean Gym", 		  corridor: "gym_inside"   },
			
			it_hidden_water: 	{x: 48,  y: 171, item: "surf" 				}, 
			it_hidden_rock: 	{x: 85,  y: 44,  item: "overworld" 			}, 
			it_cut: 			{x: 227, y: 47,  item: "cut" 				}, 
			it_nugget_guy: 		{x: 306, y: 114, item: "overworld" 			}, 
			it_machinepart: 	{x: 538, y: 580, item: "power_plant" 		}, //req: talk to power_plant director
			it_gym_badge: 		{x: 525, y: 496, item: "machine_part_quest" }, //req: finish machine part quest to find misty at route 25, making her appear in gym TODO
			it_daycare: 		{x: 287, y: 590, item: "overworld" 			}, 
			
			//nightmare
			it_lickitung:		{x: 506, y: 49,  item: "event" 				}, //req: lickitung in party
			it_growlithe:		{x: 530, y: 49,  item: "event" 				}, //req: growlithe in party
			it_pichu:			{x: 551, y: 49,  item: "event" 				}, //req: pichu in party
			it_staryu:			{x: 570, y: 49,  item: "event" 				}, //req: staryu in party
			it_oddish:			{x: 587, y: 49,  item: "event" 				}, //req: oddish in party
		},
		cherrygrove: {
			mart:     	{x: 321, y: 60                          },
			center:   	{x: 443, y: 60                          },
			house_l:  	{x: 232, y: 128                         },
			house_mid:  {x: 359, y: 160                    		},
			house_r:   	{x: 456, y: 192                    		},
			
			it_mysticwater: {x: 72,  y: 201, item: "surf" 	  	},
			
			//nightmare
			it_mapcard:		{x: 493, y: 130, item: "overworld" 	},
		},
		cianwood: {
			house_n: 		{x: 56,  y: 59  },
			house_photo: 	{x: 119, y: 284 },
			house_mid: 		{x: 215, y: 380 },
			left_center: 	{x: 247, y: 443 },
			gym:    		{x: 103, y: 460 },
			center: 		{x: 351, y: 460 },
			house_medic: 	{x: 214, y: 587 },
			
			it_secretpotion: 		{x: 241, y: 561, item: "amphy" 		}, //req: talk to jasmine about sick ampharos in lighthouse
			it_gym_badge: 			{x: 81,  y: 491, item: "strength" 	},
			it_gym_tm: 				{x: 131, y: 491, item: "strength" 	},
			it_wife: 				{x: 155, y: 542, item: "strength" 	}, //req: actually beating gym - which required strength TODO
			it_rocksmash_top: 		{x: 60,  y: 111, item: "rocksmash" 	},
			it_rocksmash_bottom: 	{x: 33,  y: 270, item: "rocksmash" 	},
		},
		cinnabar_r19_r20: {
			center: {x: 184, y: 150							 	},
			r19:	{x: 518, y: 24, name: "Route 19 (Cinnabar)"	},
			r20:	{x: 383, y: 92, name: "Route 20 (Cinnabar)"	},
			
			it_hidden: {x: 151, y: 44,  item: "overworld" },
			it_blaine: {x: 418, y: 112, item: "overworld" },
		},
		ecruteak_tower_r37: {
			burned:    	{x: 87,  y: 56  					  },
			tin:       	{x: 296, y: 153 					  },
			gateleft:  	{x: 60,  y: 261 					  },
            topgym:   	{x: 88,  y: 319 					  },
			kimono:    	{x: 375, y: 316 					  },
			mart:      	{x: 496, y: 300 					  },
            gym:       	{x: 104, y: 399 					  },
			rightgym:  	{x: 222, y: 413 					  },
			center:    	{x: 376, y: 399 					  },
			gateright: 	{x: 565, y: 397 					  },
			burned_in:  {x: 525, y: 212, name: "Burned Tower" },
			
			it_hidden: 				{x: 355, y: 227, item: "overworld" },
			it_itemfinder: 			{x: 239, y: 438, item: "overworld" },
			it_kimono: 				{x: 399, y: 342, item: "overworld" },
			it_gym_badge: 			{x: 80,  y: 431, item: "overworld" },
			it_gym_tm: 				{x: 130, y: 431, item: "overworld" },
			it_r37_hidden:			{x: 253, y: 537, item: "overworld" },
			it_r37_tree_e:			{x: 423, y: 561, item: "overworld" },
			it_r37_tree_w:			{x: 376, y: 561, item: "overworld" },
			it_r37_tree_s:			{x: 408, y: 596, item: "overworld" },
			it_r37_weekly:			{x: 445, y: 633, item: "overworld" },
			it_burned_rocksmash:    {x: 619, y: 25,  item: "rocksmash" },
			it_burned_hidden_left:  {x: 524, y: 106, item: "overworld" },
			it_burned_hidden_right: {x: 581, y: 192, item: "overworld" },
			it_burned_b1f:          {x: 435, y: 84,  item: "strength"  },
		},
		fuchsia_r18: {
			mart:      {x: 88,  y: 175, name: "Fuchsia City (Mart)" },
			house:     {x: 361, y: 191                              },
			gym:       {x: 110, y: 396                              },
			rightgym:  {x: 184, y: 464                              },
			center:    {x: 312, y: 396                              },
			strength:  {x: 440, y: 412                              },
			rightgate: {x: 572, y: 330                              },
			botgate:   {x: 127, y: 539                              },
			leftgate:  {x: 60,  y: 290                              },
			
			it_tree:      {x: 135, y: 45,  item: "cut"       },
			it_gym_badge: {x: 79,  y: 433, item: "overworld" },
			it_gym_tm:    {x: 111, y: 433, item: "overworld" },
		},
		goldenrod: {
			gate:       {x: 311, y: 53  },
			tunneltop:  {x: 153, y: 62  },
			leftgym:    {x: 246, y: 145 },
			gym:        {x: 393, y: 145 },
			flower:     {x: 473, y: 62  },
			rightgym:   {x: 538, y: 184 },
			radio:      {x: 87,  y: 282 },
			station:    {x: 150, y: 183 },
			gamecorner: {x: 233, y: 315 },
			rightmart:	{x: 501, y: 302 },
			bill:       {x: 89,  y: 381 },
			tunnelbot:  {x: 183, y: 500 },
			center:     {x: 246, y: 412 },
			mart:       {x: 392, y: 412 },
			bike:       {x: 477, y: 500 },
			center_stairs: {x: 15, y: 545, corridor: "center_doors",  name: "Goldenrod (Center)", text_offset: {x: .4, y: 0} },
			center_door:   {x: 94, y: 593, corridor: "center_stairs", name: "Goldenrod (Center)", text_offset: {x: .4, y: 0} },
			
			it_bike:			{x: 495, y: 458, item: "overworld" 		},
			it_gym_badge: 		{x: 368, y: 111, item: "overworld" 		},
			it_gym_tm: 			{x: 418, y: 111, item: "overworld" 		},
			it_squirtbottle: 	{x: 499, y: 89,  item: "plain_badge" 	},
		},
		indigo_e4: {
			center_left:     {x: 40,  y: 490,                        name: "Indigo Plateau"    },
			center_entrance: {x: 132, y: 490,                        name: "Indigo Plateau"    },
			center_top:      {x: 269, y: 376,                        name: "Indigo Plateau"    },
			will_top:        {x: 80,  y: 20,  corridor: "will_bot",  name: "E4 Member (Will)"  },
			will_bot:        {x: 80,  y: 128, corridor: "will_top",  name: "E4 Member (Will)"  },
			koga_top:        {x: 245, y: 20,  corridor: "koga_bot",  name: "E4 Member (Koga)"  },
			koga_bot:        {x: 245, y: 128, corridor: "koga_top",  name: "E4 Member (Koga)"  },
			bruno_top:       {x: 80,  y: 165, corridor: "bruno_bot", name: "E4 Member (Bruno)" },
			bruno_bot:       {x: 80,  y: 279, corridor: "bruno_top", name: "E4 Member (Bruno)" },
			karen_top:       {x: 245, y: 165, corridor: "karen_bot", name: "E4 Member (Karen)" },
			karen_bot:       {x: 245, y: 279, corridor: "karen_top", name: "E4 Member (Karen)" },
		},
		lavender_r8_r10: {
			mart:       {x: 221, y: 159 },
			center:     {x: 325, y: 159 },
			botcenter:  {x: 298, y: 241 },
			left:       {x: 266, y: 305 },
			right:      {x: 329, y: 351 },
			radio:      {x: 443, y: 170 },
			botradio:   {x: 425, y: 257 },
			rocktunnel: {x: 313, y: 49,  name: "Route 10 (Lavender)"                      },
			gate:       {x: 73,  y: 157, name: "Route 8 (Lavender)"                       },
			radio_in:	{x: 49,  y: 96,  name: "Lavender Radio",     corridor: "radio_in" },
			
			it_tree:          {x: 179, y: 196, item: "overworld"          },
			it_expansioncard: {x: 165, y: 34,  item: "machine_part_quest" },
		},
		mahogany_r44: {
			gate:      {x: 126, y: 47                            	},
			mart:	   {x: 158, y: 86                           	},
			rightmart: {x: 255, y: 142                             	},
			gym:       {x: 80,  y: 174                            	},
			center:    {x: 224, y: 186                            	},
			icepath:   {x: 680, y: 83,  name: "Route 44 (Mahogany)" },

			it_gym_badge: 		{x: 55,  y: 208, item: "overworld" 	},
			it_gym_tm: 			{x: 103, y: 208, item: "overworld" 	},
			it_tree: 			{x: 358, y: 83,  item: "overworld" 	},
			it_hidden_repel: 	{x: 411, y: 173, item: "overworld" 	},
			it_grass: 			{x: 465, y: 108, item: "surf" 		},
			it_hidden_elixer: 	{x: 497, y: 175, item: "surf" 		},
			it_ultraball: 		{x: 604, y: 34,  item: "overworld" 	},
			it_birdkeeper:		{x: 643, y: 116, item: "phone" 		}, //req: pokegear + E4 + Restoring Power (finished Machine Part Quest)
			it_fisherman:		{x: 592, y: 83,  item: "phone" 		}, //req: pokegear
		},
		olivine_r38_r39_r40: {
			r38_gate:   {x: 558, y: 105, name: "Route 38 (Olivine)" },
			r39_farm_l: {x: 178, y: 76,  name: "Route 39 (Olivine)" },
			r39_farm_r: {x: 242, y: 24,  name: "Route 39 (Olivine)" },
			r40_gate:	{x: 80,  y: 528, name: "Route 40 (Olivine)" },
			gym:        {x: 274, y: 331, name: "Olivine City"       },
			trade:      {x: 515, y: 394, name: "Olivine City"       },
			righttrade: {x: 578, y: 345, name: "Olivine City"       },
			leftmart:   {x: 323, y: 408, name: "Olivine City"       },
			mart:       {x: 419, y: 439, name: "Olivine City"       },
			center:     {x: 341, y: 500, name: "Olivine City"       },
			bar:        {x: 224, y: 500, name: "Olivine City"       },
			lighthouse: {x: 578, y: 598, name: "Olivine City"       },
						
			it_r38_tree: 	{x: 419, y: 160, item: "overworld" },
			it_r38_phone:	{x: 465, y: 47,  item: "phone" 	   }, //req: pokegear
			it_r39_tree:	{x: 328, y: 47,  item: "overworld" },
			it_r39_hidden: 	{x: 265, y: 118, item: "overworld" },
			it_r39_phone:	{x: 346, y: 263, item: "phone" 	   }, //req: pokegear + Pikachu in Team
			it_miltank: 	{x: 266, y: 45,  item: "overworld" },
			it_good_rod: 	{x: 346, y: 435, item: "overworld" },
			it_strength: 	{x: 250, y: 524, item: "overworld" },
			it_monica: 		{x: 83,  y: 639, item: "overworld" },
			it_rocksmash: 	{x: 68,  y: 607, item: "rocksmash" },
			it_gym_badge: 	{x: 250, y: 364, item: "overworld" },
			it_gym_tm: 		{x: 300, y: 364, item: "overworld" },
			it_port: 		{x: 276, y: 669, item: "surf_ticket" },
		},
		pallet: {
			main:  		{x: 88,  y: 62  },
			rival: 		{x: 215, y: 62  },
			lab:   		{x: 200, y: 154 },
		},
		pewter: {
			gym:    {x: 208, y: 237 },
			mart:   {x: 344, y: 240 },
			top:    {x: 440, y: 190 },
			center: {x: 184, y: 369 },
			bot:    {x: 89,  y: 444 },
			
			it_silverwing: 	{x: 448, y: 275, item: "overworld" },
			it_tree_left: 	{x: 455, y: 75,  item: "overworld" },
			it_tree_right: 	{x: 487, y: 75,  item: "overworld" },
			it_gym_badge: 	{x: 207, y: 274, item: "overworld" },
		},
		saffron_tunnel: {
			topgate:   	{x: 283, y: 23  						},
			rightgate: 	{x: 572, y: 334 						},
			botgate:   	{x: 272, y: 505 						},
			leftgate:  	{x: 66,  y: 373 						},
			station:   	{x: 134, y: 23  						},
			dojo:      	{x: 418, y: 23  						},
			gym:       	{x: 550, y: 23  						},
			mimic:     	{x: 151, y: 208 						},
			mimic_in:	{x: 254, y: 161, name: "Saffron Mimic" 	},
			mart:     	{x: 408, y: 141 						},
			silph:    	{x: 297, y: 303 						},
			center:    	{x: 152, y: 431 						},
			psychic:   	{x: 440, y: 431 						},
			uground_n:	{x: 677, y: 39  						},
			uground_s:	{x: 677, y: 525 						},
			
			it_psychic:   	{x: 463, y: 471, item: "overworld" },
			it_copycat:   	{x: 294, y: 194, item: "lost_item" },
			it_silphco:   	{x: 323, y: 343, item: "overworld" },
			it_fightgym:  	{x: 400, y: 56,  item: "overworld" },
			it_gym_badge: 	{x: 527, y: 56,  item: "overworld" },
			it_uground_n:	{x: 678, y: 171, item: "overworld" },
			it_uground_s:	{x: 693, y: 419, item: "overworld" },
		},
		vermilion_r6_diglett: {
			fish:        {x: 72,  y: 214                               },
			center:      {x: 136, y: 148                               },
			fanclub:     {x: 103, y: 277                               },
			trade:       {x: 211, y: 277                               },
			mart:        {x: 329, y: 277                               },
			gym:         {x: 151, y: 371, name: "Vermilion City (Gym)" },
			botmart:     {x: 329, y: 355  		                       },
			digglet:     {x: 536, y: 196  		                       },
			gate:        {x: 280, y: 47,  name: "Route 6 (Vermilion)"  },
			tunnel:      {x: 456, y: 25,  name: "Route 6 (Vermilion)"  },
			fanclub_in:	 {x: 65,  y: 77,  name: "Vermilion Fanclub"    },
			diglett_n:	 {x: 514, y: 377, name: "Diglett (Vermilion)"  },
			diglett_s:	 {x: 544, y: 611, name: "Diglett (Vermilion)"  },
			
			it_hidden:    {x: 183, y: 438, item: "overworld"   },
			it_fanclub:   {x: 76,  y: 20,  item: "overworld"   },
			it_lostitem:  {x: 16,  y: 37,  item: "copy_cat"    }, //req: talk to copy cat girl in saffron 
			it_gym_badge: {x: 127, y: 413, item: "overworld"   },
			it_port:      {x: 159, y: 575, item: "surf_ticket" }, //req: ss-ticket and surf required TODO
			it_diglett:	  {x: 536, y: 536, item: "overworld"   },
		},
		violet: {
			sprout:        {x: 360, y: 76                                                     		},
			leftmart:      {x: 62,  y: 241                                                    		},
			mart:          {x: 136, y: 274                                                    		},
			gym:           {x: 280, y: 262                                                    		},
			school:        {x: 472, y: 271                                                     		},
			center:        {x: 482, y: 389                                                     		},
			trade:         {x: 328, y: 464                                                     		},
			gate:          {x: 598, y: 382                                                     		},
			center_door:   {x: 585, y: 551, corridor: "center_stairs", name: "Violet City (Center)" },
			center_stairs: {x: 468, y: 551, corridor: "center_door",   name: "Violet City (Center)" },
			
			it_tree: 		{x: 191, y: 488, item: "overworld" 	},
			it_hidden_cut: 	{x: 584, y: 227, item: "cut" 		},
			it_surf_left: 	{x: 55,  y: 67,  item: "surf" 		},
			it_surf_right: 	{x: 575, y: 103, item: "surf" 		},
			it_gym_badge: 	{x: 256, y: 294, item: "overworld" 	},
			it_gym_tm: 		{x: 304, y: 294, item: "overworld" 	},
		},
		viridian_r1_r22: {
			r22_gate:   {x: 65,  y: 62,  name: "Route 22 (Viridian)" },
			gym:    	{x: 570, y: 61  							 },
			house:  	{x: 394, y: 108 							 },
			school: 	{x: 426, y: 190 							 },
			mart:   	{x: 523, y: 254 							 },
			center: 	{x: 426, y: 350 							 },
        		
			it_cut_guy:   {x: 197, y: 380, item: "surf_or_cut"  }, // req: either surf OR cut
			it_gym_badge: {x: 545, y: 105, item: "overworld" 	},
			it_r1:		  {x: 340, y: 503, item: "overworld" 	},
		},
		
		// Routes
		r2: {
			diglett: {x: 216, y: 76  },
			trade:   {x: 273, y: 205 },
			gatetop: {x: 287, y: 396 },
			gatebot: {x: 263, y: 520 },
			
			it_cut: 				{x: 269, y: 616, item: "cut" },
			it_diglett: 			{x: 327, y: 43,  item: "overworld" },
			it_hidden_revive: 		{x: 87,  y: 189, item: "overworld" },
			it_dire_hit: 			{x: 23,  y: 474, item: "overworld" },
			it_hidden_full_restore: {x: 108, y: 423, item: "overworld" },
			it_hidden_ether: 		{x: 175, y: 473, item: "overworld" },
			it_hidden_full_heal: 	{x: 134, y: 384, item: "overworld" },
			it_potion: 				{x: 34,  y: 355, item: "overworld" },
			it_tree: 				{x: 159, y: 210, item: "overworld" },
			it_house: 				{x: 285, y: 234, item: "overworld" },
		},
		r11_r12_r13_r15: {
			r12: {x: 270, y: 209, name: "Route 12" },
			r15: {x: 65,  y: 493, name: "Route 15" },
        		
        	it_hidden_surf: {x: 318, y: 48,  item: "surf" },
        	it_cut:	 		{x: 173, y: 332, item: "cut" },
        	it_surf_cut: 	{x: 173, y: 451, item: "surf_cut" },
        	it_hidden_maze: {x: 253, y: 607, item: "overworld" },
        	it_hidden_rock: {x: 81,  y: 76,  item: "overworld" },
        	it_tree: 		{x: 81,  y: 24,  item: "overworld" },
        	it_fisher: 		{x: 292, y: 236, item: "overworld" },
			it_r15: 		{x: 177, y: 530, item: "overworld" },
		},
		r17: {
			top: {x: 150, y: 29,  corridor: "bot"},
			bot: {x: 256, y: 593, corridor: "top"},
			
			it_hidden_water: 	{x: 149, y: 182, item: "overworld" },
			it_hidden_elixer: 	{x: 136, y: 560, item: "overworld" },
		},
		r26_r27_tohjo: {
			left:        {x: 65,  y: 487,                          name: "Route 27" },
			right:       {x: 213, y: 487,                          name: "Route 27" },
			house1:      {x: 165, y: 569,                          name: "Route 27" },
			house2:      {x: 480, y: 389,                          name: "Route 26" },
			house3:      {x: 630, y: 264,                          name: "Route 26" },
			reception:   {x: 510, y: 17,                           name: "Route 26" },
			falls_left:  {x: 191, y: 432, corridor: "falls_right", name: "Tohjo Falls" },
			falls_right: {x: 384, y: 432, corridor: "falls_left",  name: "Tohjo Falls" },
			
			it_tohjo_surf: 	{x: 41,  y: 300, item: "surf"      },
			it_sandstorm:  	{x: 187, y: 536, item: "overworld" }, //this route is kinda weird, you actually need waterfall to come from left (in non-warp-rando) TODO
			it_surf:       	{x: 330, y: 600, item: "surf"      },
			it_whirl:     	{x: 442, y: 600, item: "whirl"     }, //req: actually surf AND whirl, I didnt include surf for whirl and waterfall
			it_tree:       	{x: 622, y: 213, item: "overworld" },
			it_elixer:     	{x: 518, y: 131, item: "overworld" },
			it_phone:		{x: 385, y: 636, item: "phone" 	   }, //req: pokegear + surf + whirlpool
		},
		r30_r31: {
			gate:     {x: 68,  y: 56,  name: "Route 31"                        },
			darkcave: {x: 531, y: 43,  name: "Route 31"                        },
			berry:    {x: 419, y: 567, name: "Route 30"                        },
			lab:      {x: 570, y: 293, name: "Route 30"                        },
			lab_in:   {x: 163, y: 341, name: "Mr. Pokemon", corridor: "lab_in" },

			it_tophouse:   		{x: 458, y: 529, item: "overworld" },
			it_trainer:    		{x: 267, y: 227, item: "overworld" },
			it_cave:      	 	{x: 452, y: 89,  item: "overworld" },
			it_hidden:     		{x: 506, y: 379, item: "overworld" },
			it_tree_berry: 		{x: 361, y: 590, item: "overworld" },
			it_berryman:   		{x: 443, y: 594, item: "overworld" },
			it_tree_kenya: 		{x: 221, y: 98,  item: "overworld" },
			it_kenya_return: 	{x: 284, y: 98,  item: "overworld" },
			it_tree_lab:   		{x: 509, y: 315, item: "overworld" },
			it_mrpokemon:  		{x: 172, y: 289, item: "overworld" },
			it_oak: 			{x: 220, y: 289, item: "overworld" },
			it_red_scale: 		{x: 139, y: 289, item: "red_scale" },
			it_r30_phone:		{x: 364, y: 429, item: "phone" 	   },
			it_r31_phone:		{x: 349, y: 196, item: "phone" 	   },
		},
		r32: {
			gate:  		{x: 87,  y: 22,                          name: "Route 32"   		},
			center:     {x: 199, y: 584,                         name: "Route 32"           },
			union:      {x: 110, y: 687,                         name: "Route 32"           },
			rod_stairs: {x: 178, y: 744, corridor: "rod_door",   name: "Center (Route 32)"  },
			rod_door:   {x: 295, y: 744, corridor: "rod_stairs", name: "Center (Route 32)"  },
			
			it_miracle_seed: 	{x: 327, y: 165, item: "zephyr_badge"	},
			it_grass_top: 		{x: 72,  y: 272, item: "overworld" 		},
			it_grass_bottom: 	{x: 93,  y: 469, item: "overworld" 		},
			it_roar: 			{x: 263, y: 193, item: "cut" 			},
			it_hidden_grass: 	{x: 174, y: 402, item: "overworld" 		},
			it_hidden_frieda: 	{x: 200, y: 551, item: "overworld" 		},
			it_frieda: 			{x: 242, y: 522, item: "overworld" 		},
			it_fisher: 			{x: 241, y: 711, item: "overworld" 		},
		},
		r34_ilex: {
			r34_gate:    {x: 142, y: 503,                        name: "Route 34"        },
			r34_daycare: {x: 101, y: 78,                         name: "Route 34"        },
			ilext_top:   {x: 300, y: 80,  corridor: "ilext_bot", name: "Ilex Forest"     },
			ilext_bot:   {x: 332, y: 663, corridor: "ilext_top", name: "Ilex Forest"     },
			tm12_top:    {x: 174, y: 642, corridor: "tm12_bot",  name: "Gate (Route 34)" },
			tm12_bot:    {x: 174, y: 708, corridor: "tm12_top",  name: "Gate (Route 34)" },
			
			it_cut:             {x: 363, y: 446, item: "farfetchd" }, //req: farfetchd quest required, but you can also do farfetchd quest here TODO
			it_revive:          {x: 604, y: 559, item: "overworld" },
			it_hidden_fullheal: {x: 299, y: 272, item: "overworld" },
			it_xattack:         {x: 452, y: 298, item: "overworld" },
			it_antidote:        {x: 580, y: 136, item: "overworld" },
			it_hidden_potion:   {x: 635, y: 220, item: "overworld" },
			it_headbutt:        {x: 523, y: 220, item: "overworld" },
			it_ether:           {x: 740, y: 43,  item: "overworld" },
			it_hidden_ether:    {x: 437, y: 140, item: "overworld" },
			it_sweet_scent:     {x: 222, y: 673, item: "overworld" },
			it_nugget:          {x: 62,  y: 361, item: "surf"      },
			it_hidden_candy:    {x: 79,  y: 391, item: "surf"      },
			it_hidden_daycare:  {x: 198, y: 160, item: "overworld" },
			it_softsand:        {x: 49,  y: 694, item: "surf"      },
			it_phone:			{x: 109, y: 294, item: "phone"     }, //req: pokegear
		},
		r35_r36_park: {
			r35_gate_s:	{x: 274, y: 632, name: "Route 35" },
			r35_gate_n:	{x: 170, y: 319, name: "Route 35" },
			park_s:		{x: 191, y: 228, name: "National Park" },
			park_n:		{x: 199, y: 107, name: "National Park" },
			r36_gate_e:	{x: 403, y: 109, name: "Route 36" },
			r36_gate_w:	{x: 694, y: 241, name: "Route 36" },
			kenya_s:	{x: 520, y: 675, name: "Gate (Route 36)" },
			kenya_n:	{x: 520, y: 597, name: "Gate (Route 36)" },
        	
			it_r35_tree:	{x: 154, y: 577, item: "surf" },
			it_r35_ball:	{x: 310, y: 464, item: "overworld" },
			it_park_claw:	{x: 277, y: 225, item: "overworld" },
			it_park_hidden:	{x: 94,  y: 249, item: "overworld" },
			it_park_ball_n:	{x: 257, y: 34,  item: "overworld" },
			it_park_ball_s:	{x: 65,  y: 184, item: "overworld" },
			it_park_phone:	{x: 117, y: 109, item: "phone" }, //req: pokegear + Marill in team
			it_conquest_1:	{x: 20,  y: 62,  item: "event" },
			it_conquest_2:	{x: 65,  y: 62,  item: "event" },
			it_conquest_3:	{x: 110, y: 62,  item: "event" },
			it_conquest_4:	{x: 151, y: 62,  item: "event" },
			it_r36_tree:	{x: 443, y: 41,  item: "overworld" },
			it_r36_rsmash:	{x: 661, y: 123, item: "sudowoodo" }, //req: doing sudowoodo with squirtbottle
			it_r36_arthur:	{x: 693, y: 74,  item: "overworld" },
			it_r36_kenya:	{x: 472, y: 635, item: "event" },
			it_r36_phone:	{x: 496, y: 203, item: "phone" },
		},
		r41: {
			topleft:  {x: 181, y: 156, name: "Route 41 (NW)" },
			topright: {x: 566, y: 189, name: "Route 41 (NE)" },
			botleft:  {x: 217, y: 477, name: "Route 41 (SW)" },
			botright: {x: 566, y: 605, name: "Route 41 (SE)" },
			
			it_hidden: {x: 135, y: 494, item: "surf" },
		},
		r45_r46: {
			gate:        	{x: 143, y: 681, name: "Route 46" },
			botdarkcave: 	{x: 248, y: 386, name: "Route 46" },
			topdarkcave: 	{x: 380, y: 15,  name: "Route 45" },
			
			it_elixer: 		{x: 438, y: 100, item: "overworld" 	},
			it_potion: 		{x: 502, y: 152, item: "overworld" 	},
			it_nugget: 		{x: 423, y: 245, item: "overworld" 	},
			it_revive:	 	{x: 419, y: 325, item: "overworld" 	},
			it_r45_phone:	{x: 551, y: 229, item: "phone" 		}, //req: pokegear
			it_oasis: 		{x: 557, y: 438, item: "surf" 		},
			it_tree_oasis: 	{x: 604, y: 517, item: "overworld" 	},
			it_tree_top:	{x: 135, y: 384, item: "overworld" 	},
			it_tree_right: 	{x: 152, y: 451, item: "overworld" 	},
			it_xspeed: 		{x: 24,  y: 499, item: "overworld" 	},
			it_r46_phone:	{x: 98,  y: 539, item: "phone" 		}, //req: pokegear + E4 + Restoring Power (finished Machine Part Quest)
		},
		ragelake_r43: {
			cut:      {x: 104, y: 27,                      name: "Lake of Rage"     },
			lake:     {x: 424, y: 396,                     name: "Lake of Rage"     },
			entrance: {x: 335, y: 720,                     name: "Route 43"    		},
			gatebot:  {x: 456, y: 676,                     name: "Route 43"  		},
			gatetop:  {x: 464, y: 557,                     name: "Route 43"    		},
			tm_bot:   {x: 575, y: 657, corridor: "tm_top", name: "Gate (Route 43)" 	},
			tm_top:   {x: 575, y: 593, corridor: "tm_bot", name: "Gate (Route 43)" 	},
			fisher:	  {x: 560, y: 440,                     name: "Magikarp Fisher"  },
			
			it_gate: 				{x: 533, y: 628, item: "rockets" }, //req: beating rockets in mahagony hideout TODO
			it_ether: 				{x: 351, y: 598, item: "overworld" },
			it_tree: 				{x: 224, y: 501, item: "surf" }, //req: cut + surf
			it_gyarados: 			{x: 305, y: 272, item: "surf" },
			it_hidden_potion: 		{x: 167, y: 346, item: "overworld" },
			it_hidden_full_restore:	{x: 528, y: 85,  item: "overworld" },
			it_hidden_candy: 		{x: 33,  y: 84,  item: "cut" },
			it_Wesley: 				{x: 55,  y: 42,  item: "cut" },
			it_Elixer: 				{x: 80,  y: 163, item: "cut" },
			it_detect: 				{x: 576, y: 35,  item: "cut" },
			it_house: 				{x: 127, y: 60,  item: "cut" },
			it_phone:				{x: 351, y: 549, item: "phone" },
			it_magikarp:			{x: 529, y: 409, item: "pokemon" }, //req: magikarp of unusual size
		},
		
		// Important locations
		celadonstore: {
			f1_door: {x: 132, y: 380, name: "Celadon Store" },
			f1_up:   {x: 252, y: 270, name: "Celadon Store" },
			f2_up:   {x: 252, y: 134, name: "Celadon Store" },
			f2_down: {x: 204, y: 176, name: "Celadon Store" },
			f3_up:   {x: 252, y: -5,  name: "Celadon Store" },
			f3_down: {x: 204, y: 40,  name: "Celadon Store" },
			f4_up:   {x: 520, y: 270, name: "Celadon Store" },
			f4_down: {x: 470, y: 316, name: "Celadon Store" },
			f5_up:   {x: 520, y: 134, name: "Celadon Store" },
			f5_down: {x: 470, y: 176, name: "Celadon Store" },
			f6_up:   {x: 520, y: -5,  name: "Celadon Store" },
		},
		darkcave: {
			r31_left:  {x: 70,  y: 216                                                      },
			r31_top:   {x: 280, y: 36                                                       },
			r31_right: {x: 567, y: 520                                                      },
			r45_left:  {x: 69,  y: 637, corridor: "r45_right", name: "Dark Cave (Corridor)" },
			r45_right: {x: 363, y: 333, corridor: "r45_left",  name: "Dark Cave (Corridor)" },
			
			it_potion: 			{x: 129, y: 119, item: "overworld" },
			it_hidden_elixer: 	{x: 451, y: 39,  item: "rocksmash" },
			it_hyper_potion: 	{x: 590, y: 135, item: "rocksmash" },
			it_full_heal: 		{x: 560, y: 344, item: "rocksmash" },
			it_dire_hit: 		{x: 511, y: 438, item: "rocksmash" },
			it_blackglasses: 	{x: 132, y: 299, item: "surf" },
			it_revive: 			{x: 358, y: 634, item: "surf" },
			it_snore: 			{x: 137, y: 602, item: "surf" },
		},
		dragonsden: {
			entrance:         {x: 328, y: 25,  name: "Dragon's Den" },
			shrine:           {x: 312, y: 443, name: "Dragon's Den" },

			it_top:           {x: 470, y: 67,  item: "overworld" 	}, //need to beat claire first to access this area
			it_left:          {x: 87,  y: 305, item: "surf" 		},
			it_right:         {x: 568, y: 281, item: "whirl" 		},
			it_hidden_left:   {x: 345, y: 257, item: "surf" 		},
			it_hidden_right:  {x: 504, y: 220, item: "whirl" 		},
			it_hidden_bottom: {x: 535, y: 447, item: "whirl" 		},
			it_gym_badge:     {x: 338, y: 473, item: "whirl" 		}, //blackthorn gym badge and tm
			it_gym_tm:        {x: 224, y: 484, item: "whirl" 		},	
		},
		goldenrodstore: {
			f1_door: {x: 127, y: 375, name: "Goldenrod Store" },
			f1_up:   {x: 247, y: 261, name: "Goldenrod Store" },
			f2_up:   {x: 199, y: 174, name: "Goldenrod Store" },
			f2_down: {x: 247, y: 125, name: "Goldenrod Store" },
			f3_up:   {x: 247, y: 0,   name: "Goldenrod Store" },
			f3_down: {x: 199, y: 39,  name: "Goldenrod Store" },
			f4_up:   {x: 460, y: 306, name: "Goldenrod Store" },
			f4_down: {x: 509, y: 257, name: "Goldenrod Store" },
			f5_up:   {x: 509, y: 123, name: "Goldenrod Store" },
			f5_down: {x: 460, y: 173, name: "Goldenrod Store" },
			f6_up:   {x: 476, y: 39,  name: "Goldenrod Store" },
			f6_down: {x: 509, y: 0,   name: "Goldenrod Store" },
			b1f:     {x: 257, y: 503, name: "Goldenrod Store" },
			
			it_return1:     {x: 365, y: 238, item: "overworld"    },
			it_return2:     {x: 365, y: 213, item: "overworld"    },
			it_basement_NW: {x: 184, y: 461, item: "overworld"    },
			it_basement_NE: {x: 311, y: 445, item: "basement_key" }, //req: basement key to access basement //deadend //TODO
			it_basement_SW: {x: 248, y: 573, item: "overworld"    },
			it_basement_SE: {x: 328, y: 574, item: "overworld"    },
		},
		goldenrodtunnel: {
			top:               	{x: 60,  y: 60 , name: "Goldenrod Tunnel"                          			 },
			basement:          	{x: 168, y: 79 , name: "Goldenrod Tunnel"                                 	 },
			bot:               	{x: 60,  y: 530, name: "Goldenrod Tunnel"                                 	 },
			basement_rival:    	{x: 558, y: 24,  corridor: "basement_director",  name: "Goldenrod Basement"  },
			basement_director: 	{x: 558, y: 139, corridor: "basement_rival",     name: "Goldenrod Basement"  },
			warehouse_entrance:	{x: 247, y: 430, corridor: "warehouse_store",    name: "Goldenrod Warehouse" },
			warehouse_store: 	{x: 480, y: 268, corridor: "warehouse_entrance", name: "Goldenrod Warehouse" },
			
			it_coin_case:           {x: 66,  y: 403, item: "overworld"    },
			it_hidden_super_potion: {x: 62,  y: 295, item: "overworld"    },
			it_hidden_paralyz_heal: {x: 50,  y: 213, item: "overworld"    },
			it_hidden_antidote:     {x: 130, y: 131, item: "overworld"    },
			it_hidden_revive:       {x: 244, y: 131, item: "basement_key" }, //req: all items in the basement area need basement_key
			it_hidden_max_potion:   {x: 327, y: 147, item: "basement_key" },
			it_full_heal:           {x: 451, y: 147, item: "basement_key" },
			it_smoke_ball:          {x: 229, y: 195, item: "basement_key" },
			it_ultra_ball:          {x: 261, y: 277, item: "basement_key" },
			it_max_ether:           {x: 472, y: 500, item: "basement_key" },
			it_sleeptalk:           {x: 437, y: 404, item: "basement_key" },
			it_director:            {x: 375, y: 387, item: "radiotower"   }, //req: beat radio tower
		},
		icepath1: {
			hub_stairsleft:   {x: 64,  y: 621,                              name: "Ice Path (Holes)"      },
			hub_holebotleft:  {x: 92,  y: 565,                              name: "Ice Path (Holes)"      },
			hub_holebotright: {x: 199, y: 597,                              name: "Ice Path (Holes)"      },
			hub_holetopleft:  {x: 70,  y: 493,                              name: "Ice Path (Holes)"      },
			hub_holetopright: {x: 184, y: 408,                              name: "Ice Path (Holes)"      },
			hub_stairsup:     {x: 280, y: 442,                              name: "Ice Path (Holes)"      },
			entrance_door:    {x: 72,  y: 285, corridor: "entrance_stairs", name: "Ice Path (Waterfall)"  },
			entrance_stairs:  {x: 553, y: 76,  corridor: "entrance_door",   name: "Ice Path (Waterfall)"  },
			exit_stairs:      {x: 554, y: 217, corridor: "exit_door",       name: "Ice Path (Exit)"       },
			exit_door:        {x: 545, y: 410, corridor: "exit_stairs",     name: "Ice Path (Exit)"       },
			b1f_right:        {x: 484, y: 556, corridor: "b1f_left",        name: "Ice Path (B1F)"        },
			b1f_left:         {x: 387, y: 520, corridor: "b1f_right",       name: "Ice Path (B1F)"        },
			
			it_waterfall: 			{x: 452, y: 107, item: "overworld" },
			it_exit_protein: 		{x: 571, y: 134, item: "strength"  },
			it_exit_pp_up: 			{x: 470, y: 356, item: "strength"  },
			it_hidden_max_potion: 	{x: 603, y: 569, item: "strength"  },
			it_iron: 				{x: 411, y: 644, item: "strength"  },
		},
		icepath2: {
			fall_mid:  {x: 151, y: 162, corridor: "fall_up",   name: "Ice Path (Fall)" },
			fall_up:   {x: 282, y: 50,  corridor: "fall_mid",  name: "Ice Path (Fall)" },
			b2f_top:   {x: 381, y: 78,  corridor: "b2f_bot",   name: "Ice Path (B2F)"  },
			b2f_bot:   {x: 378, y: 226, corridor: "b2f_top",   name: "Ice Path (B2F)"  },
			b3f_right: {x: 332, y: 349, corridor: "b3f_left",  name: "Ice Path (B3F)"  },
			b3f_left:  {x: 139, y: 353, corridor: "b3f_right", name: "Ice Path (B3F)"  },
			
			it_full_heal: 				{x: 134, y: 128, item: "strength" },
			it_max_potion: 				{x: 26,  y: 36,  item: "strength" },
			it_hidden_carbos: 			{x: 11,  y: 257, item: "strength" },
			it_rest: 					{x: 458, y: 236, item: "strength" },
			it_hidden_ice_heal: 		{x: 383, y: 168, item: "strength" },
			it_rocksmash_nevermeltice: 	{x: 192, y: 407, item: "strength" },
		},
		lighthouse: {
			f2_entrance:  {x: 55,  y: 502,                         name: "Lighthouse (2F)"  },
			f2_hole:      {x: 272, y: 535,                         name: "Lighthouse (2F)"  },
			f2_stairs:    {x: 88,  y: 380,                         name: "Lighthouse (2F)"  },
			f3_entrance:  {x: 72,  y: 81,                          name: "Lighthouse (3F)"  },
			f3_hole:      {x: 272, y: 210,                         name: "Lighthouse (3F)"  },
			f3_stairs:    {x: 215, y: 24,                          name: "Lighthouse (3F)"  },
			f4_entrance:  {x: 575, y: 611,                         name: "Lighthouse (4F)"  },
			f4_hole_s:    {x: 594, y: 767,                         name: "Lighthouse (4F)"  },
			f4_stairs_up: {x: 362, y: 648,                         name: "Lighthouse (4F)"  },
			f4_stairsbot: {x: 454, y: 740,                         name: "Lighthouse (4F)"  },
			f4_stairsmid: {x: 454, y: 692,                         name: "Lighthouse (4F)"  },
			f4_hole_n:    {x: 447, y: 611,                         name: "Lighthouse (4F)"  },
			f5_hole:      {x: 594, y: 441, corridor: "f5_stairs",  name: "Lighthouse (5F)"  },
			f5_stairs:    {x: 382, y: 342, corridor: "f5_hole",    name: "Lighthouse (5F)"  },
			f5_intop:     {x: 478, y: 509, corridor: "f5_inbot",   name: "Lighthouse (5F)"  },
			f5_inbot:     {x: 478, y: 379, corridor: "f5_intop",   name: "Lighthouse (5F)"  },
			top_stairs:   {x: 478, y: 220, corridor: "top_hole",   name: "Lighthouse (Top)" },
			top_hole:     {x: 593, y: 115, corridor: "top_stairs", name: "Lighthouse (Top)" },
			
			it_f2_phone:	{x: 152, y: 318, item: "phone" }, //req: pokegear + E4 + Restoring Power + Saving Radio Tower
			it_f3: 			{x: 110, y: 36,  item: "overworld" },
			it_f5_left: 	{x: 352, y: 483, item: "overworld" },
			it_f5_hidden: 	{x: 396, y: 483, item: "overworld" },
			it_f5_middle: 	{x: 429, y: 563, item: "overworld" },
			it_f5_right: 	{x: 574, y: 511, item: "overworld" },
			it_top: 		{x: 407, y: 66,  item: "overworld" },
		},
		mtmoon_r3_r4: {
			r3:                 {x: 127, y: 311, name: "Route 3"           },
			r4:                 {x: 220, y: 376, name: "Route 4"           },
			mooncave_stairstop: {x: 204, y: 73,  name: "Mt. Moon (Cave)"   },
			mooncave_doortop:   {x: 62,  y: 26,  name: "Mt. Moon (Cave)"   },
			mooncave_stairsbot: {x: 235, y: 140, name: "Mt. Moon (Cave)"   },
			mooncave_doorbot:   {x: 236, y: 220, name: "Mt. Moon (Cave)"   },
			moonsquare_house:   {x: 422, y: 80,  name: "Mt. Moon (Square)" },
			moonsquare_top:     {x: 533, y: 44,  name: "Mt. Moon (Square)" },
			moonsquare_bot:     {x: 566, y: 144, name: "Mt. Moon (Square)" },
			
			it_rocksmash_clefairy: 	{x: 326, y: 74,  item: "rocksmash" },
			it_r4_hp_up: 			{x: 579, y: 313, item: "overworld" },
			it_r4_hidden: 			{x: 323, y: 312, item: "overworld" },
		},
		mtmortar_r42: {
			r42_gate:               {x: 62,  y: 550,                                name: "Route 42"     	 },
			r42_cave1:              {x: 168, y: 488,                                name: "Route 42"     	 },
			r42_cave2:              {x: 374, y: 498,                                name: "Route 42"     	 },
			r42_cave3:              {x: 577, y: 466,                                name: "Route 42"   	 	 },
			mortarwater_door:       {x: 280, y: 380,                                name: "Mt. Mortar Entry" },
			mortarwater_stairs:     {x: 281, y: 301,                                name: "Mt. Mortar Entry" },
			mortarwater_waterfall:  {x: 279, y: 42,                                 name: "Mt. Mortar Entry" },
			mortar1item_door:       {x: 472, y: 210, corridor: "mortar1item_entry", name: "Mt. Mortar Entry" },
			mortar1item_entry:      {x: 577, y: 377, corridor: "mortar1item_door",  name: "Mt. Mortar Entry" },
			
			it_r42_left: 		{x: 128, y: 440, item: "overworld" },
			it_hidden_surf: 	{x: 252, y: 535, item: "surf" },
			it_r42_middle: 		{x: 455, y: 482, item: "overworld" },
			it_tree_left: 		{x: 350, y: 611, item: "surf_cut" }, 
			it_tree_middle: 	{x: 375, y: 611, item: "surf_cut" },
			it_tree_right: 		{x: 400, y: 611, item: "surf_cut" },
			it_r42_phone:		{x: 495, y: 515, item: "phone" },
			it_mtmortar_hidden:	{x: 383, y: 250, item: "overworld" },
			it_mtmortar_left: 	{x: 188, y: 134, item: "overworld" },
			it_mtmortar_right: 	{x: 529, y: 180, item: "overworld" },
		},
		mtmortarb1f: {
			top:    {x: 62,  y: 18,  corridor: "bottom" },
			bottom: {x: 298, y: 486, corridor: "top"    },
			
			it_full_restore: {x: 514, y: 374, item: "surf" },
			it_hyper_potion: {x: 432, y: 182, item: "surf" },
			it_max_ether: 	 {x: 533, y: 36,  item: "surf" },
			it_pp_up: 		 {x: 356, y: 406, item: "surf" },
			it_carbos: 		 {x: 30,  y: 246, item: "surf" },
			it_hidden_rock:  {x: 33,  y: 90,  item: "overworld" },
		},
		mtmortarback: {
			topstairs:   {x: 137, y: 98,  name: "Mt. Mortar Back" },
			midstairs:   {x: 66,  y: 271, name: "Mt. Mortar Back" },
			leftstairs:  {x: 73,  y: 581, name: "Mt. Mortar Back" },
			leftdoor:    {x: 167, y: 722, name: "Mt. Mortar Back" },
			rightdoor:   {x: 455, y: 728, name: "Mt. Mortar Back" },
			rightstairs: {x: 498, y: 677, name: "Mt. Mortar Back" },
			
			it_escape_rope:  		{x: 549, y: 565, item: "overworld" },
			it_hyper_potion:		{x: 170, y: 417, item: "overworld" },
			it_nugget: 				{x: 523, y: 291, item: "overworld" },
			it_max_potion: 			{x: 343, y: 281, item: "overworld" },
			it_ultra_ball: 			{x: 237, y: 257, item: "overworld" },
			it_iron: 				{x: 120, y: 214, item: "overworld" },
			it_max_revive: 			{x: 246, y: 118, item: "overworld" },
			it_hidden_max_repel:	{x: 472, y: 136, item: "overworld" },
		},
		mtmortarf2: {
			door:   {x: 280, y: 519, corridor: "stairs" },
			stairs: {x: 62,  y: 65,  corridor: "door"   },
			
			it_rare_candy: 			{x: 58,  y: 513, item: "surf" }, //kinda need waterfall to get into the room first TODO
			it_max_potion: 			{x: 453, y: 377, item: "surf" },
			it_defense_curl: 		{x: 328, y: 276, item: "surf" },
			it_hidden_full_restore: {x: 366, y: 133, item: "surf" },
			it_escape_rope: 		{x: 476, y: 79,  item: "surf" },
			it_dragon_scale: 		{x: 283, y: 85,  item: "surf" },
			it_elixer: 				{x: 176, y: 176, item: "surf" },
		},
		mtsilver_r28: {
			r28_gate:	 {x: 636, y: 536,                          name: "Route 28" 	   },
			r28_house:	 {x: 426, y: 511,                          name: "Route 28" 	   },
			r28_center:	 {x: 267, y: 605,                          name: "Route 28" 	   },
			r28_cave:	 {x: 187, y: 535,                          name: "Route 28" 	   },
			f1_entrance: {x: 142, y: 451, corridor: "f1_door",     name: "Mt. Silver (1F)" },
			f1_door:     {x: 238, y: 39,  corridor: "f1_entrance", name: "Mt. Silver (1F)" },
			f2_entrance: {x: 562, y: 438,                          name: "Mt. Silver (2F)" },
			f2_left:     {x: 499, y: 279,                          name: "Mt. Silver (2F)" },
			f2_right:    {x: 636, y: 48,                           name: "Mt. Silver (2F)" },
			f2_exit:     {x: 467, y: 24,                           name: "Mt. Silver (2F)" },
			
			it_r28_hidden_rock:			{x: 536, y: 518, item: "cut" 		},
			it_r28_hidden_surf:			{x: 66,  y: 615, item: "surf" 		},
			it_f1_protein: 				{x: 209, y: 400, item: "overworld" 	},
			it_f1_escape_rope: 			{x: 49,  y: 415, item: "overworld" 	},
			it_f1_ultra_ball: 			{x: 82,  y: 245, item: "overworld" 	},
			it_f1_hidden_dire_hit: 		{x: 227, y: 306, item: "overworld" 	},
			it_f1_hidden_ultra_ball:	{x: 243, y: 167, item: "overworld" 	},
			it_f1_max_elixer: 			{x: 87,  y: 114, item: "overworld" 	},
			it_f2_hidden_max_potion: 	{x: 488, y: 466, item: "overworld" 	},
			it_f2_ultra_ball: 			{x: 669, y: 348, item: "overworld" 	},
			it_f2_pp_up: 				{x: 383, y: 285, item: "waterfall" 	},
			it_f2_calcium: 				{x: 646, y: 127, item: "waterfall"	},
		},
		radiotower: {
			entrance: {x: 49, y: 627}, //somewhat a deadend
			
			it_radiocard:     {x: 224, y: 632, item: "overworld" },
			it_buena:         {x: 211, y: 483, item: "overworld" },
			it_fake_director: {x: 32,  y: 100, item: "overworld" }, //req: 7+ badges TODO
			it_sunny_day:     {x: 207, y: 319, item: "card_key"  }, //req: 7+ badges + card key
			it_pink_bow:      {x: 208, y: 235, item: "card_key"  }, //req: 7+ badges + card key
			it_clear_bell:    {x: 239, y: 83,  item: "card_key"  }, //req: 7+ badges + card key
			it_ultra_ball:    {x: 159, y: 83,  item: "card_key"  }, //req: 7+ badges + card key
		},
		rockethq: {
			shop_entrance: {x: 63, y: 95}, //kinda deadend
	        
	        it_bf1_hyper_potion:	{x: 416, y: 76,  item: "overworld" }, //need lake of rage gyarados to even access this area
	        it_bf1_scientist: 		{x: 367, y: 171, item: "overworld" },
	        it_bf1_nugget: 			{x: 256, y: 219, item: "overworld" },
	        it_bf1_hidden: 			{x: 79,  y: 158, item: "overworld" },
	        it_bf2_lance: 			{x: 218, y: 396, item: "overworld" },
	        it_bf2_hidden: 			{x: 398, y: 336, item: "overworld" },
	        it_bf2_thief: 			{x: 82,  y: 380, item: "overworld" },
	        it_bf3_full_heal: 		{x: 432, y: 609, item: "overworld" },
	        it_bf3_ice_heal: 		{x: 304, y: 498, item: "overworld" },
	        it_bf3_ultra_ball:		{x: 208, y: 626, item: "overworld" },
	        it_bf3_xspecial: 		{x: 56,  y: 680, item: "overworld" },
	        it_bf3_protein: 		{x: 24,  y: 680, item: "overworld" },
		},
		rocktunnel_r9_r10: {
			r10_cave:		 {x: 593, y: 209,  							   name: "Route 10"  			},
			r10_center:		 {x: 642, y: 272,  							   name: "Route 10"  			},
			r10_plant:		 {x: 514, y: 399,  							   name: "Route 10" 		 	},
			r10_plant_in:	 {x: 506, y: 768, corridor: "r10_plant_in",    name: "Power Plant"  		},
			f1_entry_door:   {x: 234, y: 65,  corridor: "f1_entry_stairs", name: "Rock Tunnel (1F)" 	},
			f1_entry_stairs: {x: 425, y: 72,  corridor: "f1_entry_door",   name: "Rock Tunnel (1F)"  	},
			f1_exit_stairs:  {x: 427, y: 157, corridor: "f1_exit_door",    name: "Rock Tunnel (1F)"  	},
			f1_exit_door:    {x: 169, y: 364, corridor: "f1_exit_stairs",  name: "Rock Tunnel (1F)"   	},
			bf1_3item_left:  {x: 70,  y: 460, corridor: "bf1_3item_right", name: "Rock Tunnel (B1F)"	},
			bf1_3item_right: {x: 265, y: 560, corridor: "bf1_3item_left",  name: "Rock Tunnel (B1F)" 	},
			bf1_1item_top:   {x: 361, y: 467, corridor: "bf1_1item_bot",   name: "Rock Tunnel (B1F)"  	},
			bf1_1item_bot:   {x: 393, y: 723, corridor: "bf1_1item_top",   name: "Rock Tunnel (B1F)"  	},
			
			it_r9_hidden:			{x: 481, y: 260, item: "overworld" },
			it_machinepart:			{x: 714, y: 673, item: "machine_part_quest" }, //req: Getting Machine Part from Misty's Gym
			it_f1_left: 			{x: 59,  y: 239, item: "overworld" },
			it_f1_middle: 			{x: 154, y: 193, item: "overworld" },
			it_f1_hidden_bottom:	{x: 330, y: 193, item: "overworld" },
			it_f1_hidden_top: 		{x: 378, y: 17,  item: "overworld" },
			it_bf1_hidden: 			{x: 82,  y: 607, item: "overworld" },
			it_bf1_top: 			{x: 233, y: 442, item: "overworld" },
			it_bf1_bottom: 			{x: 79,  y: 781, item: "overworld" },
			it_bf1_middle: 			{x: 116, y: 654, item: "overworld" },
		},
		ruinsofalph: {
			alph_gate_n:	{x: 257, y: 98  						},
			alph_gate_s:	{x: 363, y: 336  						},
			alph_cave:		{x: 306, y: 236	 						},
			alph_house:		{x: 418, y: 200	 						},
			alph_nw:		{x: 369, y: 137  						},
			alph_sw:		{x: 402, y: 554  						},
			alph_s:			{x: 242, y: 457  						},
			alph_se:		{x: 178, y: 492  						},
			kabuto_top:     {x: 530, y: 190, corridor: "kabuto_bot",     name: "Alph (Escape)"    	},
			kabuto_bot:     {x: 530, y: 302, corridor: "kabuto_top",     name: "Alph (Escape)"     	},
			aerodactyl_top: {x: 530, y: 525, corridor: "aerodactyl_bot", name: "Alph (Flash)" 		},
			aerodactyl_bot: {x: 530, y: 638, corridor: "aerodactyl_top", name: "Alph (Flash)" 		},
			omanyte_top:    {x: 65,  y: 525, corridor: "omanyte_bot",    name: "Alph (Water Stone)" },
			omanyte_bot:    {x: 65,  y: 638, corridor: "omanyte_top",    name: "Alph (Water Stone)" },
			hooh_top:       {x: 65,  y: 190, corridor: "hooh_bot",       name: "Alph (Ho-oh)"       },
			hooh_bot:       {x: 65,  y: 302, corridor: "hooh_top",       name: "Alph (Ho-oh)"       },

			it_kabuto_NW: 		{x: 482, y: 73,  item: "overworld" }, //do we need to mark these ? I wouldnt TODO
			it_kabuto_NE: 		{x: 578, y: 73,  item: "overworld" },
			it_kabuto_SW: 		{x: 482, y: 105, item: "overworld" },
			it_kabuto_SE: 		{x: 578, y: 105, item: "overworld" },
			it_aerodactyl_NW:	{x: 482, y: 407, item: "overworld" },
			it_aerodactyl_NE: 	{x: 578, y: 407, item: "overworld" },
			it_aerodactyl_SW: 	{x: 482, y: 440, item: "overworld" },
			it_aerodactyl_SE: 	{x: 578, y: 440, item: "overworld" },
			it_omanyte_NW: 		{x: 17,  y: 407, item: "overworld" },
			it_omanyte_NE: 		{x: 114, y: 407, item: "overworld" },
			it_omanyte_SW: 		{x: 17,  y: 440, item: "overworld" },
			it_omanyte_SE: 		{x: 114, y: 440, item: "overworld" },
			it_hooh_NW: 		{x: 17,  y: 73,  item: "overworld" },
			it_hooh_NE: 		{x: 114, y: 73,  item: "overworld" },
			it_hooh_SW: 		{x: 17,  y: 105, item: "overworld" },
			it_hooh_SE: 		{x: 114, y: 105, item: "overworld" },
		},
		sprouttower: {
			floor1_left:    {x: 50,  y: 390, corridor: "floor1_right", name: "SproutTower (1F)" },
			floor1_right:	{x: 247, y: 341, corridor: "floor1_left",  name: "SproutTower (1F)" },
			floor2_left:    {x: 268, y: 402, corridor: "floor2_bot",   name: "SproutTower (2F)" },
			floor2_bot: 	{x: 395, y: 461, corridor: "floor2_left",  name: "SproutTower (2F)" },
        	top_floor:  	{x: 265, y: 202,                           name: "SproutTower (3F)" }, //deadend
			
        	it_paralyze_heal: 	{x: 201, y: 376, item: "overworld" },
        	it_xaccuracy:		{x: 260, y: 280, item: "overworld" },
        	it_potion: 			{x: 200, y: 249, item: "overworld" },
        	it_escape_rope: 	{x: 328, y: 41,  item: "overworld" },
        	it_elder: 			{x: 264, y: 59,  item: "overworld" },
		},
		ssaqua: {
			top3:     {x: 216, y: 121 },
			top4:     {x: 280, y: 155 },
			bot1:     {x: 88,  y: 231 },
			bot2:     {x: 152, y: 263 },
			bot3:     {x: 216, y: 231 },
			
			it_ship: {x: 283, y: 229, item: "overworld" }, //req: need ss-ticket to even get on the ship TODO
		},
		tintower: {
			f1:    {x: 652, y: 222, corridor: "f1",    name: "Tin Tower (1F)" },
			f3_s:  {x: 136, y: 729, corridor: "f3_ne", name: "Tin Tower (3F)" },
			f3_ne: {x: 208, y: 535, corridor: "f3_s",  name: "Tin Tower (3F)" },
			f4_sw: {x: 268, y: 781,                    name: "Tin Tower (4F)" },
			f4_nw: {x: 268, y: 618,                    name: "Tin Tower (4F)" },
			f4_ne: {x: 493, y: 536,                    name: "Tin Tower (4F)" },
			f4_se: {x: 509, y: 797,                    name: "Tin Tower (4F)" },
			f5_sw: {x: 529, y: 723,                    name: "Tin Tower (5F)" },
			f5_s:  {x: 673, y: 797,                    name: "Tin Tower (5F)" },
			f5_se: {x: 708, y: 722,                    name: "Tin Tower (5F)" },
			f5_nw: {x: 529, y: 623,                    name: "Tin Tower (5F)" },
			f6_s:  {x: 152, y: 485, corridor: "f6_w",  name: "Tin Tower (6F)" },
			f6_w:  {x: 70,  y: 440, corridor: "f6_s",  name: "Tin Tower (6F)" },
			f7_s:  {x: 397, y: 479,                    name: "Tin Tower (7F)" },
			f7_w:  {x: 285, y: 384,                    name: "Tin Tower (7F)" },
			f7_n:  {x: 364, y: 346,                    name: "Tin Tower (7F)" },
			f8_n:  {x: 657, y: 286, corridor: "f8_w",  name: "Tin Tower (8F)" },
			f8_w:  {x: 708, y: 411, corridor: "f8_n",  name: "Tin Tower (8F)" },
			f9_s1: {x: 365, y: 189,                    name: "Tin Tower (9F)" },
			f9_s2: {x: 333, y: 242,                    name: "Tin Tower (9F)" },
			f9_e:  {x: 493, y: 148,                    name: "Tin Tower (9F)" },
			f9_w:  {x: 268, y: 117, corridor: "f9_n",  name: "Tin Tower (9F)" },
			f9_n:  {x: 428, y: 82,  corridor: "f9_w",  name: "Tin Tower (9F)" },
			
			it_f1:                  {x: 623, y: 46,  item: "overworld" },
			it_f3:                  {x: 23,  y: 723, item: "overworld" },
			it_f4_right:            {x: 484, y: 757, item: "overworld" },
			it_f4_middle:           {x: 432, y: 685, item: "overworld" },
			it_f4_hidden:           {x: 389, y: 626, item: "overworld" },
			it_f4_left:             {x: 294, y: 717, item: "overworld" },
			it_f5_candy:            {x: 666, y: 668, item: "overworld" },
			it_f5_hidden_left:      {x: 573, y: 760, item: "overworld" },
			it_f5_hidden_right:     {x: 727, y: 760, item: "overworld" },
			it_f6:                  {x: 133, y: 395, item: "overworld" },
			it_f7:                  {x: 467, y: 279, item: "overworld" },
			it_f8_bottom:           {x: 637, y: 471, item: "overworld" },
			it_f8_middle:           {x: 649, y: 360, item: "overworld" },
			it_f8_top:              {x: 546, y: 306, item: "overworld" },
			it_f9:                  {x: 407, y: 23,  item: "overworld" },
		},
		unioncave: {
			f1_top:      	{x: 537, y: 81,  							 name: "Union Cave (1F)"  },
			f1_mid:      	{x: 378, y: 330, 							 name: "Union Cave (1F)"  },
			f1_right:    	{x: 537, y: 480, 							 name: "Union Cave (1F)"  },
			f1_left:     	{x: 349, y: 495, 							 name: "Union Cave (1F)"  },
			b1f_corridor_e:	{x: 537, y: 563, corridor: "b1f_corridor_w", name: "Union Cave (B1F)" },
			b1f_corridor_w:	{x: 346, y: 591, corridor: "b1f_corridor_e", name: "Union Cave (B1F)" },
			b1f_top:     	{x: 65,  y: 82,  							 name: "Union Cave (B1F)" },
			b1f_mid:     	{x: 65,  y: 210, 							 name: "Union Cave (B1F)" },
			b1f_bot:     	{x: 110, y: 329, 							 name: "Union Cave (B1F)" },
			b2f_deadend: 	{x: 77,  y: 404, 							 name: "Union Cave (B2F)" }, //deadend
			
			it_xattack:      {x: 362, y: 51,  item: "overworld" },
			it_great_ball:   {x: 571, y: 304, item: "overworld" },
			it_potion:       {x: 362, y: 239, item: "overworld" },
			it_awakening:    {x: 517, y: 521, item: "overworld" },
			it_swift:        {x: 30,  y: 274, item: "overworld" },
			it_xdefend:      {x: 269, y: 340, item: "overworld" },
			it_elixer:       {x: 254, y: 434, item: "surf"      },
			it_hyper_potion: {x: 189, y: 707, item: "surf"      },
		},
		victoryroad_reception: {
			reception_bot:   {x: 506, y: 593,                         name: "League Reception"  },
			reception_right: {x: 613, y: 432,                         name: "League Reception"  },
			reception_top:   {x: 505, y: 375,                         name: "League Reception"  },
			roadf1_bot:      {x: 160, y: 613, corridor: "roadf1_top", name: "Victory Road (1F)" },
			roadf1_top:      {x: 65,  y: 368, corridor: "roadf1_bot", name: "Victory Road (1F)" },
			roadf2_left:     {x: 65,  y: 134,                         name: "Victory Road (2F)" },
			roadf2_mid:      {x: 222, y: 66,                          name: "Victory Road (2F)" },
			roadf2_right:    {x: 287, y: 159,                         name: "Victory Road (2F)" },
			roadf3_hole:     {x: 356, y: 96,                          name: "Victory Road (3F)" },
			roadf3_mid:      {x: 566, y: 194,                         name: "Victory Road (3F)" },
			roadf3_bot:      {x: 613, y: 285,                         name: "Victory Road (3F)" },
			roadf3_top:      {x: 564, y: 62,                          name: "Victory Road (3F)" },
			
			it_f1_hidden_rock:	{x: 39,  y: 598, item: "overworld" },
			it_f1_left: 		{x: 207, y: 347, item: "overworld" },
			it_f1_right: 		{x: 256, y: 347, item: "overworld" },
			it_f2_bottom: 		{x: 153, y: 203, item: "overworld" },
			it_f2_right: 		{x: 303, y: 33,  item: "overworld" },
			it_f2_top: 			{x: 63,  y: 22,  item: "overworld" },
			it_f2_hidden: 		{x: 63,  y: 88,  item: "overworld" },
		},
		whirlislands: {
			f1_ne_entry:		{x: 506, y: 183, 							   name: "Whirl Islands (1F NE)" },
			f1_ne_n:			{x: 687, y: 66,  							   name: "Whirl Islands (1F NE)" },
			f1_ne_s:			{x: 667, y: 141, 							   name: "Whirl Islands (1F NE)" },
			f1_sw_entry:		{x: 238, y: 141, 							   name: "Whirl Islands (1F SW)" },
			f1_sw_e:			{x: 208, y: 71, 							   name: "Whirl Islands (1F SW)" },
			f1_sw_w:			{x: 432, y: 71, 							   name: "Whirl Islands (1F SW)" },
			f1_sw_corridor_e:	{x: 432, y: 200, corridor: "f1_sw_corridor_w", name: "Whirl Islands (1F SW)" },
			f1_sw_corridor_w:	{x: 206, y: 200, corridor: "f1_sw_corridor_e", name: "Whirl Islands (1F SW)" },
			b1f_nw:				{x: 225, y: 273, 							   name: "Whirl Islands (B1F)"   },
			b1f_ne:				{x: 687, y: 311, 							   name: "Whirl Islands (B1F)" 	 },
			b1f_cave:			{x: 419, y: 536, 							   name: "Whirl Islands (B1F)"   },
			b1f_sw:				{x: 289, y: 750, 							   name: "Whirl Islands (B1F)"   },
			b1f_midsw:			{x: 355, y: 687, 							   name: "Whirl Islands (B1F)"   },
			b1f_midse:			{x: 515, y: 750, 							   name: "Whirl Islands (B1F)"   },
			b1f_se:				{x: 642, y: 718, 							   name: "Whirl Islands (B1F)"   },
			b2f_n:				{x: 112, y: 307, 							   name: "Whirl Islands (B2F)"   },
			b2f_s:				{x: 143, y: 724, 							   name: "Whirl Islands (B2F)"   },
			b2f_cave:			{x: 66,  y: 628, 							   name: "Whirl Islands (B2F)"   },
			b2f_deadend:		{x: 66,  y: 399, 							   name: "Whirl Islands (B2F)"   }, //deadend: I added it because of the two items, but it otherwise it's obsolete
						
			it_f1_ne: 				{x: 634, y: 191, item: "overworld" },
			it_f1_sw: 				{x: 371, y: 21,  item: "overworld" },
			it_b2f_full_restore:	{x: 95,  y: 455, item: "overworld" },
			it_b2f_max_elixer: 		{x: 16,  y: 473, item: "overworld" },
			it_b2f_max_revive: 		{x: 32,  y: 343, item: "overworld" },
			it_b1f_hidden_w: 		{x: 204, y: 594, item: "overworld" },
			it_b1f_hidden_e: 		{x: 696, y: 510, item: "overworld" },
			it_b1f_hidden_n: 		{x: 600, y: 287, item: "overworld" },
			it_b1f_n: 				{x: 395, y: 350, item: "overworld" },
			it_b1f_s: 				{x: 474, y: 637, item: "overworld" },
			it_b1f_e: 				{x: 699, y: 590, item: "overworld" },
			it_b1f_nw: 				{x: 235, y: 429, item: "overworld" },
			it_b1f_sw: 				{x: 205, y: 510, item: "overworld" },
		},
		
		//for shopsanity
		shop_johto: { 
			it_cherrygrove1: {x: 230, y: 112, item: "overworld" },
			it_cherrygrove2: {x: 260, y: 112, item: "overworld" },
			it_cherrygrove3: {x: 290, y: 112, item: "overworld" },
			it_cherrygrove4: {x: 320, y: 112, item: "overworld" },
			it_cherrygrove5: {x: 350, y: 112, item: "overworld" },

			it_violet1: {x: 230, y: 158, item: "overworld" },
			it_violet2: {x: 260, y: 158, item: "overworld" },
			it_violet3: {x: 290, y: 158, item: "overworld" },
			it_violet4: {x: 320, y: 158, item: "overworld" },
			it_violet5: {x: 350, y: 158, item: "overworld" },

			it_azalea1: {x: 230, y: 204, item: "overworld" },
			it_azalea2: {x: 260, y: 204, item: "overworld" },
			it_azalea3: {x: 290, y: 204, item: "overworld" },
			it_azalea4: {x: 320, y: 204, item: "overworld" },
			it_azalea5: {x: 350, y: 204, item: "overworld" },

			it_ecruteak1: {x: 230, y: 250, item: "overworld" },
			it_ecruteak2: {x: 260, y: 250, item: "overworld" },
			it_ecruteak3: {x: 290, y: 250, item: "overworld" },
			it_ecruteak4: {x: 320, y: 250, item: "overworld" },
			it_ecruteak5: {x: 350, y: 250, item: "overworld" },

			it_olivine1: {x: 230, y: 296, item: "overworld" },
			it_olivine2: {x: 260, y: 296, item: "overworld" },
			it_olivine3: {x: 290, y: 296, item: "overworld" },
			it_olivine4: {x: 320, y: 296, item: "overworld" },
			it_olivine5: {x: 350, y: 296, item: "overworld" },

			it_cianwood1: {x: 230, y: 342, item: "overworld" },
			it_cianwood2: {x: 260, y: 342, item: "overworld" },
			it_cianwood3: {x: 290, y: 342, item: "overworld" },
			it_cianwood4: {x: 320, y: 342, item: "overworld" },
			it_cianwood5: {x: 350, y: 342, item: "overworld" },

			it_mahagony_rocket1: {x: 230, y: 388, item: "overworld" },
			it_mahagony_rocket2: {x: 260, y: 388, item: "overworld" },
			it_mahagony_rocket3: {x: 290, y: 388, item: "overworld" },
			it_mahagony_rocket4: {x: 320, y: 388, item: "overworld" },
			it_mahagony_rocket5: {x: 350, y: 388, item: "overworld" },

			it_mahagony1: {x: 230, y: 434, item: "overworld" },
			it_mahagony2: {x: 260, y: 434, item: "overworld" },
			it_mahagony3: {x: 290, y: 434, item: "overworld" },
			it_mahagony4: {x: 320, y: 434, item: "overworld" },
			it_mahagony5: {x: 350, y: 434, item: "overworld" },

			it_blackthorn1: {x: 230, y: 480, item: "overworld" },
			it_blackthorn2: {x: 260, y: 480, item: "overworld" },
			it_blackthorn3: {x: 290, y: 480, item: "overworld" },
			it_blackthorn4: {x: 320, y: 480, item: "overworld" },
			it_blackthorn5: {x: 350, y: 480, item: "overworld" },
			
			it_gr_ug_top1: {x: 610, y: 158, item: "overworld" },
			it_gr_ug_top2: {x: 640, y: 158, item: "overworld" },
			it_gr_ug_top3: {x: 670, y: 158, item: "overworld" },
			it_gr_ug_top4: {x: 700, y: 158, item: "overworld" },
			it_gr_ug_top5: {x: 730, y: 158, item: "overworld" },
			
			it_gr_ug_bottom1: {x: 610, y: 204, item: "overworld" },
			it_gr_ug_bottom2: {x: 640, y: 204, item: "overworld" },
			it_gr_ug_bottom3: {x: 670, y: 204, item: "overworld" },
			it_gr_ug_bottom4: {x: 700, y: 204, item: "overworld" },
			it_gr_ug_bottom5: {x: 730, y: 204, item: "overworld" },
			
			it_gr_f2_top1: {x: 610, y: 250, item: "overworld" },
			it_gr_f2_top2: {x: 640, y: 250, item: "overworld" },
			it_gr_f2_top3: {x: 670, y: 250, item: "overworld" },
			it_gr_f2_top4: {x: 700, y: 250, item: "overworld" },
			it_gr_f2_top5: {x: 730, y: 250, item: "overworld" },
			
			it_gr_f2_bottom1: {x: 610, y: 296, item: "overworld" },
			it_gr_f2_bottom2: {x: 640, y: 296, item: "overworld" },
			it_gr_f2_bottom3: {x: 670, y: 296, item: "overworld" },
			it_gr_f2_bottom4: {x: 700, y: 296, item: "overworld" },
			it_gr_f2_bottom5: {x: 730, y: 296, item: "overworld" },
			
			it_gr_f3_1: {x: 610, y: 342, item: "overworld" },
			it_gr_f3_2: {x: 640, y: 342, item: "overworld" },
			it_gr_f3_3: {x: 670, y: 342, item: "overworld" },
			it_gr_f3_4: {x: 700, y: 342, item: "overworld" },
			it_gr_f3_5: {x: 730, y: 342, item: "overworld" },
			
			it_gr_f4_1: {x: 610, y: 388, item: "overworld" },
			it_gr_f4_2: {x: 640, y: 388, item: "overworld" },
			it_gr_f4_3: {x: 670, y: 388, item: "overworld" },
			it_gr_f4_4: {x: 700, y: 388, item: "overworld" },
			it_gr_f4_5: {x: 730, y: 388, item: "overworld" },
			
			it_gr_f5_1: {x: 610, y: 434, item: "overworld" },
			it_gr_f5_2: {x: 640, y: 434, item: "overworld" },
			it_gr_f5_3: {x: 670, y: 434, item: "overworld" },
			it_gr_f5_4: {x: 700, y: 434, item: "overworld" },
			it_gr_f5_5: {x: 730, y: 434, item: "overworld" },
        },
        
        shop_kanto: {        
        	it_viridian1: {x: 230, y: 112, item: "overworld" },
			it_viridian2: {x: 260, y: 112, item: "overworld" },
			it_viridian3: {x: 290, y: 112, item: "overworld" },
			it_viridian4: {x: 320, y: 112, item: "overworld" },
			it_viridian5: {x: 350, y: 112, item: "overworld" },

			it_mtmoon1: {x: 230, y: 158, item: "overworld" },
			it_mtmoon2: {x: 260, y: 158, item: "overworld" },
			it_mtmoon3: {x: 290, y: 158, item: "overworld" },
			it_mtmoon4: {x: 320, y: 158, item: "overworld" },
			it_mtmoon5: {x: 350, y: 158, item: "overworld" },

			it_pewter1: {x: 230, y: 204, item: "overworld" },
			it_pewter2: {x: 260, y: 204, item: "overworld" },
			it_pewter3: {x: 290, y: 204, item: "overworld" },
			it_pewter4: {x: 320, y: 204, item: "overworld" },
			it_pewter5: {x: 350, y: 204, item: "overworld" },

			it_cerulean1: {x: 230, y: 250, item: "overworld" },
			it_cerulean2: {x: 260, y: 250, item: "overworld" },
			it_cerulean3: {x: 290, y: 250, item: "overworld" },
			it_cerulean4: {x: 320, y: 250, item: "overworld" },
			it_cerulean5: {x: 350, y: 250, item: "overworld" },

			it_vermilion1: {x: 230, y: 296, item: "overworld" },
			it_vermilion2: {x: 260, y: 296, item: "overworld" },
			it_vermilion3: {x: 290, y: 296, item: "overworld" },
			it_vermilion4: {x: 320, y: 296, item: "overworld" },
			it_vermilion5: {x: 350, y: 296, item: "overworld" },

			it_lavender1: {x: 230, y: 342, item: "overworld" },
			it_lavender2: {x: 260, y: 342, item: "overworld" },
			it_lavender3: {x: 290, y: 342, item: "overworld" },
			it_lavender4: {x: 320, y: 342, item: "overworld" },
			it_lavender5: {x: 350, y: 342, item: "overworld" },

			it_fuchsia1: {x: 230, y: 388, item: "overworld" },
			it_fuchsia2: {x: 260, y: 388, item: "overworld" },
			it_fuchsia3: {x: 290, y: 388, item: "overworld" },
			it_fuchsia4: {x: 320, y: 388, item: "overworld" },
			it_fuchsia5: {x: 350, y: 388, item: "overworld" },

			it_saffron1: {x: 230, y: 434, item: "overworld" },
			it_saffron2: {x: 260, y: 434, item: "overworld" },
			it_saffron3: {x: 290, y: 434, item: "overworld" },
			it_saffron4: {x: 320, y: 434, item: "overworld" },
			it_saffron5: {x: 350, y: 434, item: "overworld" },

			it_indigo_plateau1: {x: 230, y: 480, item: "overworld" },
			it_indigo_plateau2: {x: 260, y: 480, item: "overworld" },
			it_indigo_plateau3: {x: 290, y: 480, item: "overworld" },
			it_indigo_plateau4: {x: 320, y: 480, item: "overworld" },
			it_indigo_plateau5: {x: 350, y: 480, item: "overworld" },
			
			it_c_f2_top1: {x: 610, y: 158, item: "overworld" },
			it_c_f2_top2: {x: 640, y: 158, item: "overworld" },
			it_c_f2_top3: {x: 670, y: 158, item: "overworld" },
			it_c_f2_top4: {x: 700, y: 158, item: "overworld" },
			it_c_f2_top5: {x: 730, y: 158, item: "overworld" },
			
			it_c_f2_bottom1: {x: 610, y: 204, item: "overworld" },
			it_c_f2_bottom2: {x: 640, y: 204, item: "overworld" },
			it_c_f2_bottom3: {x: 670, y: 204, item: "overworld" },
			it_c_f2_bottom4: {x: 700, y: 204, item: "overworld" },
			it_c_f2_bottom5: {x: 730, y: 204, item: "overworld" },
			
			it_c_f3_1: {x: 610, y: 250, item: "overworld" },
			it_c_f3_2: {x: 640, y: 250, item: "overworld" },
			it_c_f3_3: {x: 670, y: 250, item: "overworld" },
			it_c_f3_4: {x: 700, y: 250, item: "overworld" },
			it_c_f3_5: {x: 730, y: 250, item: "overworld" },
			
			it_c_f4_1: {x: 610, y: 296, item: "overworld" },
			it_c_f4_2: {x: 640, y: 296, item: "overworld" },
			it_c_f4_3: {x: 670, y: 296, item: "overworld" },
			it_c_f4_4: {x: 700, y: 296, item: "overworld" },
			it_c_f4_5: {x: 730, y: 296, item: "overworld" },
			
			it_c_f5_left1: {x: 610, y: 342, item: "overworld" },
			it_c_f5_left2: {x: 640, y: 342, item: "overworld" },
			it_c_f5_left3: {x: 670, y: 342, item: "overworld" },
			it_c_f5_left4: {x: 700, y: 342, item: "overworld" },
			it_c_f5_left5: {x: 730, y: 342, item: "overworld" },
			
			it_c_f5_right1: {x: 610, y: 388, item: "overworld" },
			it_c_f5_right2: {x: 640, y: 388, item: "overworld" },
			it_c_f5_right3: {x: 670, y: 388, item: "overworld" },
			it_c_f5_right4: {x: 700, y: 388, item: "overworld" },
			it_c_f5_right5: {x: 730, y: 388, item: "overworld" },
        },
	
	},

    // Numbers are meant to be to check if exist any marks/progress in the maps
    // if null, then we don't do tracking
    // if undefined, then we don't draw the mark
    marks: [
        [["unknown",     0], ["corridor",    0], ["dead_end", null], ["event",      0], ["center",      0], ["mart",         0], ["one_way",  null]],
        [["item_overworld", 0], ["item_checked", null], ["item_event", 0], ["item_surf", 0], ["item_cut", 0], ["item_strength", 0], ["item_rocksmash", 0], ["item_whirl", 0],["item_basement_key", 0],["item_phone", 0]],
        //[],
        [["normal",      0], ["fighting",    0], ["flying",      0], ["poison",     0], ["ground",      0], ["rock",         0], ["bug",         0], ["ghost",       0], ["fairy",     0]],
        [["steel",       0], ["fire",        0], ["water",       0], ["grass",      0], ["electric",    0], ["psychic",      0], ["ice",         0], ["dragon",      0], ["dark",      0]],
        [["1",           0], ["2",           0], ["3",           0], ["4",          0], ["5",           0], ["6",            0], ["7",           0], ["8",           0]],
		[["team_rocket", 0], ["c_rival",     0], ["c_gyarados",  0], ["",   undefined], ["c_legendary", 0], ["burned_tower", 0], ["c_kurt",      0], ["c_unown",     0], ["c_train",   0], ["dratini", 0], ["c_daycare" ,0]],
        [["c_bush",      0], ["c_surf",      0], ["c_boulder",   0], ["c_darkness", 0], ["c_whirlpool", 0], ["c_waterfall",  0], ["c_rock",      0], ["bike_needed", 0], ["c_trainer", 0]],
    ],
    progress: [
        [["zephyr_badge",  0], ["hive_badge",    0], ["plain_badge",    0], ["fog_badge",     0], ["storm_badge",   0], ["mineral_badge", 0], ["glacier_badge", 0], ["rising_badge", 0]],
        [["boulder_badge", 0], ["cascade_badge", 0], ["thunder_badge",  0], ["rainbow_badge", 0], ["soul_badge",    0], ["marsh_badge",   0], ["volcano_badge", 0], ["earth_badge",  0]],
        [["c_will",        0], ["c_koga",        0], ["c_bruno",        0], ["c_karen",       0], ["c_lance",       0], ["",      undefined], ["c_oak",         0], ["c_red",        0]],
        [["hm_cut",        0], ["hm_fly",        0], ["hm_surf",        0], ["hm_strength",   0], ["hm_flash",      0], ["hm_whirlpool",  0], ["hm_waterfall",  0], ["hm_rocksmash", 0]],
        [["pokegear",      0], ["radio_card",    0], ["expansion_card", 0], ["squirt_bottle", 0], ["secret_potion", 0], ["card_key",      0], ["ss_ticket",     0], ["pass",         0]],
        [["machine_part",  0], ["clear_bell",    0], ["rainbow_wing",   0], ["silver_wing",   0], ["basement_key",  0], ["lost_item",     0], ["red_scale",     0], ["mystery_egg",  0]],
        [["pokedex",       0], ["bike",          0], ["blue_card",      0], ["coin_case",     0], ["itemfinder",    0], ["old_rod",       0], ["good_rod",      0], ["super_rod",    0]],
    ],
	modifiers: [
		[["#ce4069", 0], ["#ff9c54", 0], ["#f3d23b", 0], ["#743683", 0], ["#654321", 0], ["#014f01", 0]],
		[["#4d90d5", 0], ["#74cec0", 0], ["#90c12c", 0], ["#ec8fe6", 0], ["#5a5366", 0], ["#00146b", 0]],
	],
};
