let gen3crossover = {
	debug: false,
    name: "gen3crossover",
    folder: "gen3crossover",
    start_location: "viridian",
    font: "GameBoy_Font",
    font_size: "22px",

    // Config texts
	config_name: "FireRed+CrystalDust+Emerald Crossover",
	config_randomizer_author: "KittyPBoxx",
	config_randomizer_link: "https://kittypboxx.github.io/GBAXG/",
	//config_tracker_author: "", 
	//config_tracker_link: "",

	// Tracker information
    locations: {

        /*
        *************
        *** KANTO ***     
        *************
        */			

        // Cities
        viridian:         {x: 229,  y: 60,  w: 8,  h: 8,  name: "Viridian City\nRoute 22",       link_name: "Viridian City"   },
        pewter:           {x: 229,  y: 28,  w: 8,  h: 8,  name: "Pewter City"                                                 },
        cerulean:         {x: 309,  y: 20,  w: 8,  h: 8,  name: "Cerulean City\nRoutes 5 & 25",  link_name: "Cerulean City"   },
        vermilion:        {x: 309,  y: 68,  w: 8,  h: 8,  name: "Vermilion City\nRoutes 6 & 11", link_name: "Vermilion City"  },
        lavender:         {x: 341,  y: 44,  w: 8,  h: 8,  name: "Lavender Town\nRoute 8",        link_name: "Lavender Town"   },
        celadon:          {x: 285,  y: 44,  w: 8,  h: 8,  name: "Celadon City\nRoutes 7 & 16",   link_name: "Celadon City"    },
        saffron:          {x: 309,  y: 44,  w: 8,  h: 8,  name: "Saffron City"                                                },
        fuchsia:          {x: 293,  y: 92,  w: 8,  h: 8,  name: "Fuchsia City\nRoutes 15 & 18",  link_name: "Fuchsia City"    },
        cinnabar:         {x: 229,  y: 108, w: 8,  h: 8,  name: "Cinnabar Island"                                             },
        indigo:           {x: 213,  y: 20,  w: 8,  h: 8,  name: "Indigo Plateau"                                              },
    
        // Routes
        r2:               {x: 229,  y: 44,  w: 8,  h: 8,  name: "Route 2"                                                     },
        r10:              {x: 341,  y: 28,  w: 8,  h: 8,  name: "Route 10"                                                    },
        r12:              {x: 341,  y: 68,  w: 8,  h: 8,  name: "Route 12"                                                    },
        r15:              {x: 303,  y: 92,  w: 8,  h: 8,  name: "Route 15"                                                    },
    
        // Important locations
        cerulean_cave:    {x: 301,  y: 12,  w: 8,  h: 8,  name: "Cerulean Cave"                                               },
        department_store: {x: 285,  y: 35,  w: 8,  h: 8,  name: "Celadon\nDepartment Store",     link_name: "Celadon Store"   },
        cinnabar_mansion: {x: 220,  y: 108, w: 8,  h: 8,  name: "Cinnabar Mansion"                                            },
        mt_moon:          {x: 269,  y: 20,  w: 8,  h: 8,  name: "Mt. Moon\nRoute 4",             link_name: "Mt. Moon"        },
        rocket_hideout:   {x: 285,  y: 53,  w: 8,  h: 8,  name: "Rocket Hideout"                                              },
        seafoam_islands:  {x: 262,  y: 108, w: 8,  h: 8,  name: "Seafoam Islands\nRoute 20",     link_name: "Seafoam Islands" },
        silph_1:          {x: 318,  y: 44,  w: 8,  h: 8,  name: "Silph Co.\n1F to 5F",           link_name: "Silph Co."       },
        silph_2:          {x: 318,  y: 35,  w: 8,  h: 8,  name: "Silph Co.\n6F to 11F",          link_name: "Silph Co."       },
        ss_anne:          {x: 309,  y: 77,  w: 8,  h: 8,  name: "SS Anne"                                                     },
        victory_road:     {x: 213,  y: 29,  w: 8,  h: 8,  name: "Victory Road"                                                },
        gates:            {x: 269,  y: 4,   w: 8,  h: 8,  name: "Gates",                         link_name: "Gate"            },
        rocktunnel1:	  {x: 333,  y: 28,  w: 8,  h: 8,  name: "Rock Tunnel",                  							  },
        rocktunnel2:	  {x: 333,  y: 36,  w: 8,  h: 8,  name: "Rock Tunnel",                   							  },
        pokemontower:     {x: 350,  y: 44,  w: 8,  h: 8,  name: "Pokémon Tower"                                               },
        cyclingroad:      {x: 253,  y: 68,  w: 8,  h: 8,  name: "Cycling Road"                                                },


        /*
        *************
        *** JOHTO ***     
        *************
        */

        // Cities
        newbark:         {x: 183, y: 92, w: 8,  h: 8,  name: "New Bark Town"              },
        cherrygrove_r29: {x: 135, y: 92, w: 17, h: 8,  name: "Cherrygrove City\nRoute 29" },
        violet:          {x: 103, y: 44, w: 8,  h: 8,  name: "Violet City"                },
        azalea_well:     {x: 87,  y: 108,w: 8,  h: 8,  name: "Azalea Town\nSlowpoke Well" },
        goldenrod:       {x: 71,  y: 68, w: 8,  h: 8,  name: "Goldenrod City"             },
        ecruteak:        {x: 87,  y: 28, w: 8,  h: 8,  name: "Ecruteak City"              },
        olivine_r40:     {x: 31,  y: 43, w: 8,  h: 17, name: "Olivine City\nRoute 38-40"  },
        cianwood:        {x: 7,   y: 84, w: 8,  h: 8,  name: "Cianwood City"              },
        mahogany_r44:    {x: 127, y: 28, w: 8,  h: 8,  name: "Mahogany Town\nRoute 44"    },
        blackthorn:      {x: 167, y: 28, w: 8,  h: 8,  name: "Blackthorn City"            },
        indigo_e4:       {x: 204, y: 20, w: 8,  h: 8,  name: "Indigo Plateau\nElite 4"    },
        
        // Routes
        r45_r46:       {x: 167, y: 60,  w: 8,  h: 8, name: "Route 45\nRoute 46"      },
        r30_r31:       {x: 135, y: 67,  w: 8,  h: 8, name: "Route 30\nRoute 31"      },
        alphruins_r32: {x: 103, y: 83,  w: 8,  h: 8, name: "Ruins of Alph\nRoute 32" },
        r34_ilex:      {x: 71,  y: 91,  w: 8,  h: 8, name: "Route 34\nIlex Forest"   },
        r35_r36:       {x: 71,  y: 44,  w: 8,  h: 8, name: "Route 35\nRoute 36"      },
        r41:           {x: 23,  y: 65,  w: 8,  h: 8, name: "Route 41"                },
        ragelake_r43:  {x: 127, y: 19,  w: 8,  h: 8, name: "Lake of Rage\nRoute 43"  },
        r26_r27:       {x: 213, y: 92,  w: 8,  h: 8, name: "Route 26\nRoute 27"      },

        // Important locations
        darkcave:              {x: 150, y: 60, w: 8, h: 8,  name: "Dark Cave"                      },
        puzzlechambers:        {x: 94,  y: 53, w: 8, h: 8,  name: "Puzzle Chambers"                },
        unioncave:             {x: 103, y: 108,w: 8, h: 8,  name: "Union Cave"                     },
        goldenrodstore:        {x: 80,  y: 64, w: 8, h: 8,  name: "Goldenrod\nDepartment Store"    },
        underground:           {x: 80,  y: 73, w: 8, h: 8,  name: "Underground"                    },
        mtmortar_r42:          {x: 101, y: 28, w: 8, h: 8,  name: "Mt. Mortar Entry\nRoute 42"     },
        mtmortarback:          {x: 101, y: 19, w: 8, h: 8,  name: "Mt. Mortar Back"                },
        mtmortarf2:            {x: 101, y: 10, w: 8, h: 8,  name: "Mt. Mortar F2"                  },
        mtmortarb1f:           {x: 110, y: 19, w: 8, h: 8,  name: "Mt. Mortar B1F"                 },
        lighthouse:            {x: 40,  y: 52, w: 8, h: 8,  name: "Olivine's Lighthouse"           },
        whirlislands:          {x: 19,  y: 80, w: 8, h: 8,  name: "Whirl Islands"                  },
        icepath1:              {x: 167, y: 19, w: 8, h: 8,  name: "Ice Path"                       },
        victoryroad_reception: {x: 204, y: 29, w: 8, h: 8,  name: "Victory Road\nLeague Reception" },

        /*
        *************
        *** HOENN ***     
        *************
        */

        // Cities
        littleroot:     {x: 47,  y: 224, w: 8,  h: 8,  name: "Littleroot Town"           },
        oldale:         {x: 47,  y: 208, w: 8,  h: 8,  name: "Oldale Town"               },
        petalburg:      {x: 23,  y: 208, w: 8,  h: 8,  name: "Petalburg City"            },
        rustboro:       {x: 15,  y: 176, w: 8,  h: 16, name: "Rustboro City"             },
        dewford:        {x: 31,  y: 248, w: 8,  h: 8,  name: "Dewford Town"              },
        slateport_r109: {x: 79,  y: 216, w: 8,  h: 16, name: "Slateport City\nRoute 109" },
        mauville_r117:  {x: 79,  y: 184, w: 16, h: 8,  name: "Mauville City\nRoute 117"  },
        verdanturf:     {x: 47,  y: 184, w: 8,  h: 8,  name: "Verdanturf Town"           },
        fallarbor_r113: {x: 39,  y: 136, w: 8,  h: 8,  name: "Fallarbor Town\nRoute 113" },
        lavaridge:      {x: 55,  y: 160, w: 8,  h: 8,  name: "Lavaridge Town"            },
        fortree:        {x: 111, y: 136, w: 8,  h: 8,  name: "Fortree City"              },
        lilycove:       {x: 159, y: 160, w: 16, h: 8,  name: "Lilycove City"             },
        mossdeep_r124:  {x: 207, y: 176, w: 16, h: 8,  name: "Mossdeep City\nRoute 124"  },
        sootopolis:     {x: 183, y: 192, w: 8,  h: 8,  name: "Sootopolis City"           },
        pacifidlog:     {x: 151, y: 216, w: 8,  h: 8,  name: "Pacifidlog Town"           },
        evergrande:     {x: 231, y: 200, w: 8,  h: 16, name: "Ever Grande City\nElite 4" },

        // Routes
        petalburgwoods_r104: {x: 15,  y: 198, w: 8, h: 8, name: "Petalburg Woods\nRoute 104" },
        rusturftunnel_r116:  {x: 34,  y: 176, w: 8, h: 8, name: "Rusturf Tunnel\nRoute 116"  },
        r110:                {x: 79,  y: 199, w: 8, h: 8, name: "Route 110"                  },
        r111_r112:           {x: 79,  y: 147, w: 8, h: 8, name: "Route 111\nRoute 112"       },
        r114:                {x: 23,  y: 136, w: 8, h: 8, name: "Route 114"                  },
        r119_r123:           {x: 103, y: 160, w: 8, h: 8, name: "Route 119\nRoute 123"       },
        r120_r121:           {x: 127, y: 160, w: 8, h: 8, name: "Route 120\nRoute 121"       },

        // Important locations
        granitecave_r105_r106:   {x: 15,  y: 240, w: 8, h: 8, name: "Granite Cave\nRoute 105/106" },
        abandonedship_r108:      {x: 67,  y: 248, w: 8, h: 8, name: "Abandoned Ship\nRoute 108"   },
        miragetower:             {x: 79,  y: 171, w: 8, h: 8, name: "Mirage Tower"                },
        magmahideout_jaggedpass: {x: 69,  y: 160, w: 8, h: 8, name: "Magma Hideout\nJagged Pass"  },
        meteorfalls_r115:        {x: 15,  y: 152, w: 8, h: 8, name: "Meteor Falls\nRoute 115"     },
        mtpyre_r122:             {x: 143, y: 173, w: 8, h: 8, name: "Mt. Pyre\nRoute 122"         },
        departmentstore:         {x: 159, y: 147, w: 8, h: 8, name: "Lilycove\nDepartment Store"  },
        aquahideout:             {x: 180, y: 160, w: 8, h: 8, name: "Aqua Hideout"                },
        seafloor_underwater:     {x: 207, y: 192, w: 8, h: 8, name: "Seafloor Cavern\nUnderwater" },
        skypillar_r131:          {x: 176, y: 216, w: 8, h: 8, name: "Sky Pillar\nRoute 131"       },
        victoryroad:             {x: 244, y: 200, w: 8, h: 8, name: "Victory Road"                },
        victoryroad_corridors:   {x: 244, y: 190, w: 8, h: 8, name: "Victory Road\n(Corridors)"   },
        navelrock:               {x: 336, y: 122,  w: 8, h: 8, name: "Navel Rock"                 },
    },

    // Undefined fields:
    // - link_type:     "warp"        / "mark"
    // - link:          warp_name     / mark_name
    // - link_location: location_name / <garbage>
    warps: {

        /*
        *************
        *** KANTO ***     
        *************
        */

        celadon: {
            r16_top:            {x: 92,   y: 212,                      name: "R16 (Celadon)"       },
            r16_bottom:         {x: 92,   y: 323,                      name: "R16 (Celadon)"       },
            dept_left:          {x: 263,  y: 213,                      name: "Celadon City"        },
            dept_right:         {x: 329,  y: 163,                      name: "Celadon City"        },
            n_front:            {x: 566,  y: 129,                      name: "Celadon City"        },
            n_back:             {x: 568,  y: 34,                       name: "Celadon City"        },
            center:             {x: 853,  y: 126,                      name: "Celadon City"        },
            gym:                {x: 276,  y: 425,                      name: "Celadon City (Gym)"  },
            casino_left:        {x: 631,  y: 321,                      name: "Celadon City"        },
            casino_right:       {x: 708,  y: 272,                      name: "Celadon City"        },
            sw:                 {x: 676,  y: 457,                      name: "Celadon City"        },
            s:                  {x: 749,  y: 400,                      name: "Celadon City"        },
            se:                 {x: 878,  y: 457,                      name: "Celadon City"        },
            r7_underground:     {x: 992,  y: 535,                      name: "R7 (Celadon)"        },
            r7_gate:            {x: 1100, y: 477,                      name: "R7 (Celadon)"        },
            tea_bot:            {x: 1100, y: 271, corridor: "tea_top", name: "Celadon (Tea Lady)"  },
			tea_top:            {x: 1100, y: 67,  corridor: "tea_bot", name: "Celadon (Tea Lady)"  },
        },
        cerulean: {
            nw:                 {x: 169,  y: 150, name: "Cerulean City"       },
            n:                  {x: 286,  y: 149, name: "Cerulean City"       },
            c:                  {x: 247,  y: 243, name: "Cerulean City"       },
            center:             {x: 358,  y: 278, name: "Cerulean City"       },
            gym:                {x: 506,  y: 310, name: "Cerulean City"       },
            ne_front:           {x: 511,  y: 176, name: "Cerulean City"       },
            ne_back:            {x: 509,  y: 106, name: "Cerulean City"       },
            bike:               {x: 218,  y: 429, name: "Cerulean City"       },
            s:                  {x: 375,  y: 413, name: "Cerulean City"       },
            mart:               {x: 481,  y: 464, name: "Cerulean City"       },
            r25_bill:           {x: 775,  y: 44,  name: "R25 (Cerulean)"      },
            r5_daycare:         {x: 774,  y: 474, name: "R5 (Cerulean)"       },
            r5_gate:            {x: 799,  y: 617, name: "R5 (Cerulean)"       },
            r5_underground:     {x: 905,  y: 558, name: "R5 (Cerulean)"       },
        },
        cerulean_cave: {
            w:                  {x: 86,   y: 230,                                                  },
            nw:                 {x: 169,  y: 45,                                                   },
            c:                  {x: 391,  y: 193,                                                  },
            e:                  {x: 489,  y: 143,                                                  },
            ne:                 {x: 554,  y: 48,                                                   },
            entrance:           {x: 534,  y: 339,                                                  },
			f2_left:            {x: 85,   y: 451, corridor: "f2_right", name: "Cerulean Cave (F2)" },
			f2_right:           {x: 376,  y: 511, corridor: "f2_left",  name: "Cerulean Cave (F2)" },
        },
        cinnabar: {
            mansion:            {x: 135,  y: 32,  name: "Cinnabar Island"     },
            gym:                {x: 321,  y: 40,  name: "Cinnabar Island"     },
            lab:                {x: 131,  y: 131, name: "Cinnabar Island"     },
            center:             {x: 219,  y: 158, name: "Cinnabar Island"     },
            mart:               {x: 313,  y: 139, name: "Cinnabar Island"     },
            lab_entrance:       {x: 70,   y: 483, name: "Cinnabar Lab"        },
            lab_w:              {x: 214,  y: 390, name: "Cinnabar Lab"        },
            lab_c:              {x: 311,  y: 446, name: "Cinnabar Lab"        },
            lab_e:              {x: 410,  y: 383, name: "Cinnabar Lab"        },
        },
        cinnabar_mansion: {
            _1f_entrance_w:     {x: 134,  y: 671, name: "Mansion 1F"          },
            _1f_stairs_n:       {x: 159,  y: 363, name: "Mansion 1F"          },
            _1f_stairs_s:       {x: 386,  y: 570, name: "Mansion 1F"          },
            _1f_entrance_e:     {x: 553,  y: 666, name: "Mansion 1F"          },
            _2f_stairs_sw:      {x: 74,   y: 269, name: "Mansion 2F"          },
            _2f_stairs_se:      {x: 188,  y: 199, name: "Mansion 2F"          },
            _2f_stairs_n:       {x: 142,  y: 33,  name: "Mansion 2F"          },
            _3f_stairs_n:       {x: 447,  y: 222, name: "Mansion 3F"          },
            _3f_stairs_se:      {x: 859,  y: 465, name: "Mansion 3F"          },
            _3f_drop_w:         {x: 611,  y: 454, name: "Mansion 3F"          },
            _3f_drop_e:         {x: 709,  y: 506, name: "Mansion 3F"          },
        },
        department_store: {
            _1f_entrance_w:     {x: 38,   y: 478, name: "Celadon Store" },
            _1f_entrance_e:     {x: 168,  y: 479, name: "Celadon Store" },
            _1f_stairs:         {x: 53,   y: 271, name: "Celadon Store" },
            _2f_stairs_w:       {x: 33,   y: 66,  name: "Celadon Store" },
            _2f_stairs_e:       {x: 172,  y: 10,  name: "Celadon Store" },
            _4f_stairs_w:       {x: 257,  y: 83,  name: "Celadon Store" },
            _4f_stairs_e:       {x: 402,  y: 22,  name: "Celadon Store" },
            _3f_stairs_w:       {x: 252,  y: 339, name: "Celadon Store" },
            _3f_stairs_e:       {x: 394,  y: 290, name: "Celadon Store" },
            _5f_stairs_w:       {x: 481,  y: 340, name: "Celadon Store" },
            _5f_stairs_e:       {x: 630,  y: 290, name: "Celadon Store" },
        },
        fuchsia: {
            r18_gate:           {x: 88,   y: 299, name: "R18 (Fuchsia)"       },
            mart:               {x: 302,  y: 219, name: "Fuchsia City"        },
            safari:             {x: 523,  y: 61,  name: "Fuchsia City"        },
            c:                  {x: 587,  y: 240, name: "Fuchsia City"        },
            gym:                {x: 276,  y: 467, name: "Fuchsia City"        },
            sw1:                {x: 369,  y: 501, name: "Fuchsia City"        },
            sw2:                {x: 452,  y: 457, name: "Fuchsia City"        },
            center:             {x: 535,  y: 503, name: "Fuchsia City"        },
            se1:                {x: 670,  y: 468, name: "Fuchsia City"        },
            se2:                {x: 759,  y: 502, name: "Fuchsia City"        },
            r15_left:           {x: 859,  y: 303, name: "R15 (Fuchsia)"       },
        },
        gates: {
            r11_w:              {x: 42,   y: 74,  name: "Gate (Route 11)"     },
            r11_e:              {x: 188,  y: 70,  name: "Gate (Route 11)"     },
            r11_stairs:         {x: 153,  y: 144, name: "Gate (Route 11)"     },
            r12_n:              {x: 310,  y: 37,  name: "Gate (Route 12)"     },
            r12_s:              {x: 311,  y: 181, name: "Gate (Route 12)"     },
            r12_stairs:         {x: 355,  y: 143, name: "Gate (Route 12)"     },
            r15_w:              {x: 435,  y: 75,  name: "Gate (Route 15)"     },
            r15_e:              {x: 584,  y: 75,  name: "Gate (Route 15)"     },
            r15_stairs:         {x: 565,  y: 145, name: "Gate (Route 15)"     },
            r16_w:              {x: 42,   y: 293, name: "Gate (Route 16)"     },
            r16_e:              {x: 187,  y: 290, name: "Gate (Route 16)"     },
            r16_stairs:         {x: 153,  y: 357, name: "Gate (Route 16)"     },
            r18_w:              {x: 247,  y: 314, name: "Gate (Route 18)"     },
            r18_e:              {x: 403,  y: 307, name: "Gate (Route 18)"     },
            r18_stairs:         {x: 376,  y: 371, name: "Gate (Route 18)"     },
        },
        indigo: {
            stairs:             {x: 65 ,  y: 630                                                     },
            e4:                 {x: 86 ,  y: 473                                                     },
            entrance:           {x: 198,  y: 675                                                     },
			lorelei_n:			{x: 104,  y: 18 , corridor: "lorelei_s", name: "E4 Member (Lorelei)" },
			lorelei_s:			{x: 104,  y: 186, corridor: "lorelei_n", name: "E4 Member (Lorelei)" },
			bruno_n:			{x: 324,  y: 18 , corridor: "bruno_s",   name: "E4 Member (Bruno)"   },
			bruno_s:			{x: 324,  y: 186, corridor: "bruno_n",   name: "E4 Member (Bruno)"   },
			agatha_n:			{x: 104,  y: 234, corridor: "agatha_s",  name: "E4 Member (Agatha)"  },
			agatha_s:			{x: 104,  y: 400, corridor: "agatha_n",  name: "E4 Member (Agatha)"  },
			lance_n:			{x: 324,  y: 234, corridor: "lance_s",   name: "E4 Member (Lance)"   },
			lance_s:			{x: 324,  y: 400, corridor: "lance_n",   name: "E4 Member (Lance)"   },
        },
        lavender: {
            r8_gate:            {x: 54,   y: 145, name: "R8 (Lavender)"       },
            r8_underground:     {x: 158,  y: 52,  name: "R8 (Lavender)"       },
            center:             {x: 361,  y: 66,  name: "Lavender Town"       },
            tower:              {x: 553,  y: 75,  name: "Lavender Town"       },
            c:                  {x: 422,  y: 153, name: "Lavender Town"       },
            sw:                 {x: 343,  y: 231, name: "Lavender Town"       },
            s:                  {x: 427,  y: 260, name: "Lavender Town"       },
            mart:               {x: 575,  y: 221, name: "Lavender Town"       },
        },
        mt_moon: {
            ladder_nw:          {x: 89,   y: 89,  name: "Mt. Moon"            },
            ladder_n:           {x: 309,  y: 216, name: "Mt. Moon"            },
            ladder_ne:          {x: 500,  y: 242, name: "Mt. Moon"            },
            entrance:           {x: 296,  y: 589, name: "Mt. Moon"            },
            r4_center:          {x: 358,  y: 58,  name: "Route 4"             },
            r4_entrance_w:      {x: 494,  y: 83,  name: "Route 4"             },
            r4_entrance_e:      {x: 679,  y: 59,  name: "Route 4"             },
        },
        pewter: {
            sw:                 {x: 161,  y: 475 },
            center:             {x: 276,  y: 384 },
            gym:                {x: 245,  y: 231 },
            museum_w:           {x: 280,  y: 89  },
            museum_e:           {x: 408,  y: 50  },
            ne:                 {x: 540,  y: 166 },
            mart:               {x: 445,  y: 275 },
        },
        r10: {
            cave_n:             {x: 133,  y: 112 },
            center:             {x: 232,  y: 155 },
            power_plant:        {x: 119,  y: 348 },
            power_plant_side:   {x: 40,   y: 292 },
            cave_s:             {x: 133,  y: 574 },
        },
        r12: {
            house:              {x: 215,  y: 200, name: "R12 (Route)"         },
            gate_s:             {x: 158,  y: 105, name: "R12 (Route)"         },
            gate_n:             {x: 158,  y: 24,  name: "R12 (Lavender)"      },
            r11_gate:           {x: 38,   y: 217, name: "R12 (Route)"         },
        },
        r2: {
            p_gate_w:           {x: 93,   y: 211,                     name: "R2 (Pewter)"   },
            p_cave:             {x: 272,  y: 162,                     name: "R2 (Pewter)"   },
            p_house:            {x: 264,  y: 336,                     name: "R2 (Pewter)"   },
            p_gate_e:           {x: 307,  y: 654,                     name: "R2 (Pewter)"   },
            v_gate_w:           {x: 491,  y: 293,                     name: "R2 (Viridian)" },
            v_gate_e:           {x: 698,  y: 251,                     name: "R2 (Viridian)" },
            hm_bot:             {x: 582,  y: 146, corridor: "hm_top", name: "R2 (HM Flash)" },
			hm_top:             {x: 582,  y: 47,  corridor: "hm_bot", name: "R2 (HM Flash)" },
        },
        r15: {
			gate:               {x: 126,  y: 92,  name: "Route 15"            },
        },
        rocket_hideout: {
            b1f_stairs_w:       {x: 178,  y: 69,  name: "Rocket Hideout B1F"  },
            b1f_stairs_e:       {x: 297,  y: 23,  name: "Rocket Hideout B1F"  },
            b2f_stairs_nw:      {x: 797,  y: 65,  name: "Rocket Hideout B2F"  },
            b2f_stairs_ne:      {x: 917,  y: 31,  name: "Rocket Hideout B2F"  },
            b2f_stairs_s:       {x: 837,  y: 200, name: "Rocket Hideout B2F"  },
        },
        saffron: {
            gate_w:             {x: 47,   y: 376 },
            gate_n:             {x: 463,  y: 59  },
            gate_e:             {x: 823,  y: 389 },
            gate_s:             {x: 465,  y: 687 },
            center:             {x: 294,  y: 545 },
            se:                 {x: 601,  y: 543 },
            silph:              {x: 443,  y: 414 },
            w:                  {x: 341,  y: 267 },
            mart:               {x: 542,  y: 272 },
            e:                  {x: 675,  y: 267 },
            nw:                 {x: 269,  y: 156 },
            dojo:               {x: 549,  y: 141 },
            gym:                {x: 647,  y: 100 },
        },
        seafoam_islands: {
            _1f_entrance:       {x: 102,  y: 334,                            name: "Seafoam Islands 1F"  },
            _1f_ladder_nw:      {x: 156,  y: 78,                             name: "Seafoam Islands 1F"  },
            _1f_hole_w:         {x: 324,  y: 116,                            name: "Seafoam Islands 1F"  },
            _1f_hole_e:         {x: 475,  y: 160,                            name: "Seafoam Islands 1F"  },
            _1f_ladder_ne:      {x: 498,  y: 42,                             name: "Seafoam Islands 1F"  },
            b1f_ladder_nw:      {x: 135,  y: 421,                            name: "Seafoam Islands B1F" },
            b1f_ladder_w:       {x: 143,  y: 517,                            name: "Seafoam Islands B1F" },
            b1f_ladder_c:       {x: 253,  y: 597,                            name: "Seafoam Islands B1F" },
            b1f_hole_w:         {x: 360,  y: 564,                            name: "Seafoam Islands B1F" },
            b1f_hole_e:         {x: 463,  y: 505, corridor: "b1f_hole_e",    name: "Seafoam Islands B1F" },
            b1f_ladder_ne:      {x: 524,  y: 437, corridor: "b1f_ladder_ne", name: "Seafoam Islands B1F" },
            b2f_ladder_nw:      {x: 676,  y: 50,  corridor: "b2f_ladder_nw", name: "Seafoam Islands B2F" },
            b2f_ladder_sw:      {x: 665,  y: 208,                            name: "Seafoam Islands B2F" },
            b2f_ladder_se:      {x: 978,  y: 252,                            name: "Seafoam Islands B2F" },
            b2f_ladder_c:       {x: 813,  y: 160,                            name: "Seafoam Islands B2F" },
            b2f_hole_w:         {x: 910,  y: 114, corridor: "b2f_hole_w",    name: "Seafoam Islands B2F" },
            b2f_hole_e:         {x: 1020, y: 55,  corridor: "b2f_hole_e",    name: "Seafoam Islands B2F" },
            b2f_ladder_ne:      {x: 1097, y: 20,  corridor: "b2f_ladder_ne", name: "Seafoam Islands B2F" },
            b3f_hole_w:         {x: 703,  y: 561,                            name: "Seafoam Islands B3F" },
            b3f_hole_e:         {x: 797,  y: 605,                            name: "Seafoam Islands B3F" },
            b3f_ladder_w:       {x: 745,  y: 498,                            name: "Seafoam Islands B3F" },
            b3f_ladder_n:       {x: 820,  y: 413,                            name: "Seafoam Islands B3F" },
            b3f_ladder_se:      {x: 1124, y: 527,                            name: "Seafoam Islands B3F" },
            b4f_ladder_w:       {x: 490,  y: 678, corridor: "b4f_ladder_e",  name: "Seafoam Islands B4F" },
            b4f_ladder_e:       {x: 608,  y: 721, corridor: "b4f_ladder_w",  name: "Seafoam Islands B4F" },
            r20_cave_w:         {x: 777,  y: 704,                            name: "R20 (Seafoam)"       },
            r20_cave_e:         {x: 964,  y: 806,                            name: "R20 (Seafoam)"       },
        },
        silph_1: {
            _1f_entrance:       {x: 58,   y: 742, name: "Silph Co. 1F"        },
            _1f_stairs:         {x: 58,   y: 651, name: "Silph Co. 1F"        },
            _2f_nw:             {x: 58,   y: 387, name: "Silph Co. 2F"        },
            _2f_sw:             {x: 102,  y: 567, name: "Silph Co. 2F"        },
            _2f_n:              {x: 220,  y: 389, name: "Silph Co. 2F"        },
            _2f_se:             {x: 456,  y: 568, name: "Silph Co. 2F"        },
            _2f_stairs_w:       {x: 362,  y: 326, name: "Silph Co. 2F"        },
            _2f_stairs_e:       {x: 435,  y: 373, name: "Silph Co. 2F"        },
            _3f_sw:             {x: 66,   y: 266, name: "Silph Co. 3F"        },
            _3f_w:              {x: 56,   y: 182, name: "Silph Co. 3F"        },
            _3f_nw:             {x: 78,   y: 75,  name: "Silph Co. 3F"        },
            _3f_c:              {x: 197,  y: 182, name: "Silph Co. 3F"        },
            _3f_se:             {x: 435,  y: 270, name: "Silph Co. 3F"        },
            _3f_e:              {x: 407,  y: 177, name: "Silph Co. 3F"        },
            _3f_ne:             {x: 455,  y: 90,  name: "Silph Co. 3F"        },
            _3f_stairs_w:       {x: 359,  y: 57,  name: "Silph Co. 3F"        },
            _3f_stairs_e:       {x: 442,  y: 11,  name: "Silph Co. 3F"        },
            _4f_sw:             {x: 552,  y: 736, name: "Silph Co. 4F"        },
            _4f_nw:             {x: 673,  y: 581, name: "Silph Co. 4F"        },
            _4f_ne:             {x: 759,  y: 528, name: "Silph Co. 4F"        },
            _4f_c:              {x: 763,  y: 647, name: "Silph Co. 4F"        },
            _4f_stairs_w:       {x: 871,  y: 476, name: "Silph Co. 4F"        },
            _4f_stairs_e:       {x: 947,  y: 526, name: "Silph Co. 4F"        },
            _5f_sw:             {x: 541,  y: 432, name: "Silph Co. 5F"        },
            _5f_s:              {x: 654,  y: 401, name: "Silph Co. 5F"        },
            _5f_n:              {x: 716,  y: 236, name: "Silph Co. 5F"        },
            _5f_stairs_w:       {x: 872,  y: 195, name: "Silph Co. 5F"        },
            _5f_stairs_e:       {x: 946,  y: 157, name: "Silph Co. 5F"        },
            _5f_ne:             {x: 946,  y: 234, name: "Silph Co. 5F"        },
        },
        silph_2: {
            _6f_w:              {x: 44,   y: 722,                          name: "Silph Co. 6F"      },
            _6f_stairs_w:       {x: 215,  y: 652,                          name: "Silph Co. 6F"      },
            _6f_stairs_e:       {x: 423,  y: 665,                          name: "Silph Co. 6F"      },
            _6f_e:              {x: 478,  y: 739,                          name: "Silph Co. 6F"      },
            _7f_stairs_w:       {x: 288,  y: 391,                          name: "Silph Co. 7F"      },
            _7f_stairs_e:       {x: 454,  y: 336,                          name: "Silph Co. 7F"      },
            _7f_s:              {x: 411,  y: 579,                          name: "Silph Co. 7F"      },
            _7f_rival_n:        {x: 88,   y: 365, corridor: "_7f_rival_s", name: "Silph Co. (Rival)" },
			_7f_rival_s:        {x: 88,   y: 481, corridor: "_7f_rival_n", name: "Silph Co. (Rival)" },
            _8f_stairs_w:       {x: 247,  y: 24,                           name: "Silph Co. 8F"      },
            _8f_stairs_e:       {x: 443,  y: 64,                           name: "Silph Co. 8F"      },
            _8f_w:              {x: 34,   y: 175,                          name: "Silph Co. 8F"      },
            _8f_sw:             {x: 55,   y: 262,                          name: "Silph Co. 8F"      },
            _8f_c:              {x: 193,  y: 143,                          name: "Silph Co. 8F"      },
            _8f_n:              {x: 167,  y: 79,                           name: "Silph Co. 8F"      },
            _9f_nw:             {x: 582,  y: 481,                          name: "Silph Co. 9F"      },
            _9f_stairs_w:       {x: 671,  y: 510,                          name: "Silph Co. 9F"      },
            _9f_stairs_e:       {x: 752,  y: 436,                          name: "Silph Co. 9F"      },
            _9f_s:              {x: 795,  y: 707,                          name: "Silph Co. 9F"      },
            _10f_stairs_w:      {x: 582,  y: 126,                          name: "Silph Co. 10F"     },
            _10f_stairs_e:      {x: 660,  y: 178,                          name: "Silph Co. 10F"     },
            _10f_e:             {x: 757,  y: 246,                          name: "Silph Co. 10F"     },
            _10f_sw:            {x: 666,  y: 320,                          name: "Silph Co. 10F"     },
            _10f_se:            {x: 757,  y: 398,                          name: "Silph Co. 10F"     },
            _11f_stairs:        {x: 581,  y: 29,                           name: "Silph Co. 11F"     },
        },
        ss_anne: {
            _1f_entrance:       {x: 315,  y: 39,  name: "SS Anne 1F"          },
            _1f_stairs_w:       {x: 30,   y: 107, name: "SS Anne 1F"          },
            _1f_room_1:         {x: 40,   y: 200, name: "SS Anne 1F"          },
            _1f_room_2:         {x: 110,  y: 150, name: "SS Anne 1F"          },
            _1f_room_3:         {x: 170,  y: 200, name: "SS Anne 1F"          },
            _1f_room_4:         {x: 230,  y: 150, name: "SS Anne 1F"          },
            _1f_room_5:         {x: 290,  y: 200, name: "SS Anne 1F"          },
            _1f_room_6:         {x: 350,  y: 150, name: "SS Anne 1F"          },
            _1f_room_7:         {x: 420,  y: 200, name: "SS Anne 1F"          },
            _1f_door_s:         {x: 38,   y: 288, name: "SS Anne 1F"          },
            _1f_stairs_e:       {x: 448,  y: 253, name: "SS Anne 1F"          },
            _2f_stairs_nw:      {x: 69,   y: 435, name: "SS Anne 2F"          },
            _2f_stairs_sw:      {x: 33,   y: 582, name: "SS Anne 2F"          },
            _2f_room_1:         {x: 100,  y: 490, name: "SS Anne 2F"          },
            _2f_room_2:         {x: 160,  y: 540, name: "SS Anne 2F"          },
            _2f_room_3:         {x: 235,  y: 490, name: "SS Anne 2F"          },
            _2f_room_4:         {x: 295,  y: 540, name: "SS Anne 2F"          },
            _2f_room_5:         {x: 370,  y: 490, name: "SS Anne 2F"          },
            _2f_room_6:         {x: 430,  y: 540, name: "SS Anne 2F"          },
            _2f_stairs_ne:      {x: 497,  y: 360, name: "SS Anne 2F"          },
            b1f_room_1:         {x: 25,   y: 680, name: "SS Anne B1F"         },
            b1f_room_2:         {x: 100,  y: 635, name: "SS Anne B1F"         },
            b1f_room_3:         {x: 160,  y: 680, name: "SS Anne B1F"         },
            b1f_room_4:         {x: 235,  y: 635, name: "SS Anne B1F"         },
            b1f_room_5:         {x: 295,  y: 680, name: "SS Anne B1F"         },
            b1f_stairs:         {x: 323,  y: 715, name: "SS Anne B1F"         },
        },
        vermilion: {
            nw:                 {x: 154,  y: 67,  name: "Vermilion City"      },
            center:             {x: 262,  y: 121, name: "Vermilion City"      },
            fan_club:           {x: 203,  y: 239, name: "Vermilion City"      },
            c:                  {x: 310,  y: 282, name: "Vermilion City"      },
            mart:               {x: 459,  y: 251, name: "Vermilion City"      },
            gym:                {x: 236,  y: 372, name: "Vermilion City (Gym)"},
            se:                 {x: 461,  y: 358, name: "Vermilion City"      },
            harbor:             {x: 381,  y: 568, name: "Vermilion City"      },
            r6_gate:            {x: 657,  y: 54,  name: "R6 (Vermilion)"      },
            r6_underground:     {x: 771,  y: 190, name: "R6 (Vermilion)"      },
            r11_cave:           {x: 655,  y: 405, name: "R11 (Vermilion)"     },
            r11_gate:           {x: 986,  y: 447, name: "R11 (Vermilion)"     },
        },
        victory_road: {
            _2f_ladder_nw:      {x: 67,   y: 55,  name: "Victory Road 2F"     },
            _2f_ladder_w:       {x: 41,   y: 145, name: "Victory Road 2F"     },
            _2f_ladder_e:       {x: 540,  y: 158, name: "Victory Road 2F"     },
            _2f_ladder_se:      {x: 595,  y: 274, name: "Victory Road 2F"     },
            _3f_ladder_nw:      {x: 96,   y: 419, name: "Victory Road 3F"     },
            _3f_ladder_n:       {x: 535,  y: 505, name: "Victory Road 3F"     },
            _3f_ladder_e:       {x: 614,  y: 545, name: "Victory Road 3F"     },
            _3f_ladder_se:      {x: 645,  y: 632, name: "Victory Road 3F"     },
            _3f_hole:           {x: 532,  y: 680, name: "Victory Road 3F"     },
        },
        viridian: {
            n:                  {x: 418,  y: 150, name: "Viridian City"       },
            gym:                {x: 586,  y: 126, name: "Viridian City"       },
            s:                  {x: 416,  y: 263, name: "Viridian City"       },
            mart:               {x: 587,  y: 278, name: "Viridian City"       },
            center:             {x: 421,  y: 388, name: "Viridian City"       },
            r22:                {x: 135,  y: 50,  name: "R22 (Viridian)"      },
        },
        rocktunnel1: {
            f1_left:        {x: 73,  y: 64,  corridor: "f1_right",       name: "Rock Tunnel (F1)"    },
			f1_right:       {x: 329, y: 240, corridor: "f1_left",        name: "Rock Tunnel (F1)"    },
			entrance_left:  {x: 280, y: 62,  corridor: "entrance_right", name: "Rock Tunnel (Entry)" },
			entrance_right: {x: 729, y: 63,  corridor: "entrance_left",  name: "Rock Tunnel (Entry)" },
			exit_door:      {x: 729, y: 312, corridor: "exit_stairs",    name: "Rock Tunnel (Exit)"  },
			exit_stairs:    {x: 297, y: 583, corridor: "exit_door",      name: "Rock Tunnel (Exit)"  },
        },
        rocktunnel2: {
            left_left:  {x: 42,  y: 85,  corridor: "left_right", name: "Rock Tunnel (BF1 L)" },
			left_right: {x: 440, y: 229, corridor: "left_left",  name: "Rock Tunnel (BF1 L)" },
			right_top:  {x: 536, y: 85,  corridor: "right_bot",  name: "Rock Tunnel (BF1 R)" },
			right_bot:  {x: 616, y: 485, corridor: "right_top",  name: "Rock Tunnel (BF1 R)" },
        },
        pokemontower: {
            f2_down: {x: 270, y: 734, corridor: "f2_up",   name: "Pokémon Tower (2F)" },
			f2_up:   {x: 14,  y: 734, corridor: "f2_down", name: "Pokémon Tower (2F)" },
			f3_down: {x: 344, y: 800, corridor: "f3_up",   name: "Pokémon Tower (3F)" },
			f3_up:   {x: 590, y: 800, corridor: "f3_down", name: "Pokémon Tower (3F)" },
			f4_down: {x: 270, y: 431, corridor: "f4_up",   name: "Pokémon Tower (4F)" },
			f4_up:   {x: 14,  y: 431, corridor: "f4_down", name: "Pokémon Tower (4F)" },
			f5_down: {x: 344, y: 500, corridor: "f5_up",   name: "Pokémon Tower (5F)" },
			f5_up:   {x: 590, y: 499, corridor: "f5_down", name: "Pokémon Tower (5F)" },
			f6_down: {x: 441, y: 134, corridor: "f6_up",   name: "Pokémon Tower (6F)" },
			f6_up:   {x: 281, y: 218, corridor: "f6_down", name: "Pokémon Tower (6F)" },
        },
        cyclingroad: {
            top: {x: 147, y: 60,  corridor: "bot" },
			bot: {x: 155, y: 215, corridor: "top" },
        },

        /*
        *************
        *** JOHTO ***     
        *************
        */

        // Cities
        newbark: {
            elmslab:    {x: 135, y: 58,  name: "New Bark (Elm's Lab)"     },
            playerhouse:{x: 262, y: 93,                                   },
            left:       {x: 55,  y: 225,                                  },
            elmhouse:   {x: 247, y: 239,                                  },
        },
        cherrygrove_r29: {
            r29_gate: {x: 440, y: 24, name: "R29 (Cherrygrove)" },
            mart:     {x: 214, y: 23                            },
            center:   {x: 321, y: 15                            },
            house1:   {x: 63 , y: 122                           },
            house2:   {x: 224, y: 138                           },
            house3:   {x: 351, y: 185                           },
        },
        violet: {
            sprout:        {x: 468, y: 93     },
            leftmart:      {x: 53, y: 260     },
            mart:          {x: 212, y: 280    },
            gym:           {x: 373, y: 271    },
            school:        {x: 581, y: 273    },
            center:        {x: 597, y: 417    },
            trade:         {x: 404, y: 485    },
            gate:          {x: 721, y: 373    }
        },
        azalea_well: {
            kurt:      {x: 168, y: 55                               },
            center:    {x: 327, y: 120                              },
            mart:      {x: 424, y: 43                               },
            well:      {x: 583, y: 99                               },
            gym:       {x: 215, y: 243                              },
            charcoal:  {x: 424, y: 216                              },
            gate:      {x: 37,  y: 121                              },
            unioncave: {x: 568, y: 249,   name: "Route 33 (Azalea)" }
        },
        goldenrod: {
            gate:        {x: 384, y: 271 },
            tunneltop:   {x: 168, y: 295 },
            leftgym:     {x: 313, y: 306 },
            gym:         {x: 472, y: 306 },
            flower:      {x: 552, y: 279 },
            rightgym:    {x: 616, y: 343 },
            radio:       {x: 103, y: 450 },
            station:     {x: 232, y: 429 },
            gamecorner:  {x: 295, y: 567 },
            rightmart:	 {x: 583, y: 549 },
            bill:        {x: 71,  y: 633 },
            tunnelbot:   {x: 185, y: 708 },
            center:      {x: 297, y: 675 },
            mart:        {x: 473, y: 673 },
            bike:        {x: 550, y: 711 },
            radf3right:  {x: 280, y: 18,  name: "Goldenrod (Radio)" },
            radf3cent:   {x: 158, y: 18,  name: "Goldenrod (Radio)" },
            radf3left:   {x: 40,  y: 18,  name: "Goldenrod (Radio)" },
            pcenterance: {x: 477, y: 186, name: "Goldenrod (Center)" },
            pcstairs   : {x: 373, y: 141, name: "Goldenrod (Center)" },
            pcback     : {x: 400, y: 18,  name: "Goldenrod (Center)" },
        },
        ecruteak: {
            burned:    {x: 120, y: 164                           },
            tin:       {x: 407, y: 283                           },
            gateleft:  {x: 48,  y: 439                           },
            topgym:    {x: 148, y: 506                           },
            kimono:    {x: 487, y: 508                           },
            mart:      {x: 616, y: 510                           },
            gym:       {x: 166, y: 606                           },
            rightgym:  {x: 297, y: 616                           },
            center:    {x: 487, y: 612                           },
            gateright: {x: 718, y: 563                           },
            tintower:  {x: 373, y: 43, corridor: "Tin Tower"     },
            gatehouse: {x: 633, y: 89, corridor: "Gate House"    },
        },
        olivine_r40: {
            gym:        {x: 484, y: 218 , name: "Olivine City"       },
            trade:      {x: 757, y: 245 , name: "Olivine City"       },
            righttrade: {x: 838, y: 245 , name: "Olivine City"       },
            leftmart:   {x: 536, y: 344 , name: "Olivine City"       },
            mart:       {x: 680, y: 344 , name: "Olivine City"       },
            center:     {x: 568, y: 449 , name: "Olivine City"       },
            bar:        {x: 421, y: 451 , name: "Olivine City"       },
            lighthouse: {x: 884, y: 541 , name: "Olivine City"       },
            dock:       {x: 695, y: 635 , name: "Olivine City"       },
            battle:     {x: 906, y: 42  , name: "Olivine City"       },
            gate:       {x: 156, y: 270 , name: "Route 38 (Olivine)" },
            farm1:      {x: 152, y: 36  , name: "Route 39 (Olivine)" },
            farm2:      {x: 71, y:  37  , name: "Route 39 (Olivine)" },
    
        },
        cianwood: {
            house1: {x: 45,  y: 17  },
            house2: {x: 127, y: 304 },
            house3: {x: 237, y: 434 },
            house4: {x: 286, y: 529 },
            gym:    {x: 110, y: 549 },
            center: {x: 414, y: 555 },
            house5: {x: 237, y: 641 },
        },
        mahogany_r44: {
            gate:      {x: 164, y: 14                              },
            mart:	   {x: 220, y: 129                             },
            rightmart: {x: 316, y: 131                             },
            gym:       {x: 107, y: 249                             },
            center:    {x: 283, y: 254                             },
            icepath:   {x: 530, y: 115, name: "Route44 (Mahogany)" },
        },
        blackthorn: {
            den:         {x: 412, y: 26  },
            gym:         {x: 323, y: 202 },
            icepath:     {x: 658, y: 231 },
            botgym:      {x: 195, y: 418 },
            leftmart:    {x: 132, y: 627 },
            mart:        {x: 259, y: 576 },
            center:      {x: 371, y: 568 },
            rightcenter: {x: 517, y: 464 }
        },
        indigo_e4: {
            center_left:     {x: 19,  y: 561,                        name: "Indigo Plateau"    },
            center_entrance: {x: 119, y: 607,                        name: "Indigo Plateau"    },
            center_top:      {x: 394, y: 474,                        name: "Indigo Plateau"    },
            will_top:        {x: 111, y: 43,  corridor: "will_bot",  name: "E4 Member (Will)"  },
            will_bot:        {x: 111, y: 193, corridor: "will_top",  name: "E4 Member (Will)"  },
            koga_top:        {x: 335, y: 42,  corridor: "koga_bot",  name: "E4 Member (Koga)"  },
            koga_bot:        {x: 335, y: 194, corridor: "koga_top",  name: "E4 Member (Koga)"  },
            bruno_top:       {x: 111, y: 258, corridor: "bruno_bot", name: "E4 Member (Bruno)" },
            bruno_bot:       {x: 111, y: 411, corridor: "bruno_top", name: "E4 Member (Bruno)" },
            karen_top:       {x: 335, y: 257, corridor: "karen_bot", name: "E4 Member (Karen)" },
            karen_bot:       {x: 335, y: 410, corridor: "karen_top", name: "E4 Member (Karen)" },
        },
    
        // Routes
        r45_r46: {
            gate:        {x: 122, y: 396, name: "Route 46 (Gate)" },
            botdarkcave: {x: 55,  y: 41,  name: "Route 46 (Cave)" },
            topdarkcave: {x: 234, y: 231, name: "Route 45"        },
        },
        r30_r31: {
            gate:     {x: 27,  y: 61,  name: "Route 31" },
            darkcave: {x: 472, y: 49,  name: "Route 31" },
            berry:    {x: 81,  y: 362, name: "Route 30" },
            lab:      {x: 451, y: 367, name: "Route 30" },
        },
        alphruins_r32: {
            topgate:    {x: 193, y: 29,                          name: "Ruins of Alph (Top)" },
            puzzle:     {x: 312, y: 109,                         name: "Ruins of Alph (Top)" },
            house:      {x: 411, y: 192,                         name: "Ruins of Alph (Top)" },
            unown:      {x: 233, y: 234,                         name: "Ruins of Alph (Top)" },
            leftgate:   {x: 334, y: 359,                         name: "Ruins of Alph (Top)" },
            left:       {x: 442, y: 449,                         name: "Ruins of Alph (Bot)" },
            top:        {x: 72,  y: 576,                         name: "Ruins of Alph (Bot)" },
            right:      {x: 136, y: 517,                         name: "Ruins of Alph (Bot)" },
            rightgate:  {x: 342, y: 606,                         name: "Route 32 (Violet)"   },
            center:     {x: 682, y: 387,                         name: "Route 32"            },
            union:      {x: 585, y: 533,                         name: "Route 32"            },
            hoho:       {x: 73,  y: 307, corridor: "hoho",       name: "Ruins of Alph"       },
            alph_union: {x: 136, y: 340, corridor: "alph_union", name: "Ruins of Alph"       },
        },
        r34_ilex: {
            r34_gate:    {x: 260, y: 772,                        name: "Route 34"        },
            r34_daycare: {x: 229, y: 274,                        name: "Route 34"        },
            ilext_top:   {x: 530, y: 75 , corridor: "ilext_bot", name: "Ilex Forest"     },
            ilext_bot:   {x: 572, y: 855, corridor: "ilext_top", name: "Ilex Forest"     }
        },
        r35_r36: {
            botgate:    {x: 208, y: 666,                         name: "Route 35"          },
            botpark:    {x: 113, y: 398,                         name: "Route 35"          },
            toppark:    {x: 79,  y: 168,                         name: "Route 36"          },
            topgate:    {x: 273, y: 326,                         name: "Route 36 (Violet)" }
        },
        r41: {
            topleft:  {x: 760, y: 237, name: "Route 41 (NW)" },
            topright: {x: 246, y: 202, name: "Route 41 (NE)" },
            botleft:  {x: 232, y: 642, name: "Route 41 (SW)" },
            botright: {x: 743, y: 732, name: "Route 41 (SE)" },
        },
        ragelake_r43: {
            cut:      {x: 399, y: 44 ,                      name: "Lake of Rage"       },
            lake:     {x: 467, y: 282,                      name: "Lake of Rage"       },
            entrance: {x: 110, y: 381,                      name: "Route 43 (Lake)"    },
            gatebot:  {x: 272, y: 99 ,                      name: "Route 43 (Lake)"    },
            gatetop:  {x: 271, y: 23 ,                      name: "Route 43 (Lake)"    }
        },
        r26_r27: {
            left:        {x: 85,  y: 279,                          name: "Route 27" },
            right:       {x: 309, y: 279,                          name: "Route 27" },
            house1:      {x: 228, y: 313,                          name: "Route 27" },
            house2:      {x: 464, y: 346,                          name: "Route 26" },
            house3:      {x: 473, y: 239,                          name: "Route 26" },
            reception:   {x: 405, y: 51,                           name: "Route 26" }
        },
    
        /*
        r28: {
            gate:   {x: 456, y: 375 },
            house:  {x: 70,  y: 405 },
            center: {x: 325, y: 175 },
            silver: {x: 244, y: 43  },
        },
        */
    
        // Important locations
        darkcave: {
            r31_left:  {x: 188, y: 267                                                      },
            r31_top:   {x: 448, y: 45                                                       },
            r31_right: {x: 798, y: 590                                                      },
            r45_left:  {x: 62,  y: 738, corridor: "r45_right", name: "Dark Cave (Corridor)" },
            r45_right: {x: 605, y: 352, corridor: "r45_left",  name: "Dark Cave (Corridor)" },
        },
        puzzlechambers: {
            kabuto_top:     {x: 87, y: 10,  name: "Puzzle (Kabuto)"     },
            kabuto_cent:    {x: 87, y: 60,  name: "Puzzle (Kabuto)"     },
            kabuto_bot:     {x: 87, y: 165, name: "Puzzle (Kabuto)"     },
            aerodactyl_top: {x: 87, y: 197, name: "Puzzle (Aerodactyl)" },
            aerodactyl_cent:{x: 87, y: 250, name: "Puzzle (Aerodactyl)" },
            aerodactyl_bot: {x: 86, y: 354, name: "Puzzle (Aerodactyl)" },
        },
        unioncave: {
            f1_top:   {x: 327, y: 91,  name: "Union Cave (1F)"  },
            f1_mid:   {x: 78,  y: 131, name: "Union Cave (1F)"  },
            f1_right: {x: 344, y: 404, name: "Union Cave (1F)"  },
            f1_left:  {x: 39,  y: 380, name: "Union Cave (1F)"  },
            bf1_top:  {x: 449, y: 72,  name: "Union Cave (B1F)" },
            bf1_mid:  {x: 433, y: 200, name: "Union Cave (B1F)" },
            bf1_bot:  {x: 495, y: 275, name: "Union Cave (B1F)" },
        },
        goldenrodstore: {
            f1_door: {x: 103, y: 221, name: "Goldenrod Store" },
            f1_up:   {x: 141, y: 65,  name: "Goldenrod Store" },
            f2_up:   {x: 232, y: 65,  name: "Goldenrod Store" },
            f2_down: {x: 382, y: 65,  name: "Goldenrod Store" },
            f3_up:   {x: 601, y: 65,  name: "Goldenrod Store" },
            f3_down: {x: 468, y: 65,  name: "Goldenrod Store" },
            f4_up:   {x: 37,  y: 319, name: "Goldenrod Store" },
            f4_down: {x: 166, y: 319, name: "Goldenrod Store" },
            f5_up:   {x: 390, y: 319, name: "Goldenrod Store" },
            f5_down: {x: 253, y: 319, name: "Goldenrod Store" },
            f6_up:   {x: 471, y: 319, name: "Goldenrod Store" },
            f6_down: {x: 602, y: 320, name: "Goldenrod Store" },
            b1f:     {x: 384, y: 523, name: "Goldenrod Store" },
        },
        underground: {
            top:               {x: 40,  y: 41     },
            basement:          {x: 392, y: 115    },
            bot:               {x: 40,  y: 274    }
        },
        mtmortar_r42: {
            r42_gate:                  {x: 45, y: 757 ,                                name: "Route 42 (Left)"     },
            r42_cave1:                 {x: 230, y: 716,                                name: "Route 42 (Left)"     },
            r42_cave2:                 {x: 464, y: 810,                                name: "Route 42 (Middle)"   },
            r42_cave3:                 {x: 708, y: 731,                                name: "Route42 (Mahogany)"  },
            mortarwater_leftouter:     {x: 71,  y: 617, corridor: "leftouter"                                      },
            mortarwater_midouter:      {x: 419, y: 622                                                             },
            mortarwater_righttouter:   {x: 721, y: 617, corridor: "righttouter"                                    },
            mortarwater_botstairs:     {x: 377, y: 517                                                             },
            mortarwater_leftinnerdoor: {x: 203, y: 359, corridor: "leftinnerdoor"                                  },
            mortarwater_rigthinnerdoor:{x: 619, y: 358, corridor: "rigthinnerdoor"                                 },
            mortarwater_topleftstairs: {x: 122, y: 177, corridor: "topleftstairs"                                  },
            mortarwater_toprightstairs:{x: 712, y: 159, corridor: "toprightstairs"                                 },
            mortarwater_topinnerdoor:  {x: 379, y: 97                                                              },
        },
        mtmortarback: {
            topstairs:   {x: 160, y: 115, name: "Mortar Back (Top)" },
            midstairs:   {x: 68,  y: 321, name: "Mortar Back (Top)" },
            leftstairs:  {x: 98,  y: 723, name: "Mortar Back (Bot)" },
            leftdoor:    {x: 209, y: 934, name: "Mortar Back (Bot)" },
            rightdoor:   {x: 513, y: 934, name: "Mortar Back (Bot)" },
            rightstairs: {x: 609, y: 761, name: "Mortar Back (Bot)" },
        },
        mtmortarf2: {
            door:   {x: 65,  y: 56,  corridor: "stairs" },
            stairs: {x: 351, y: 630, corridor: "door"   },
        },
        mtmortarb1f: {
            top:    {x: 66,  y: 34,  corridor: "bottom" },
            bottom: {x: 369, y: 570, corridor: "top"    },
        },
        lighthouse: {
            f1_entrance:  {x: 278, y: 1214, corridor: "f1_entrance", name: "Lighthouse (F1)"  },
            f1_stairs:    {x: 128, y: 1058, corridor: "f1_stairs",   name: "Lighthouse (F1)"  },
            f2_entrance:  {x: 539, y: 1068,                          name: "Lighthouse (F2)"  },
            f2_hole:      {x: 903, y: 1202,                          name: "Lighthouse (F2)"  },
            f2_stairs:    {x: 566, y: 915,                           name: "Lighthouse (F2)"  },
            f3_entrance:  {x: 67,  y: 442,                           name: "Lighthouse (F3)"  },
            f3_hole:      {x: 418, y: 717,                           name: "Lighthouse (F3)"  },
            f3_stairs:    {x: 387, y: 460,                           name: "Lighthouse (F3)"  },
            f4_entrance:  {x: 853, y: 501,                           name: "Lighthouse (F4)"  },
            f4_hole1:     {x: 717, y: 463,                           name: "Lighthouse (F4)"  },
            f4_stairstop: {x: 702, y: 526,                           name: "Lighthouse (F4)"  },
            f4_stairsbot: {x: 701, y: 577,                           name: "Lighthouse (F4)"  },
            f4_stairsmid: {x: 588, y: 544,                           name: "Lighthouse (F4)"  },
            f4_hole2:     {x: 900, y: 650,                           name: "Lighthouse (F4)"  },
            f5_hole:      {x: 415, y: 177,                           name: "Lighthouse (F5)"  },
            f5_stairs:    {x: 66, y: 76  ,                           name: "Lighthouse (F5)"  },
            f5_intop:     {x: 210, y: 111, corridor: "f5_inbot",     name: "Lighthouse (F5)"  },
            f5_inbot:     {x: 292, y: 319, corridor: "f5_intop",     name: "Lighthouse (F5)"  },
            top_stairs:   {x: 678, y: 317, corridor: "top_hole",     name: "Lighthouse (Top)" },
            top_hole:     {x: 902, y: 153, corridor: "top_stairs",   name: "Lighthouse (Top)" },
        },
        whirlislands: {
            waterfall_top:           {x: 275, y: 80,                          name: "Whirl (Waterfall)"     },
            waterfall_cave:          {x: 195, y: 458,                         name: "Whirl (Waterfall)"     },
            waterfall_bot:           {x: 340, y: 655,                         name: "Whirl (Waterfall)"     },
            waterfall_end:           {x: 164, y: 148, corridor: "fall_end",   name: "Whirl (Waterfall)"     },
            lake_left:               {x: 71,  y: 722,                         name: "Whirl (Lake Left)"     },
            lake_right:              {x: 374, y: 731,                         name: "Whirl (Lake Right)"    },
            lake_entrance:           {x: 118, y: 841,                         name: "Whirl (Lake Left)"     },
            surf_left:               {x: 85,  y: 915, corridor: "surf_right", name: "Whirl (Surf Corridor)" },
            surf_right:              {x: 392, y: 947, corridor: "surf_left",  name: "Whirl (Surf Corridor)" },
            ledges_entrance:         {x: 524, y: 974,                         name: "Whirl (Ledges)"        },
            ledges_bot:              {x: 732, y: 854,                         name: "Whirl (Ledges 🚫)"     },
            ledges_top:              {x: 796, y: 766,                         name: "Whirl (Ledges 🚫)"     },
            main_topright:           {x: 1157,y: 23 , corridor: "topright",   name: "Whirl (Hub)"           },
            main_topleft:            {x: 581, y: 60 ,                         name: "Whirl (Hub)"           },
            main_mid:                {x: 1027,y: 138,                         name: "Whirl (Hub)"           },
            main_cave:               {x: 774, y: 376,                         name: "Whirl (Hub)"           },
            bellow_cave:             {x: 708, y: 507,                         name: "Whirl (Hub)"           },
            right_of_cave:           {x: 931, y: 376, corridor: "rightofcave",name: "Whirl (Hub)"           },
            main_cave:               {x: 774, y: 376,                         name: "Whirl (Hub)"           },
            main_botleft:            {x: 614, y: 622,                         name: "Whirl (Hub)"           },
            main_botmid:             {x: 889, y: 650,                         name: "Whirl (Hub)"           },
            main_botright:           {x: 1069,y: 607,                         name: "Whirl (Hub)"           },
        },
        icepath1: {
            hub_stairsleft:   {x: 496, y: 823,                              name: "Ice Path (Holes)"      },
            hub_holebotleft:  {x: 526, y: 722,                              name: "Ice Path (Holes)"      },
            hub_holebotright: {x: 639, y: 735,                              name: "Ice Path (Holes)"      },
            hub_holetopleft:  {x: 510, y: 639,                              name: "Ice Path (Holes)"      },
            hub_holetopright: {x: 623, y: 556,                              name: "Ice Path (Holes)"      },
            hub_stairsup:     {x: 735, y: 571,                              name: "Ice Path (Holes)"      },
            entrance_door:    {x: 67, y: 358 , corridor: "entrance_stairs", name: "Ice Path (Waterfall)"  },
            entrance_stairs:  {x: 675, y: 64 , corridor: "entrance_door",   name: "Ice Path (Waterfall)"  },
            exit_stairs:      {x: 692, y: 197, corridor: "exit_door",       name: "Ice Path (Exit)"       },
            exit_door:        {x: 630, y: 496, corridor: "exit_stairs",     name: "Ice Path (Exit)"       },
            b2f_stairsup:     {x: 340, y: 598, corridor: "b2f_stairsup",    name: "Ice Path (B2F)"        },
            b2f_stairsdown:   {x: 180, y: 725, corridor: "b2f_stairsdown",  name: "Ice Path (B2F)"        }
        },
        victoryroad_reception: {
            roadf2_left:     {x: 20,  y: 478,                         name: "Victory Road (2F)" },
            roadf2_mid:      {x: 498, y: 467,                         name: "Victory Road (2F)" },
            roadf2_right:    {x: 610, y: 464,                         name: "Victory Road (2F)" },
            roadf3_hole:     {x: 121, y: 118,                         name: "Victory Road (3F)" },
            roadf3_mid:      {x: 362, y: 211,                         name: "Victory Road (3F)" },
            roadf3_bot:      {x: 552, y: 274,                         name: "Victory Road (3F)" },
            roadf3_top:      {x: 372, y: 13,                          name: "Victory Road (3F)" },
        },

        /*
        *************
        *** HOENN ***     
        *************
        */
       
        // Cities
        littleroot: {
            left:   {x: 88,  y: 108 },
            right:  {x: 230, y: 107 },
            lab:    {x: 117, y: 238},
        },
        oldale: {
            left:   {x: 88,  y: 99 },
            mart:   {x: 232, y: 82 },
            center: {x: 103, y: 243},
            right:  {x: 248, y: 242},
        },
        petalburg: {
            wally:  {x: 120, y: 64 },
            gym:    {x: 248, y: 111},
            center: {x: 328, y: 242},
            mart:   {x: 408, y: 180},
            left:   {x: 168, y: 288},
            right:  {x: 328, y: 370},
        },
        rustboro: {
            corp:      {x: 192, y: 107},
            gym:       {x: 440, y: 165},
            rightgym:  {x: 535, y: 200},
            upcut:     {x: 213, y: 345},
            cut:       {x: 150, y: 520},
            upschool:  {x: 487, y: 312},
            school:    {x: 440, y: 410},
            center:    {x: 263, y: 472},
            leftmart:  {x: 86,  y: 680},
            mart:      {x: 262, y: 585},
            rightmart: {x: 422, y: 602},
        },
        dewford: {
            top:    {x: 56,  y: 31 },
            middle: {x: 135, y: 110},
            bottom: {x: 278, y: 208},
            center: {x: 38,  y: 144},
            gym:    {x: 135, y: 248},
        },
        slateport_r109: {
            contest:   {x: 168, y: 40                                                     },
            rater:     {x: 85,  y: 148                                                    },
            club:      {x: 51,  y: 264                                                    },
            center:    {x: 310, y: 153                                                    },
            mart:      {x: 225, y: 267                                                    },
            museum:    {x: 494, y: 268,                        name: "Slateport (Museum)" },
            shipyard:  {x: 424, y: 449                                                    },
            house:     {x: 342, y: 555                                                    },
            beach:     {x: 90,  y: 555                                                    },
            port:      {x: 455, y: 43                                                     },
            stern_top: {x: 534, y: 399, corridor: "stern_bot", name: "Stern's Shipyard"   },
			stern_bot: {x: 527, y: 624, corridor: "stern_top", name: "Stern's Shipyard"   },
        },
        mauville_r117: {
            gym:     {x: 135, y: 50 },
			center:  {x: 369, y: 50 },
			bicycle: {x: 569, y: 50 },
			casino:  {x: 135, y: 179},
			left:    {x: 310, y: 190},
			mart:    {x: 378, y: 260},
			right:   {x: 526, y: 190},
			daycare: {x: 115, y: 374},
        },
        verdanturf: {
            contest: {x: 55,  y: 89 },
            tunnel:  {x: 135, y: 9  },
            mart:    {x: 208, y: 34 },
            center:  {x: 273, y: 14 },
            left:    {x: 34,  y: 204},
            middle:  {x: 167, y: 204},
            right:   {x: 281, y: 219},
        },
        fallarbor_r113: {
            move:    {x: 52,  y: 77 },
            contest: {x: 136, y: 130},
            center:  {x: 231, y: 96 },
            house:   {x: 103, y: 253},
            mart:    {x: 255, y: 223},
            ashes:   {x: 450, y: 156},
        },

        lavaridge: {
            center:      {x: 100, y: 80 , name: "Lavaridge Town"     },
            mart:        {x: 199, y: 60 , name: "Lavaridge Town"     },
            gym:         {x: 52,  y: 215, name: "Lavaridge Town"     },
            herbs:       {x: 140, y: 270, name: "Lavaridge Town"     },
            house:       {x: 230, y: 215, name: "Lavaridge Town"     },
            center_top:  {x: 325, y: 24 , name: "Lavaridge (Center)" },
            center_left: {x: 313, y: 99 , name: "Lavaridge (Center)" },
            center_bot:  {x: 398, y: 149, name: "Lavaridge (Center)" },
        },

        fortree: {
            center:  {x: 95,  y: 81 },
            top1:    {x: 168, y: 29 },
            top2:    {x: 280, y: 66 },
            top3:    {x: 408, y: 29 },
            top4:    {x: 521, y: 66 },
            mart:    {x: 79,  y: 225},
            gym:     {x: 359, y: 148, name: "Fortree City (Gym)"},
            bottom1: {x: 199, y: 185},
            bottom2: {x: 570, y: 185},
        },

        lilycove: {
            department:   {x: 309, y: 75,  name: "Lilycove City"           },
            deleter:      {x: 453, y: 125, name: "Lilycove City"           },
            rightdeleter: {x: 552, y: 75,  name: "Lilycove City"           },
            leftcenter:   {x: 84,  y: 197, name: "Lilycove City"           },
            center:       {x: 261, y: 199, name: "Lilycove City"           },
            club:         {x: 501, y: 198, name: "Lilycove City"           },
            coast:        {x: 745, y: 212, name: "Lilycove City"           },
            lefthall:     {x: 84,  y: 323, name: "Lilycove City"           },
            hall:         {x: 243, y: 354, name: "Lilycove City"           },
            motel:        {x: 469, y: 356, name: "Lilycove City"           },
            harbor:       {x: 84,  y: 485, name: "Lilycove City"           },
            aqua:         {x: 745, y: 53,  name: "Lilycove (Aqua Hideout)" },
            hall_left:    {x: 487, y: 482, name: "Lilycove's Contest Hall" },
            hall_right:   {x: 677, y: 480, name: "Lilycove's Contest Hall" },
            hall_bot:     {x: 571, y: 587, name: "Lilycove's Contest Hall" },
            art_museum:   {x: 61 , y: 50 , name: "Lilycove's Art Museum"   }
        },

        mossdeep_r124: {
            steven:     {x: 95,  y: 100, name: "Mossdeep City"         },
            leftgym:    {x: 234, y: 65,  name: "Mossdeep City"         },
            gym:        {x: 391, y: 120, name: "Mossdeep City"         },
            leftcenter: {x: 84,  y: 222, name: "Mossdeep City"         },
            center:     {x: 239, y: 188, name: "Mossdeep City"         },
            mart:       {x: 385, y: 222, name: "Mossdeep City"         },
            botmart:    {x: 374, y: 315, name: "Mossdeep City"         },
            space:      {x: 710, y: 160, name: "Mossdeep City"         },
            botspace:   {x: 746, y: 330, name: "Mossdeep City"         },
            leftspace:  {x: 574, y: 24 , name: "Mossdeep City"         },
            r124:       {x: 84,  y: 314, name: "Route 124"             },
            r125:       {x: 759, y: 23 , name: "Route 125 (Shoal Cave)"}
        },
        sootopolis: {
            mart:       {x: 192, y: 399, name: "Sootopolis (Left Side)" },
            left1:      {x: 80,  y: 495, name: "Sootopolis (Left Side)" },
            left2:      {x: 80,  y: 346, name: "Sootopolis (Left Side)" },
            left3:      {x: 80,  y: 201, name: "Sootopolis (Left Side)" },
            left4:      {x: 80,  y: 25 , name: "Sootopolis (Left Side)" },
            center:     {x: 608, y: 428, name: "Sootopolis (Right Side)"},
            right1:     {x: 719, y: 509, name: "Sootopolis (Right Side)"},
            right2:     {x: 719, y: 376, name: "Sootopolis (Right Side)"},
            right3:     {x: 645, y: 323, name: "Sootopolis (Right Side)"},
            right4:     {x: 615, y: 203, name: "Sootopolis (Right Side)"},
            right5:     {x: 631, y: 26 , name: "Sootopolis (Right Side)"},
            gym:        {x: 406, y: 442, name: "Sootopolis (Gym)"       },
            underwater: {x: 393, y: 682, name: "Sootopolis (Underwater)"},
            cave:       {x: 407, y: 179, name: "Sootopolis (Cave)"      },
        },
        pacifidlog: {
            center:    {x: 143, y: 83 },
            topleft:   {x: 39,  y: 46 },
            topright:  {x: 263, y: 70 },
            botleft:   {x: 55,  y: 209},
            botmiddle: {x: 200, y: 238},
            botright:  {x: 280, y: 191},
        },
        evergrande: {
			center:      {x: 183, y: 476,                         name: "Ever Grande (Victory R.)" },
            cave:        {x: 38,  y: 362,                         name: "Ever Grande (Victory R.)" },
			center_top:  {x: 404, y: 386,                         name: "Ever Grande (E4)"         },
			center_left: {x: 258, y: 433,                         name: "Ever Grande (E4)"         },
			center_bot:  {x: 404, y: 507,                         name: "Ever Grande (E4)"         },
            sidney_top:  {x: 134, y: 26,  corridor: "sidney_bot", name: "Elite 4 (Sidney)"         },
			sidney_bot:  {x: 134, y: 145, corridor: "sidney_top", name: "Elite 4 (Sidney)"         },
			phoebe_top:  {x: 344, y: 26,  corridor: "phoebe_bot", name: "Elite 4 (Phoebe)"         },
			phoebe_bot:  {x: 344, y: 145, corridor: "phoebe_top", name: "Elite 4 (Phoebe)"         },
			glacia_top:  {x: 134, y: 190, corridor: "glacia_bot", name: "Elite 4 (Glacia)"         },
			glacia_bot:  {x: 134, y: 305, corridor: "glacia_top", name: "Elite 4 (Glacia)"         },
			drake_top:   {x: 344, y: 190, corridor: "drake_bot",  name: "Elite 4 (Drake)"          },
			drake_bot:   {x: 344, y: 305, corridor: "drake_top",  name: "Elite 4 (Drake)"          },
        },

        // Routes
        petalburgwoods_r104: {
            briney:         {x: 392, y: 510, name: "Route 104 (Petalburg)"},
            woodsentrance:  {x: 289, y: 362, name: "Route 104 (Petalburg)"},
            woodsbotexit:   {x: 641, y: 417, name: "Route 104 (Petalburg)"},
            woods_entrance: {x: 111, y: 691, name: "Petalburg Woods"      },
            woods_botexit:  {x: 431, y: 691, name: "Petalburg Woods"      },
            woods_topexit:  {x: 79,  y: 216, name: "Petalburg Woods"      },
            woodstopexit:   {x: 420, y: 207, name: "Route 104 (Rustboro)" },
            flowers:        {x: 332, y: 89 , name: "Route 104 (Rustboro)" },
        },
        rusturftunnel_r116:  {
            house:       {x: 197, y: 70,  name: "Route 116"     },
            cave:        {x: 342, y: 130, name: "Route 116"     },
            cave_left:   {x: 70,  y: 390, name: "Rusturf Tunnel"},
            cave_middle: {x: 298, y: 550, name: "Rusturf Tunnel"},
            cave_right:  {x: 472, y: 486, name: "Rusturf Tunnel"},
        },
        r110:                {
            topcycle:    {x: 72,  y: 104,                          name: "Route 110 (Mauville)"    },
            powerplant:  {x: 279, y: 88,                           name: "Route 110 (Power Plant)" },
            trickhouse:  {x: 71,  y: 325,                          name: "Route 110 (Trick House)" },
            botcycle:    {x: 230, y: 360,                          name: "Route 110 (Slateport)"   },
			trick_left:  {x: 20,  y: 194, corridor: "trick_right", name: "Trick House Prize"       },
			trick_right: {x: 146, y: 192, corridor: "trick_left",  name: "Trick House Prize"       },
            cycle_top:   {x: 119, y: 69,  corridor: "cycle_bot",   name: "Cycle Road"              },
			cycle_bot:   {x: 280, y: 322, corridor: "cycle_top",   name: "Cycle Road"              },
        },
        r111_r112:           {
            jaggedentrance:  {x: 79,  y: 181, name: "Route 111 (Lavaridge)"   },
            fieryentrance:   {x: 152, y: 73 , name: "Route 111 (Fiery Entr.)" },
            fieryexit:       {x: 295, y: 59 , name: "Route 111 (Fiery Exit)"  },
            cablecar:        {x: 399, y: 165, name: "Route 111 (Cable Car)"   },
            trainerhill:     {x: 385, y: 290, name: "Route 111 (Trainer Hill)"},
            reststop:        {x: 391, y: 64 , name: "Route 111 (Heal Lady)"   },
            familyhouse:     {x: 72,  y: 411, name: "Route 112 (Family)"      },
            desert_mirage:   {x: 195, y: 421, name: "Route 112 (Mirage)"      },
            desert_regirock: {x: 358, y: 398, name: "Route 112 (Regirock)"    },
        },
        r114: {
            fossilmaniac: {x: 264, y: 66 ,                          name: "Route114 (Fossil Maniac)" },
            lanette:      {x: 247, y: 190,                          name: "Route 114 (Lanette)"      },
            meteorfalls:  {x: 87,  y: 187,                          name: "Route 114 (Meteor Falls)" },
            maniac_top:   {x: 70,  y: 10,  corridor: "maniac_bot",  name: "Fossil Maniac's House"    },
			maniac_bot:   {x: 80,  y: 102, corridor: "maniac_top",  name: "Fossil Maniac's House"    },
        },
        r119_r123:           {
            r119_house:       {x: 166, y: 287, name: "Route 119 (House)"  },
            weatherinstitute: {x: 103, y: 105, name: "Route 119 (Weather)"},
            berrymaster:      {x: 332, y: 207, name: "Route 123"          },
        },
        r120_r121:           {
            scorchedslab: {x: 286, y: 40 , name: "Route 120 (Slab)"   },
            ancienttomb:  {x: 104, y: 87 , name: "Route 120 (Tomb)"   },
            safari:       {x: 286, y: 158, name: "Route 121 (Safari)" },
        },

        // Important locations
        granitecave_r105_r106: {
            r105:            {x: 104, y: 332, name: "Route 105"    },
            graniteentrance: {x: 88,  y: 643, name: "Route 106"    },
            f1_entrance:     {x: 667, y: 191, name: "Granite (1F)" },
            f1_botstairs:    {x: 347, y: 158, name: "Granite (1F)" },
            f1_topstairs:    {x: 636, y: 79 , name: "Granite (1F)" },
            f1_steven:       {x: 154, y: 139, name: "Granite (1F)" },
            bf1_entrance:    {x: 299, y: 574, name: "Granite (1BF)"},
            bf1_exit:        {x: 683, y: 580, name: "Granite (1BF)"},
            bf1_optional1:   {x: 363, y: 366, name: "Granite (1BF)"},
            bf1_optional2:   {x: 428, y: 286, name: "Granite (1BF)"},
            bf1_optional3:   {x: 701, y: 323, name: "Granite (1BF)"},
            bf2_topstairs:   {x: 427, y: 721, name: "Granite (2BF)"},
            bf2_botstairs:   {x: 364, y: 801, name: "Granite (2BF)"},
        },
        abandonedship_r108: {
            r108_entrance:       {x: 365, y: 393, name: "Route 108 (Ship)"      },

            bedroom_left:        {x: 303, y: 321, name: "Abandoned Ship (Beds)" },
            bedroom_right:       {x: 440, y: 321, name: "Abandoned Ship (Beds)" },
            bedroom_top:         {x: 440, y: 116, name: "Abandoned Ship (Beds)" },

            line_stairs:         {x: 77,  y: 31 , name: "Abandoned Ship (Line)" },
            line_top:            {x: 54,  y: 64 , name: "Abandoned Ship (Line)" },
            line_bot:            {x: 54,  y: 113, name: "Abandoned Ship (Line)" },
            line_exit:           {x: 52,  y: 170, name: "Abandoned Ship (Line)" },

            block_stairs:        {x: 258, y: 20 , name: "Abandoned Ship (Block)"},
            block_topleft:       {x: 180, y: 45 , name: "Abandoned Ship (Block)"},
            block_topright:      {x: 232, y: 66 , name: "Abandoned Ship (Block)"},
            block_botleft:       {x: 180, y: 116, name: "Abandoned Ship (Block)"},
            block_botright:      {x: 232, y: 137, name: "Abandoned Ship (Block)"},
            block_exit:          {x: 156, y: 170, name: "Abandoned Ship (Block)"},

            hub_stairsleft:      {x: 52,  y: 230, name: "Abandoned Ship (Hub)"  },
            hub_stairsright:     {x: 155, y: 230, name: "Abandoned Ship (Hub)"  },
            hub_top1:            {x: 55,  y: 282, name: "Abandoned Ship (Hub)"  },
            hub_top2:            {x: 104, y: 262, name: "Abandoned Ship (Hub)"  },
            hub_locked:          {x: 184, y: 282, name: "Abandoned Ship (Hub)"  },
            hub_bot1:            {x: 82,  y: 340, name: "Abandoned Ship (Hub)"  },
            hub_bot2:            {x: 136, y: 310, name: "Abandoned Ship (Hub)"  },
            hub_bot3:            {x: 188, y: 340, name: "Abandoned Ship (Hub)"  },
        },
        miragetower: {
            f1_entrance: {x: 169, y: 495, name: "Mirage Tower (1F)"},
			f1_stairs:   {x: 250, y: 360, name: "Mirage Tower (1F)"},
			f2_entrance: {x: 250, y: 73,  name: "Mirage Tower (2F)"},
			f2_stairs:   {x: 297, y: 156, name: "Mirage Tower (2F)"},
			f3_entrance: {x: 610, y: 311, name: "Mirage Tower (3F)"},
			f3_stairs:   {x: 386, y: 250, name: "Mirage Tower (3F)"},
        },
        magmahideout_jaggedpass: {
            jagged_top: {x: 369, y: 602, name: "Jagged Pass (Top)"  },
            jagged_mid: {x: 554, y: 602, name: "Jagged Pass (Magma)"},
            jagged_bot: {x: 720, y: 602, name: "Jagged Pass (Bot)"  },
            f1_left:    {x: 90,  y: 233, name: "Magma Hideout (1F)" },
            f1_top:     {x: 248, y: 78 , name: "Magma Hideout (1F)" },
            f1_right:   {x: 329, y: 230, name: "Magma Hideout (1F)" },
            f2_top:     {x: 521, y: 76 , name: "Magma Hideout (2F)" },
            f2_mid:     {x: 566, y: 335, name: "Magma Hideout (2F)" },
            f2_bot:     {x: 664, y: 519, name: "Magma Hideout (2F)" },
            f3_top:     {x: 374, y: 370, name: "Magma Hideout (3F)" },
            f3_mid:     {x: 344, y: 465, name: "Magma Hideout (3F)" },
            f3_bot:     {x: 122, y: 614, name: "Magma Hideout (3F)" },
        },
        meteorfalls_r115: {
            r115_exit:        {x: 703, y: 570, name: "Route 115 (Meteor)"     },

            f1r1_entrance:    {x: 735, y: 440, name: "Meteor Falls (1F Room1)"},
            f1r1_exit:        {x: 512, y: 564, name: "Meteor Falls (1F Room1)"},
            f1r1_cave:        {x: 466, y: 430, name: "Meteor Falls (1F Room1)"},

            f1r2_cave:        {x: 536, y: 279, name: "Meteor Falls (1F Room2)"},
            f1r2_stairstop:   {x: 445, y: 80 , name: "Meteor Falls (1F Room2)"},
            f1r2_stairsmid:   {x: 490, y: 181, name: "Meteor Falls (1F Room2)"},
            f1r2_stairsright: {x: 715, y: 231, name: "Meteor Falls (1F Room2)"},

            f2_stairsbot:     {x: 85,  y: 336, name: "Meteor Falls (2F)"      },
            f2_stairstop:     {x: 89,  y: 128, name: "Meteor Falls (2F)"      },
            f2_stairsmid:     {x: 122, y: 213, name: "Meteor Falls (2F)"      },
            f2_stairsright:   {x: 296, y: 276, name: "Meteor Falls (2F)"      },
            f2_cavebot:       {x: 327, y: 573, name: "Meteor Falls (2F)"      },
            f2_cavetop:       {x: 280, y: 80 , name: "Meteor Falls (2F)"      },
        },
        mtpyre_r122: {
            r122_entrance:  {x: 654, y: 343, name: "Route 122 (Mt. Pyre)"},

            f1_entrance:    {x: 287, y: 270, name: "Mt. Pyre (1F)"       },
            f1_exit:        {x: 82,  y: 132, name: "Mt. Pyre (1F)"       },
            f1_stairs:      {x: 185, y: 48,  name: "Mt. Pyre (1F)"       },

            f2_stairsright: {x: 538, y: 10,  name: "Mt. Pyre (2F)"       },
            f2_stairsleft:  {x: 406, y: 45,  name: "Mt. Pyre (2F)"       },
            f2_hole:        {x: 550, y: 132, name: "Mt. Pyre (2F)"       },

            f3_stairsright: {x: 718, y: 60,  name: "Mt. Pyre (3F)"       },
            f3_stairsleft:  {x: 632, y: 100, name: "Mt. Pyre (3F)"       },
            f3_hole:        {x: 718, y: 272, name: "Mt. Pyre (3F)"       },

            f4_stairsleft:  {x: 82,  y: 405, name: "Mt. Pyre (4F)"       },
            f4_stairsright: {x: 167, y: 360, name: "Mt. Pyre (4F)"       },
            f4_hole:        {x: 151, y: 463, name: "Mt. Pyre (4F)"       },

            f5_holetop:     {x: 501, y: 381, corridor: "f5_holetop", name: "Mt. Pyre (5F)"    },
            f5_holebot:     {x: 501, y: 459, corridor: "f5_holebot", name: "Mt. Pyre (5F)"    }
        },
        departmentstore: {
            f1_entrance: {x: 48,  y: 395, name: "Lilycove Store" },
            f1_stairs:   {x: 168, y: 325, name: "Lilycove Store" },
            f2_left:     {x: 120, y: 180, name: "Lilycove Store" },
            f2_right:    {x: 168, y: 150, name: "Lilycove Store" },
            f3_left:     {x: 120, y: 35,  name: "Lilycove Store" },
            f3_right:    {x: 168, y: 9,   name: "Lilycove Store" },
            f4_left:     {x: 328, y: 325, name: "Lilycove Store" },
            f4_right:    {x: 368, y: 295, name: "Lilycove Store" },
            f5_left:     {x: 328, y: 180, name: "Lilycove Store" },
            f5_right:    {x: 368, y: 150, name: "Lilycove Store" },
        },
        aquahideout: {
            small_stairs:     {x: 242, y: 183, name: "Aqua Hideout (Small)"},
            small_left:       {x: 210, y: 237, name: "Aqua Hideout (Small)"},
            small_right:      {x: 274, y: 267, name: "Aqua Hideout (Small)"},

            long_top:         {x: 55,  y: 331, name: "Aqua Hideout (Long)" },
            long_bot:         {x: 56,  y: 406, name: "Aqua Hideout (Long)" },
            long_right:       {x: 251, y: 395, name: "Aqua Hideout (Long)" },
            generator_stairs: {x: 72,  y: 43 , name: "Aqua Hideout (Big)"  },
            generator_left:   {x: 71,  y: 201, name: "Aqua Hideout (Big)"  },
            generator_right:  {x: 280, y: 120, name: "Aqua Hideout (Big)"  },

            hub_entrance:     {x: 426, y: 116, name: "Aqua Hideout (Hub 1)"},
            hub_row1left:     {x: 358, y: 169, name: "Aqua Hideout (Hub 1)"},
            hub_row1mid:      {x: 426, y: 147, name: "Aqua Hideout (Hub 1)"},
            hub_row1right:    {x: 462, y: 169, name: "Aqua Hideout (Hub 1)"},

            hub_row2left:     {x: 358, y: 233, name: "Aqua Hideout (Hub 2)"},
            hub_row2mid:      {x: 426, y: 211, name: "Aqua Hideout (Hub 2)"},
            hub_row2right:    {x: 462, y: 233, name: "Aqua Hideout (Hub 2)"},

            hub_row3left:     {x: 358, y: 297, name: "Aqua Hideout (Hub 3)"},
            hub_row3mid:      {x: 426, y: 274, name: "Aqua Hideout (Hub 3)"},
            hub_row3right:    {x: 462, y: 297, name: "Aqua Hideout (Hub 3)"},

            hub_row4left:     {x: 358, y: 361, name: "Aqua Hideout (Hub 4)"},
            hub_row4mid:      {x: 426, y: 339, name: "Aqua Hideout (Hub 4)"},
            hub_row4right:    {x: 462, y: 361, name: "Aqua Hideout (Hub 4)"},
        },
        seafloor_underwater: {
            underwater_r126: {x: 151, y: 660, name: "Route 126"          },
            underwater_r128: {x: 711, y: 660, name: "Route 128"          },

            room1_top:       {x: 104, y: 60 , name: "Seafloor (Room 1)"  },
            room1_right:     {x: 279, y: 207, name: "Seafloor (Room 1)"  },
            room1_left:      {x: 87,  y: 284, name: "Seafloor (Room 1)"  },

            room2_top:       {x: 370, y: 50 , name: "Seafloor (Room 2)"  },
            room2_right:     {x: 534, y: 185, name: "Seafloor (Room 2)"  },
            room2_left:      {x: 416, y: 268, name: "Seafloor (Room 2)"  },

            room3_topleft:   {x: 578, y: 50 , name: "Seafloor (Room 3)"  },
            room3_topright:  {x: 745, y: 50 , name: "Seafloor (Room 3)"  },
            room3_mid:       {x: 702, y: 185, name: "Seafloor (Room 3)"  },
            room3_bot:       {x: 711, y: 284, name: "Seafloor (Room 3)"  },

            room4_topleft:   {x: 104, y: 390, name: "Seafloor (Boulders)"},
            room4_topright:  {x: 186, y: 335, name: "Seafloor (Boulders)"},
            room4_botleft:   {x: 84,  y: 512, name: "Seafloor (Boulders)"},
            room4_botright:  {x: 167, y: 450, name: "Seafloor (Boulders)"},

            room5_top:       {x: 333, y: 400, name: "Seafloor (Surf)"    },
            room5_mid:       {x: 493, y: 507, name: "Seafloor (Surf)"    },
            room5_bot:       {x: 445, y: 674, name: "Seafloor (Surf)"    },

            room7_top:       {x: 712, y: 379, name: "Seafloor (Puzzle)"  },
            room7_right:     {x: 726, y: 525, name: "Seafloor (Puzzle)"  },
            room7_left:      {x: 646, y: 560, name: "Seafloor (Puzzle)"  },
        },

        skypillar_r131: {
            r131_entrance: {x: 184, y: 551, name: "Route 131 (Sky Pillar)"},
            f1_entrance:   {x: 111, y: 431, name: "Sky Pillar (1F)"       },
            f1_stairs:     {x: 167, y: 227, name: "Sky Pillar (1F)"       },
            f2_left:       {x: 56,  y: 50,  name: "Sky Pillar (2F)"       },
            f2_right:      {x: 168, y: 14,  name: "Sky Pillar (2F)"       },
            f3_left:       {x: 280, y: 287, name: "Sky Pillar (3F)"       },
            f3_mid:        {x: 360, y: 227, name: "Sky Pillar (3F)"       },
            f3_right:      {x: 435, y: 287, name: "Sky Pillar (3F)"       },
            f4_left:       {x: 280, y: 50,  name: "Sky Pillar (4F)"       },
            f4_mid:        {x: 360, y: 14,  name: "Sky Pillar (4F)"       },
            f4_right:      {x: 435, y: 50,  name: "Sky Pillar (4F)"       },
        },
        victoryroad: {
            bf1_topleft:  {x: 137, y: 82 , name: "Victory Road (1BF)"},
            bf1_midleft:  {x: 278, y: 230, name: "Victory Road (1BF)"},
            bf1_midright: {x: 330, y: 373, name: "Victory Road (1BF)"},
            bf1_botleft:  {x: 89,  y: 395, name: "Victory Road (1BF)"},
            bf1_botmid:   {x: 489, y: 440, name: "Victory Road (1BF)"},
            bf1_botright: {x: 680, y: 366, name: "Victory Road (1BF)"},

            bf2_top:      {x: 680, y: 540, name: "Victory Road (2BF)"},
            bf2_mid:      {x: 313, y: 570, name: "Victory Road (2BF)"},
            bf2_left:     {x: 86,  y: 715, name: "Victory Road (2BF)"},
            bf2_right:    {x: 484, y: 695, name: "Victory Road (2BF)"},
        },
        victoryroad_corridors: {
            f1_entrybot:  {x: 207, y: 530, corridor: "f1_entrytop",  name: "Victory Road (F1 Entry)" },
			f1_entrytop:  {x: 127, y: 215, corridor: "f1_entrybot",  name: "Victory Road (F1 Entry)" },
			f1_exitbot:   {x: 288, y: 455, corridor: "f1_exittop",   name: "Victory Road (F1 Exit)"  },
			f1_exittop:   {x: 526, y: 100, corridor: "f1_exitbot",   name: "Victory Road (F1 Exit)"  },
			exterior_bot: {x: 71,  y: 65,  corridor: "exterior_top", name: "Ever Grande (Entrance)"  },
			exterior_top: {x: 219, y: 45,  corridor: "exterior_bot", name: "Ever Grande (Entrance)"  },
        },
        navelrock: {
            stairsleft:   {x: 74,  y: 76 },
            stairsright:  {x: 360, y: 76 },
            stairsbottom: {x: 184, y: 252},
        },
    },

    // Numbers are meant to be to check if exist any marks/progress in the maps
    // if null, then we don't do tracking
    // if undefined, then we don't draw the mark
    marks: [
        [["unknown",     0], ["corridor",    0], ["dead_end", null], ["event",      0], ["center",      0], ["mart",        0], ["one_way", null]],
        [["normal",      0], ["fighting",    0], ["flying",      0], ["poison",     0], ["ground",      0], ["rock",        0], ["bug",        0], ["ghost",       0], ["fairy",       0]],
        [["steel",       0], ["fire",        0], ["water",       0], ["grass",      0], ["electric",    0], ["psychic",     0], ["ice",        0], ["dragon",      0], ["dark",        0]],
        [["1",           0], ["2",           0], ["3",           0], ["4",          0], ["5",           0], ["6",           0], ["7",          0], ["8",           0]],
        [["team_magma",  0], ["team_aqua",   0], ["",    undefined], ["rayquaza",   0], ["e_legendary", 0], ["c_legendary", 0], ["burned_tower", 0]],
        [["e_bush",      0], ["e_surf",      0], ["e_boulder",   0], ["e_darkness", 0], ["e_rock",      0], ["e_waterfall", 0], ["e_dive",     0], ["c_whirlpool", 0], ["bike_needed", 0]],
        [["team_rocket", 0], ["frlg_rival",   0], ["c_rival",     0], ["e_trainer",   0], ["",     undefined], ["safari",        0], ["masterball", 0]],
    ],
    progress: [
        [["boulder_badge", 0], ["cascade_badge", 0], ["thunder_badge", 0] , ["rainbow_badge", 0], ["soul_badge", 0]   , ["marsh_badge",  0] , ["volcano_badge", 0], ["earth_badge",  0]],
        [["zephyr_badge",  0], ["hive_badge",    0], ["plain_badge",    0], ["fog_badge",     0], ["storm_badge",   0], ["mineral_badge", 0], ["glacier_badge", 0], ["rising_badge", 0]],
        [["stone_badge", 0], ["knuckle_badge", 0], ["dynamo_badge", 0], ["heat_badge",   0], ["balance_badge", 0], ["feather_badge", 0], ["mind_badge",    0], ["rain_badge", 0]],

        [["frlg_lorelei",  0], ["frlg_bruno",    0] , ["frlg_agatha",   0], ["frlg_lance",    0], ["frlg_blue",  0]],
        [["hgss_will",     0], ["hgss_koga",      0], ["hgss_bruno",    0], ["hgss_karen",    0], ["hgss_lance",   0]],
        [["e_sidney",    0]  , ["e_phoebe",      0] , ["e_glacia",     0] , ["e_drake",      0 ], ["e_wallace",     0], ["",      undefined], ["e_steven",   0]],

        [["hm_cut",      0], ["hm_fly",        0], ["hm_surf",      0], ["hm_strength",  0], ["hm_flash",      0], ["hm_rocksmash",  0], ["hm_waterfall",  0], ["hm_dive",    0], ["hm_whirlpool",  0]],

        [["bike_voucher",  0], ["bike",          0], ["",      undefined], ["parcel",       0], ["poke_flute", 0], ["tea",           0], ["silph_scope",   0], ["gold_teeth",    0]],
        [["card_key",      0], ["lift_key",      0], ["secret_key",    0], ["ss_ticket",    0], ["",   undefined], ["storage_key",   0], ["magma_emblem",  0], ["go_goggles",    0], ["devon_scope",   0]],
        [["squirt_bottle", 0], ["secret_potion", 0], ["",   undefined]   , ["basement_key", 0], ["red_scale",  0], ["mystery_egg",   0], ["coin_case",     0], ["itemfinder",    0]],
    ],
    modifiers: [
		[["#ce4069", 0], ["#ff9c54", 0], ["#f3d23b", 0], ["#743683", 0], ["#654321", 0], ["#014f01", 0]],
		[["#4d90d5", 0], ["#74cec0", 0], ["#90c12c", 0], ["#ec8fe6", 0], ["#5a5366", 0], ["#00146b", 0]],
	],
};