let rb = {
    debug: false,
    name: "rb",
    folder: "rb",
    start_location: "viridian",
    font: "GameBoy_Font",
    font_size: "22px",

    // Config texts
    config_name: "Red/Blue",
    config_randomizer_author: "Archipelago",
    config_randomizer_link: "https://archipelago.gg/tutorial/Pokemon Red and Blue/setup/en",
    // config_tracker_author: "", 
    // config_tracker_link: "",

    // Tracker information
    locations: {
        // Cities
        pallet:           {x: 24,  y: 85,  w: 8,  h: 8,  name: "Pallet Town"                                                 },
        viridian:         {x: 24,  y: 64,  w: 8,  h: 8,  name: "Viridian City\nRoute 22",       link_name: "Viridian City"   },
        pewter:           {x: 24,  y: 32,  w: 8,  h: 8,  name: "Pewter City"                                                 },
        cerulean:         {x: 104, y: 24,  w: 8,  h: 8,  name: "Cerulean City\nRoutes 5 & 25",  link_name: "Cerulean City"   },
        vermilion:        {x: 104, y: 72,  w: 8,  h: 8,  name: "Vermilion City\nRoutes 6 & 11", link_name: "Vermilion City"  },
        lavender:         {x: 136, y: 48,  w: 8,  h: 8,  name: "Lavender Town\nRoute 8",        link_name: "Lavender Town"   },
        celadon:          {x: 80,  y: 48,  w: 8,  h: 8,  name: "Celadon City\nRoutes 7 & 16",   link_name: "Celadon City"    },
        saffron:          {x: 104, y: 48,  w: 8,  h: 8,  name: "Saffron City"                                                },
        fuchsia:          {x: 88,  y: 96,  w: 8,  h: 8,  name: "Fuchsia City\nRoute 15",       link_name: "Fuchsia City"    },
        cinnabar:         {x: 24,  y: 112, w: 8,  h: 8,  name: "Cinnabar Island"                                             },
        indigo:           {x: 8,   y: 24,  w: 8,  h: 8,  name: "Indigo Plateau"                                              },

        // Routes
        r2:               {x: 24,  y: 48,  w: 8,  h: 8,  name: "Route 2"                                                     },
        r10:              {x: 136, y: 32,  w: 8,  h: 8,  name: "Route 10"                                                    },
        r12:              {x: 136, y: 72,  w: 8,  h: 8,  name: "Route 12"                                                    },

        // Important locations
        cerulean_cave:    {x: 96,  y: 16,  w: 8,  h: 8,  name: "Cerulean Cave"                                               },
        department_store: {x: 80,  y: 40,  w: 8,  h: 8,  name: "Department Store"                                            },
        department_elevator: {x: 87 , y: 40, w: 8, h: 8,  name: "Department Store\nElevator"                                 },
        condominiums:      {x: 94,  y: 40,  w: 8,  h: 8,  name: "Celadon Condiminums"                                         },
        cinnabar_mansion: {x: 16,  y: 112, w: 8,  h: 8,  name: "Cinnabar Mansion"                                            },
        mt_moon:          {x: 64,  y: 24,  w: 8,  h: 8,  name: "Mt. Moon\nRoute 4",             link_name: "Mt. Moon"        },
        rocket_hideout:   {x: 80,  y: 56,  w: 8,  h: 8,  name: "Rocket Hideout"                                              },
        rocket_elevator:  {x: 87,  y: 56,  w: 8,  h: 8,  name: "Rocket Hideout\nElevator"                                    },
        seafoam_islands:  {x: 56,  y: 112, w: 8,  h: 8,  name: "Seafoam Islands\nRoute 20",     link_name: "Seafoam Islands" },
        silph_1:          {x: 112, y: 48,  w: 8,  h: 8,  name: "Silph Co.\n1F to 5F",           link_name: "Silph Co."       },
        silph_2:          {x: 112, y: 40,  w: 8,  h: 8,  name: "Silph Co.\n6F to 11F",          link_name: "Silph Co."       },
        silph_elevator:   {x: 119, y: 40,  w: 8,  h: 8,  name: "Silph Co.\nElevator"                                         },
        safari_zone:      {x: 88,  y: 88,  w: 8,  h: 8,  name: "Safari Zone"                                                 },
        saffron_gym:      {x: 119, y: 48,  w: 8,  h: 8,  name: "Saffron City\nGym",             link_name: "Saffron Gym"     },
        ss_anne:          {x: 104, y: 80,  w: 8,  h: 8,  name: "SS Anne"                                                     },
        victory_road:     {x: 8,   y: 32,  w: 8,  h: 8,  name: "Victory Road"                                                },
        gates:            {x: 64,  y: 8,   w: 8,  h: 8,  name: "Gates",                         link_name: "Gate"            },
        rocktunnel: 	  {x: 128, y: 32,  w: 8,  h: 8,  name: "Rock Tunnel",                  								 },
        pokemontower:     {x: 144, y: 48,  w: 8,  h: 8,  name: "Pokémon Tower"                                               },
        cycling_road:     {x: 48,  y: 72,  w: 8,  h: 8,  name: "Cycling Road"                                                },
    },

    // Undefined fields:
    // - link_type:     "warp"        / "mark"
    // - link:          warp_name     / mark_name
    // - link_location: location_name / <garbage>
    warps: {
        condominiums: {
            entrance:                                                   {x: 79, y: 166, name: "Condominiums 1F" },
            stair1:                                                     {x: 39, y: 6, name: "Condominiums 1F" },
            door1:                                                      {x: 71, y: 25, name: "Condominiums 1F" },
            stair2:                                                     {x: 119, y: 6, name: "Condominiums 1F" },
            stair3:                                                     {x: 226, y: 6, name: "Condominiums 2F" },
            stair4:                                                     {x: 259, y: 44, name: "Condominiums 2F" },
            stair5:                                                     {x: 290, y: 7, name: "Condominiums 2F" },
            stair6:                                                     {x: 306, y: 41, name: "Condominiums 2F" },
            stair7:                                                     {x: 39, y: 237, name: "Condominiums 3F" },
            stair8:                                                     {x: 71, y: 277, name: "Condominiums 3F" },
            stair9:                                                     {x: 102, y: 239, name: "Condominiums 3F" },
            stair10:                                                    {x: 117, y: 276, name: "Condominiums 3F" },
            stair11:                                                    {x: 227, y: 238, name: "Condominiums 4F" },
            stair12:                                                    {x: 291, y: 238, name: "Condominiums 4F" },
            door2:                                                      {x: 228, y: 331, name: "Condominiums 4F" },
        },
        celadon: {
            mart1:                                                      {x: 474, y: 191 },
            mart2:                                                      {x: 506, y: 245 },
            cond1:                                                      {x: 729, y: 129 },
			cond2:                                                      {x: 730, y: 38 },
            center:                                                     {x: 1002, y: 124 },
            corner1:                                                    {x: 872, y: 338 },
			corner2:                                                    {x: 797, y: 283 },
            house1:                                                     {x: 844, y: 410 },
			house2:                                                     {x: 906, y: 464 },
			house3:                                                     {x: 1035, y: 413 },
            gym:                                                        {x: 539, y: 417 },
            g:                                                          {x: 89, y: 463, name: "Rt. 7" },
			saffron1:                                                   {x: 169, y: 437, name: "Rt. 7" },
			saffron2:                                                   {x: 261, y: 437, name: "Rt. 7" },
        },
        cerulean: {
            bike:                                                      {x: 223, y: 356 },
            mart:                                                      {x: 462, y: 358 },
            gym:                                                       {x: 562, y: 238 },
            center:                                                    {x: 341, y: 199 },
            house1:                                                    {x: 223, y: 162 },
            house2:                                                    {x: 142, y: 83 },
            house3:                                                    {x: 502, y: 81 },
            bill:                                                      {x: 719, y: 79, name: "Rt. 25" },
            daycare:                                                   {x: 802, y: 201, name: "Rt. 5" },
            g:                                                         {x: 943, y: 314, name: "Rt. 5" },
            saffron1:                                                  {x: 792, y: 361, name: "Rt. 5" },
            saffron2:                                                  {x: 804, y: 433, name: "Rt. 5" },
        },
        cerulean_cave: {
            ladder1:                                                   {x: 25, y: 101, name: "Cerulean Cave 1F" },
            ladder2:                                                   {x: 24, y: 150, name: "Cerulean Cave 1F" },
            ladder3:                                                   {x: 120, y: 70, name: "Cerulean Cave 1F" },
            ladder4:                                                   {x: 441, y: 73, name: "Cerulean Cave 1F" },
            ladder5:                                                   {x: 378, y: 116, name: "Cerulean Cave 1F" },
            ladder6:                                                   {x: 297, y: 150, name: "Cerulean Cave 1F" },
            ladder7:                                                   {x: 58, y: 183, name: "Cerulean Cave 1F" },
            entrance:                                                  {x: 401, y: 286, name: "Cerulean Cave 1F" },
            ladder8:                                                   {x: 25, y: 405, name: "Cerulean Cave 2F" },
            ladder9:                                                   {x: 154, y: 331, name: "Cerulean Cave 2F" },
            ladder10:                                                  {x: 312, y: 467, name: "Cerulean Cave 2F" },
            ladder11:                                                  {x: 362, y: 407, name: "Cerulean Cave 2F" },
            ladder12:                                                  {x: 473, y: 329, name: "Cerulean Cave 2F" },
            ladder13:                                                  {x: 57, y: 488, name: "Cerulean Cave 2F" },
            ladder14:                                                  {x: 543, y: 250, name: "Cerulean Cave B1F" },
        },
        cinnabar: {
            mansion:                                                   {x: 67, y: 48 },
			lab:                                                       {x: 67, y: 144 },
            center:                                                    {x: 147, y: 179 },
            mart:                                                      {x: 211, y: 179 },
            gym:                                                       {x: 258, y: 51 },
            entrance:                                                  {x: 65, y: 364, name: "Cinnabar Lab" },
            door1:                                                     {x: 154, y: 320, name: "Cinnabar Lab" },
            door2:                                                     {x: 217, y: 356, name: "Cinnabar Lab" },
            door3:                                                     {x: 283, y: 320, name: "Cinnabar Lab" },
        },
        cinnabar_mansion: {
            entrance:                                                   {x: 93, y: 284, name: "Cinnabar Mansion 1F" },
			stair1:                                                     {x: 107, y: 42, name: "Cinnabar Mansion 1F" },
            stair2:                                                     {x: 338, y: 206, name: "Cinnabar Mansion 1F" },
            door:                                                       {x: 428, y: 278, name: "Cinnabar Mansion 1F" },
            stair3:                                                     {x: 523, y: 146, name: "Cinnabar Mansion 2F" },
			stair4:                                                     {x: 556, y: 96, name: "Cinnabar Mansion 2F" },
            stair5:                                                     {x: 844, y: 159, name: "Cinnabar Mansion 2F" },
            stair6:                                                     {x: 123, y: 367, name: "Cinnabar Mansion 3F" },
            stair7:                                                     {x: 112, y: 469, name: "Cinnabar Mansion 3F" },
            stair8:                                                     {x: 400, y: 533, name: "Cinnabar Mansion 3F" },
            stair9:                                                     {x: 590, y: 361, name: "Cinnabar Mansion B1F" },
        },
        cycling_road: {
            fly:                                                        {x: 48, y: 47, name: "Cycling Road (Top)" },
            r16_1:                                                      {x: 197, y: 138, name: "Cycling Road (Top)" },
            r16_2:                                                      {x: 292, y: 140, name: "Cycling Road (Top)" },
            r16_3:                                                      {x: 197, y: 46, name: "Cycling Road (Top)" },
            r16_4:                                                      {x: 293, y: 44, name: "Cycling Road (Top)" },
            r18_1:                                                      {x: 121, y: 256, name: "Cycling Road (Bottom)" },
            r18_2:                                                      {x: 214, y: 255, name: "Cycling Road (Bottom)" },
        },
        department_store: {
            entrance1:                                                  {x: 48, y: 101, name: "Department Store 1F" },
            entrance2:                                                  {x: 270, y: 98, name: "Department Store 1F" },
            stair1:                                                     {x: 198, y: 48, name: "Department Store 1F" },
            elevator1:                                                  {x: 24, y: 52, name: "Department Store 1F" },
            stair2:                                                     {x: 544, y: 49, name: "Department Store 2F" },
            stair3:                                                     {x: 609, y: 6, name: "Department Store 2F" },
            elevator2:                                                  {x: 369, y: 52, name: "Department Store 2F" },
            stair4:                                                     {x: 893, y: 47, name: "Department Store 3F" },
            stair5:                                                     {x: 956, y: 2, name: "Department Store 3F" },
            elevator3:                                                  {x: 717, y: 51, name: "Department Store 3F" },
            stair6:                                                     {x: 199, y: 200, name: "Department Store 4F" },
            stair7:                                                     {x: 262, y: 150, name: "Department Store 4F" },
            elevator4:                                                  {x: 19, y: 203, name: "Department Store 4F" },
            stair8:                                                     {x: 542, y: 196, name: "Department Store 5F" },
            stair9:                                                     {x: 606, y: 147, name: "Department Store 5F" },
            elevator5:                                                  {x: 369, y: 207, name: "Department Store 5F" },
            aaaa0:                                                      {x: 941, y: 166, name: "Department Store 6F" },
        },
        department_elevator: {
            f1:                                                         {x: 44, y: 54, name: "Department Store 1F" },
			f2:                                                         {x: 124, y: 54, name: "Department Store 2F" },
			f3:                                                         {x: 202, y: 54, name: "Department Store 3F" },
			f4:                                                         {x: 86, y: 130, name: "Department Store 4F" },
			f5:                                                         {x: 166, y: 130, name: "Department Store 5F" },
        },
        fuchsia: {
            gym:                                                        {x: 43, y: 417 },
			center:                                                     {x: 266, y: 417 },
            warden:                                                     {x: 396, y: 417 },
            fisherman:                                                  {x: 459, y: 417 },
            mart:                                                       {x: 43, y: 194 },
            house:                                                      {x: 315, y: 192 },
            szone:                                                      {x: 252, y: 31 },
            r15_1:                                                      {x: 595, y: 249, name: "Rt. 15" },
			r15_2:                                                      {x: 692, y: 249, name: "Rt. 15" },
        },
        gates: {
            r11_1:                                                      {x: 43, y: 85, name: "Rt. 11 Gate" },
            r11_2:                                                      {x: 127, y: 86, name: "Rt. 11 Gate" },
            r11_3:                                                      {x: 111, y: 144, name: "Rt. 11 Gate" },
            r12_1:                                                      {x: 242, y: 42, name: "Rt. 12 Gate" },
            r12_2:                                                      {x: 242, y: 123, name: "Rt. 12 Gate" },
            r12_4:                                                      {x: 298, y: 107, name: "Rt. 12 Gate" },
            r15_1:                                                      {x: 383, y: 86, name: "Rt. 15 Gate" },
			r15_2:                                                      {x: 462, y: 84, name: "Rt. 15 Gate" },
			r15_3:                                                      {x: 448, y: 141, name: "Rt. 15 Gate" },
            r16_1:                                                      {x: 81, y: 334, name: "Rt. 16 Gate" },
			r16_2:                                                      {x: 161, y: 334, name: "Rt. 16 Gate" },
			r16_3:                                                      {x: 147, y: 388, name: "Rt. 16 Gate" },
			r16_4:                                                      {x: 83, y: 235, name: "Rt. 16 Gate" },
			r16_5:                                                      {x: 163, y: 237, name: "Rt. 16 Gate" },
            r18_1:                                                      {x: 311, y: 288, name: "Rt. 18 Gate" },
			r18_2:                                                      {x: 391, y: 291, name: "Rt. 18 Gate" },
			r18_3:                                                      {x: 375, y: 347, name: "Rt. 18 Gate" },
        },
        indigo: {
            center1:                                                    {x: 177, y: 670 },
            center2:                                                    {x: 184, y: 536 },
			lorelei1:                                                   {x: 80, y: 157 },
			lorelei2:                                                   {x: 78, y: 34 },
			bruno1:                                                     {x: 268, y: 155 },
			bruno2:                                                     {x: 267, y: 33 },
			agatha1:                                                    {x: 80, y: 386 },
			agatha2:                                                    {x: 78, y: 263 },
			lance1:                                                     {x: 266, y: 382 },
			lance2:                                                     {x: 259, y: 256 },
        },
        lavender: {
            center:                                                      {x: 314, y: 68 },
            fuji:                                                        {x: 379, y: 129 },
            house1:                                                      {x: 315, y: 195 },
            house2:                                                      {x: 379, y: 196 },
            mart:                                                        {x: 507, y: 198 },
            tower:                                                       {x: 490, y: 70 },
            g:                                                           {x: 181, y: 74, name: "Rt. 8" },
            saffron1:                                                    {x: 113, y: 167, name: "Rt. 8" },
            saffron2:                                                    {x: 26, y: 170, name: "Rt. 8" },
        },
        mt_moon: {
            entrance:                                                    {x: 226, y: 760, name: "Mt. Moon 1F" },
            ladder1_1:                                                   {x: 37, y: 168, name: "Mt. Moon 1F" },
            ladder2_1:                                                   {x: 277, y: 282, name: "Mt. Moon 1F" },
            ladder3_1:                                                   {x: 439, y: 430, name: "Mt. Moon 1F" },
            ladder1_2:                                                   {x: 555, y: 365, name: "Mt. Moon B1F" },
            ladder1_3:                                                   {x: 874, y: 605, name: "Mt. Moon B1F" },
            ladder1_4:                                                   {x: 632, y: 1067, name: "Mt. Moon B2F" },
            ladder2_2:                                                   {x: 953, y: 370, name: "Mt. Moon B1F" },
            ladder2_3:                                                   {x: 795, y: 414, name: "Mt. Moon B1F" },
            ladder2_4:                                                   {x: 711, y: 913, name: "Mt. Moon B2F" },
            ladder3_2:                                                   {x: 953, y: 492, name: "Mt. Moon B1F" },
            ladder3_3:                                                   {x: 713, y: 735, name: "Mt. Moon B1F" },
            ladder3_4:                                                   {x: 511, y: 1266, name: "Mt. Moon B2F" },
            ladder4_1:                                                   {x: 309, y: 941, name: "Mt. Moon B2F" },
            ladder4_2:                                                   {x: 913, y: 259, name: "Mt. Moon B1F" },
            ladder4_3:                                                   {x: 992, y: 325, name: "Mt. Moon B1F" },
            r4_center:                                                   {x: 621, y: 95, name: "Rt. 4" },
            r4_w:                                                        {x: 831, y: 95, name: "Rt. 4" },
            r4_e:                                                        {x: 1010, y: 91, name: "Rt. 4" },
        },
        pallet: {
            house1:                                                      {x: 88, y: 73 },
            house2:                                                      {x: 216, y: 73 },
            lab:                                                         {x: 200, y: 171 },
        },
        pewter: {
            s_house:                                                     {x: 48, y: 523 },
            center:                                                      {x: 169, y: 442 },
            mart:                                                        {x: 368, y: 282 },
            gym:                                                         {x: 228, y: 282 },
            e_house:                                                     {x: 489, y: 202 },
            w_museum:                                                    {x: 189, y: 80 },
            e_museum:                                                    {x: 289, y: 42 },
        },
        pokemontower: {
            entrance:                                                    {x: 146, y: 263, name: "Pokemon Tower 1F" },
            stair1:                                                      {x: 245, y: 136, name: "Pokemon Tower 1F" },
            stair2:                                                      {x: 339, y: 164, name: "Pokemon Tower 2F" },
            stair3:                                                      {x: 558, y: 127, name: "Pokemon Tower 2F" },
            stair4:                                                      {x: 27, y: 428, name: "Pokemon Tower 3F" },
			stair5:                                                      {x: 263, y: 474, name: "Pokemon Tower 3F" },
            stair6:                                                      {x: 322, y: 431, name: "Pokemon Tower 4F" },
            stair7:                                                      {x: 559, y: 432, name: "Pokemon Tower 4F" },
            stair8:                                                      {x: 24, y: 736, name: "Pokemon Tower 5F" },
            stair9:                                                      {x: 260, y: 739, name: "Pokemon Tower 5F" },
            stair10:                                                     {x: 561, y: 729, name: "Pokemon Tower 6F" },
            stair11:                                                     {x: 416, y: 842, name: "Pokemon Tower 6F" },
        },
        r10: {
            center:                                                      {x: 107, y: 82 },
            rocktunnel:                                                  {x: 65, y: 53 },
            powerplant:                                                  {x: 78, y: 218, name: "Rt. 10 (Power Plant)" },
            rocktunnel2:                                                 {x: 72, y: 298 },
        },
        r12: {
            r12_1:                                                       {x: 50, y: 16 },
			r12_2:                                                       {x: 47, y: 61 },
			fisherman:                                                   {x: 50, y: 162 },
        },
        r2: {
            v_gate_s:                                                    {x: 47, y: 407 },
            flash:                                                       {x: 216, y: 351 },
            trade:                                                       {x: 216, y: 202 },
            v_gate_n:                                                    {x: 47, y: 145 },
            d_cave:                                                      {x: 174, y: 61 },
        },
        rocktunnel: {
            ladder1:                                                      {x: 87, y: 30, name: "Rock Tunnel 1F" },
            ladder2:                                                      {x: 248, y: 25, name: "Rock Tunnel 1F" },
            ladder3:                                                      {x: 579, y: 32, name: "Rock Tunnel 1F" },
            ladder4:                                                      {x: 280, y: 155, name: "Rock Tunnel 1F" },
            ladder5:                                                      {x: 599, y: 246, name: "Rock Tunnel 1F" },
            ladder6:                                                      {x: 713, y: 79, name: "Rock Tunnel B1F" },
            ladder7:                                                      {x: 1096, y: 26, name: "Rock Tunnel B1F" },
            ladder8:                                                      {x: 1194, y: 378, name: "Rock Tunnel B1F" },
            ladder9:                                                      {x: 248, y: 501, name: "Rock Tunnel 1F" },
            ladder10:                                                     {x: 1034, y: 152, name: "Rock Tunnel B1F" },
        },
        rocket_hideout: {
            entrance:                                                     {x: 238, y: 241, name: "Rocket Hideout 1F" },
			stair1:                                                       {x: 269, y: 47, name: "Rocket Hideout 1F" },
            stair2:                                                       {x: 58, y: 378, name: "Rocket Hideout B1F" },
			stair3:                                                       {x: 121, y: 326, name: "Rocket Hideout B1F" },
            stair4:                                                       {x: 59, y: 749, name: "Rocket Hideout B1F" },
            elevator1:                                                    {x: 135, y: 660, name: "Rocket Hideout B1F" },
            stair5:                                                       {x: 439, y: 423, name: "Rocket Hideout B2F" },
            stair6:                                                       {x: 318, y: 421, name: "Rocket Hideout B2F" },
            stair7:                                                       {x: 321, y: 634, name: "Rocket Hideout B2F" },
            elevator2:                                                    {x: 390, y: 580, name: "Rocket Hideout B2F" },
            stair8:                                                       {x: 157, y: 928, name: "Rocket Hideout B3F" },
            stair9:                                                       {x: 39, y: 1172, name: "Rocket Hideout B3F" },
			stair10:                                                      {x: 315, y: 941, name: "Rocket Hideout B4F" },
            elevator3:                                                    {x: 427, y: 1042, name: "Rocket Hideout B4F" },
        },
        rocket_elevator: {
            f1:                                                           {x: 60, y: 55, name: "Rocket Elevator B1F" },
            f2:                                                           {x: 191, y: 51, name: "Rocket Elevator B2F" },
            f4:                                                           {x: 327, y: 50, name: "Rocket Elevator B4F" },
        },
        safari_zone: {
            c_entrance:                                                   {x: 747, y: 988, name: "Safari Zone Center" },
			c_ne:                                                         {x: 941, y: 782, name: "Safari Zone Center" },
            c_n:                                                          {x: 749, y: 646, name: "Safari Zone Center" },
            c_nw:                                                         {x: 536, y: 779, name: "Safari Zone Center" },
            house1:                                                       {x: 787, y: 882, name: "Safari Zone Center" },
            e_sw:                                                         {x: 1033, y: 971, name: "Safari Zone East" },
			e_nw:                                                         {x: 1025, y: 687, name: "Safari Zone East" },
			house2:                                                       {x: 1407, y: 712, name: "Safari Zone East" },
            n_s:                                                          {x: 767, y: 534, name: "Safari Zone North" },
            n_se:                                                         {x: 1019, y: 491, name: "Safari Zone North" },
			n_sw1:                                                        {x: 572, y: 546, name: "Safari Zone North" },
            n_sw2:                                                        {x: 475, y: 502, name: "Safari Zone North" },
            house3:                                                       {x: 995, y: 103, name: "Safari Zone North" },
            w_ne1:                                                        {x: 432, y: 660, name: "Safari Zone West" },
            w_ne2:                                                        {x: 339, y: 696, name: "Safari Zone West" },
            w_se:                                                         {x: 440, y: 972, name: "Safari Zone West" },
            surf:                                                         {x: 57, y: 694, name: "Safari Zone West" },
			house4:                                                       {x: 187, y: 744, name: "Safari Zone West" },
        },
        saffron: {
            center:                                                      {x: 151, y: 449 }, 
            psychic:                                                     {x: 472, y: 449 },
            silphco:                                                     {x: 296, y: 321 },
            house:                                                       {x: 216, y: 161 },
            mart:                                                        {x: 407, y: 162 },
            house2:                                                      {x: 119, y: 70 },
            dojo:                                                        {x: 423, y: 38 },
            gym:                                                         {x: 552, y: 36 },
        },
        saffron_gym: {
            entrance:                                                    {x: 186, y: 232 },
            blnw:                                                        {x: 26, y: 233 },
            blne:                                                        {x: 90, y: 233 },
            blsw:                                                        {x: 26, y: 265 },
            blse:                                                        {x: 90, y: 266 },
            lnw:                                                         {x: 26, y: 137 },
            lne:                                                         {x: 90, y: 136 },
            lsw:                                                         {x: 26, y: 171 },
            lse:                                                         {x: 90, y: 170 },
            tlnw:                                                        {x: 26, y: 41 },
            tlne:                                                        {x: 90, y: 40 },
			tlsw:                                                        {x: 26, y: 73 },
			tlse:                                                        {x: 90, y: 73 },
            tnw:                                                         {x: 153, y: 40 },
			tne:                                                         {x: 185, y: 40 },
			tsw:                                                         {x: 153, y: 73 },
			tse:                                                         {x: 186, y: 73 },
            trnw:                                                        {x: 251, y: 41 },
			trne:                                                        {x: 314, y: 40 },
			trsw:                                                        {x: 250, y: 73 },
			trse:                                                        {x: 314, y: 72 },
            rnw:                                                         {x: 249, y: 137 },
			rne:                                                         {x: 314, y: 137 },
			rsw:                                                         {x: 249, y: 169 },
			rse:                                                         {x: 313, y: 169 },
            brnw:                                                        {x: 249, y: 231 },
			brne:                                                        {x: 314, y: 231 },
			brsw:                                                        {x: 250, y: 264 },
			brse:                                                        {x: 314, y: 264 },
            center:                                                      {x: 185, y: 169 },
        },
        seafoam_islands: {
            entrance:                                                    {x: 64, y: 274, name: "Seafoam Islands 1F" },
            ladder1:                                                     {x: 110, y: 39, name: "Seafoam Islands 1F" },
            ladder2:                                                     {x: 470, y: 57, name: "Seafoam Islands 1F" },
            ladder3:                                                     {x: 431, y: 241, name: "Seafoam Islands 1F" },
            exit:                                                        {x: 502, y: 279, name: "Seafoam Islands 1F" },
            ladder4:                                                     {x: 640, y: 34, name: "Seafoam Islands B1F" },
            ladder5:                                                     {x: 659, y: 118, name: "Seafoam Islands B1F" },
			ladder6:                                                     {x: 776, y: 106, name: "Seafoam Islands B1F" },
            ladder7:                                                     {x: 860, y: 290, name: "Seafoam Islands B1F" },
            ladder8:                                                     {x: 979, y: 268, name: "Seafoam Islands B1F" },
			ladder9:                                                     {x: 1020, y: 181, name: "Seafoam Islands B1F" },
            ladder10:                                                    {x: 1018, y: 85, name: "Seafoam Islands B1F" },
			ladder11:                                                    {x: 69, y: 398, name: "Seafoam Islands B2F" },
            ladder12:                                                    {x: 69, y: 540, name: "Seafoam Islands B2F" },
			ladder13:                                                    {x: 228, y: 423, name: "Seafoam Islands B2F" },
            ladder14:                                                    {x: 468, y: 406, name: "Seafoam Islands B2F" },
            ladder15:                                                    {x: 468, y: 504, name: "Seafoam Islands B2F" },
			ladder16:                                                    {x: 471, y: 563, name: "Seafoam Islands B2F" },
            ladder17:                                                    {x: 638, y: 508, name: "Seafoam Islands B3F" },
            ladder18:                                                    {x: 687, y: 419, name: "Seafoam Islands B3F" },
            ladder19:                                                    {x: 958, y: 372, name: "Seafoam Islands B3F" },
            ladder20:                                                    {x: 958, y: 442, name: "Seafoam Islands B3F" },
            ladder21:                                                    {x: 958, y: 542, name: "Seafoam Islands B3F" },
            ladder22:                                                    {x: 118, y: 767, name: "Seafoam Islands B4F" },
			ladder23:                                                    {x: 398, y: 705, name: "Seafoam Islands B4F" },
            door1:                                                       {x: 678, y: 738, name: "Rt. 20" },
			door2:                                                       {x: 864, y: 756, name: "Rt. 20" },
        },
        silph_1: {
            entrance:                                                    {x: 245, y: 244, name: "Silph Co. 1F" },
            elevator1:                                                   {x: 183, y: 184, name: "Silph Co. 1F" },
            elevator2:                                                   {x: 301, y: 185, name: "Silph Co. 1F" },
            stair1:                                                      {x: 907, y: 25, name: "Silph Co. 2F" },
            stair2:                                                      {x: 875, y: 49, name: "Silph Co. 2F" },
            elevator3:                                                   {x: 812, y: 23, name: "Silph Co. 2F" },
            warp1:                                                       {x: 700, y: 36, name: "Silph Co. 2F" },
            warp2:                                                       {x: 635, y: 224, name: "Silph Co. 2F" },
            warp3:                                                       {x: 923, y: 227, name: "Silph Co. 2F" },
            warp4:                                                       {x: 540, y: 75, name: "Silph Co. 2F" },
            stair3:                                                      {x: 421, y: 320, name: "Silph Co. 3F" },
            stair4:                                                      {x: 388, y: 342, name: "Silph Co. 3F" },
            elevator4:                                                   {x: 328, y: 319, name: "Silph Co. 3F" },
            warp5:                                                       {x: 438, y: 368, name: "Silph Co. 3F" },
            warp6:                                                       {x: 55, y: 372, name: "Silph Co. 3F" },
            warp7:                                                       {x: 53, y: 453, name: "Silph Co. 3F" },
            warp8:                                                       {x: 180, y: 454, name: "Silph Co. 3F" },
            warp9:                                                       {x: 376, y: 456, name: "Silph Co. 3F" },
            warp10:                                                      {x: 56, y: 518, name: "Silph Co. 3F" },
            warp11:                                                      {x: 439, y: 518, name: "Silph Co. 3F" },
            stair5:                                                      {x: 908, y: 320, name: "Silph Co. 4F" },
            stair6:                                                      {x: 875, y: 337, name: "Silph Co. 4F" },
            elevator5:                                                   {x: 812, y: 320, name: "Silph Co. 4F" },
            warp12:                                                      {x: 763, y: 368, name: "Silph Co. 4F" },
            warp13:                                                      {x: 669, y: 390, name: "Silph Co. 4F" },
            warp14:                                                      {x: 765, y: 453, name: "Silph Co. 4F" },
            warp15:                                                      {x: 541, y: 518, name: "Silph Co. 4F" },
            stair7:                                                      {x: 420, y: 614, name: "Silph Co. 5F" },
            stair8:                                                      {x: 390, y: 633, name: "Silph Co. 5F" },
            elevator6:                                                   {x: 325, y: 615, name: "Silph Co. 5F" },
            warp16:                                                      {x: 438, y: 659, name: "Silph Co. 5F" },
            warp17:                                                      {x: 181, y: 649, name: "Silph Co. 5F" },
            warp18:                                                      {x: 55, y: 812, name: "Silph Co. 5F" },
            elevator7:                                                   {x: 812, y: 611, name: "Silph Co. 6F" },
            stair10:                                                     {x: 778, y: 630, name: "Silph Co. 6F" },
            stair11:                                                     {x: 725, y: 611, name: "Silph Co. 6F" },
            warp19:                                                      {x: 572, y: 662, name: "Silph Co. 6F" },
            warp20:                                                      {x: 893, y: 659, name: "Silph Co. 6F" },
        },
        silph_2: {
            stair1:                                                      {x: 359, y: 26, name: "Silph Co. 7F" },
            elevator1:                                                   {x: 293, y: 40, name: "Silph Co. 7F" },
            stair2:                                                      {x: 261, y: 25, name: "Silph Co. 7F" },
            warp1:                                                       {x: 346, y: 226, name: "Silph Co. 7F" },
            warp2:                                                       {x: 89, y: 30, name: "Silph Co. 7F" },
            warp3:                                                       {x: 88, y: 96, name: "Silph Co. 7F" },
            stair4:                                                      {x: 650, y: 29, name: "Silph Co. 8F" },
            stair5:                                                      {x: 698, y: 50, name: "Silph Co. 8F" },
            elevator2:                                                   {x: 731, y: 29, name: "Silph Co. 8F" },
            warp4:                                                       {x: 618, y: 63, name: "Silph Co. 8F" },
			warp5:                                                       {x: 618, y: 129, name: "Silph Co. 8F" },
            warp6:                                                       {x: 491, y: 157, name: "Silph Co. 8F" },
            warp7:                                                       {x: 491, y: 220, name: "Silph Co. 8F" },
            stair6:                                                      {x: 213, y: 327, name: "Silph Co. 9F" },
            stair7:                                                      {x: 259, y: 343, name: "Silph Co. 9F" },
            elevator3:                                                   {x: 293, y: 327, name: "Silph Co. 9F" },
            warp8:                                                       {x: 150, y: 377, name: "Silph Co. 9F" },
            warp9:                                                       {x: 280, y: 520, name: "Silph Co. 9F" },
            stair8:                                                      {x: 642, y: 325, name: "Silph Co. 10F" },
            stair9:                                                      {x: 689, y: 344, name: "Silph Co. 10F" },
            stair10:                                                     {x: 721, y: 325, name: "Silph Co. 10F" },
            warp10:                                                      {x: 737, y: 395, name: "Silph Co. 10F" },
            warp11:                                                      {x: 674, y: 461, name: "Silph Co. 10F" },
            warp12:                                                      {x: 739, y: 522, name: "Silph Co. 10F" },
            stair10:                                                     {x: 474, y: 630, name: "Silph Co. 11F" },
            elevator4:                                                   {x: 537, y: 629, name: "Silph Co. 11F" },
            warp13:                                                      {x: 376, y: 656, name: "Silph Co. 11F" },
        },
        silph_elevator: {
            f1:                                                          {x: 37, y: 54, name: "Silph Elevator 1F" },
            f2:                                                          {x: 129, y: 53, name: "Silph Elevator 2F" },
			f3:                                                          {x: 221, y: 53, name: "Silph Elevator 3F" },
			f4:                                                          {x: 38, y: 145, name: "Silph Elevator 4F" },
			f5:                                                          {x: 127, y: 147, name: "Silph Elevator 5F" },
			f6:                                                          {x: 221, y: 145, name: "Silph Elevator 6F" },
			f7:                                                          {x: 39, y: 241, name: "Silph Elevator 7F" },
			f8:                                                          {x: 127, y: 244, name: "Silph Elevator 8F" },
			f9:                                                          {x: 222, y: 243, name: "Silph Elevator 9F" },
			f10:                                                         {x: 88, y: 336, name: "Silph Elevator 10F" },
			f11:                                                         {x: 180, y: 336, name: "Silph Elevator 11F" },
        },
        ss_anne: {
            entrance:                                                    {x: 522, y: 20, name: "S.S. Anne 1F" },
			stair1:                                                      {x: 34, y: 159, name: "S.S. Anne 1F" },
            door1:                                                       {x: 132, y: 145, name: "S.S. Anne 1F" },
            door2:                                                       {x: 212, y: 203, name: "S.S. Anne 1F" },
            door3:                                                       {x: 293, y: 146, name: "S.S. Anne 1F" },
			door4:                                                       {x: 374, y: 203, name: "S.S. Anne 1F" },
            door5:                                                       {x: 454, y: 144, name: "S.S. Anne 1F" },
            door6:                                                       {x: 613, y: 144, name: "S.S. Anne 1F" },
            stair2:                                                      {x: 733, y: 274, name: "S.S. Anne 1F" },
            stair3:                                                      {x: 647, y: 419, name: "S.S. Anne 2F" },
            door7:                                                       {x: 535, y: 484, name: "S.S. Anne 2F" },
            door8:                                                       {x: 472, y: 531, name: "S.S. Anne 2F" },
            door9:                                                       {x: 409, y: 484, name: "S.S. Anne 2F" },
            door10:                                                      {x: 344, y: 531, name: "S.S. Anne 2F" },
            door11:                                                      {x: 280, y: 484, name: "S.S. Anne 2F" },
            door12:                                                      {x: 216, y: 531, name: "S.S. Anne 2F" },
            stair4:                                                      {x: 103, y: 497, name: "S.S. Anne 2F" },
            stair5:                                                      {x: 103, y: 420, name: "S.S. Anne 2F" },
            stair6:                                                      {x: 539, y: 652, name: "S.S. Anne 3F" },
			door13:                                                      {x: 217, y: 650, name: "S.S. Anne 3F" },
            stair7:                                                      {x: 584, y: 726, name: "S.S. Anne B1F" },
			door14:                                                      {x: 521, y: 743, name: "S.S. Anne B1F" },
            door15:                                                      {x: 456, y: 732, name: "S.S. Anne B1F" },
            door16:                                                      {x: 391, y: 743, name: "S.S. Anne B1F" },
			door17:                                                      {x: 328, y: 732, name: "S.S. Anne B1F" },
            door18:                                                      {x: 264, y: 743, name: "S.S. Anne B1F" },
            door10:                                                      {x: 54, y: 321, name: "S.S. Anne 1F" },
        },
        vermilion: {
            fisherman:                                                   {x: 66, y: 43 },
            center:                                                      {x: 144, y: 38 },
            fanclub:                                                     {x: 106, y: 240 },
            house1:                                                      {x: 225, y: 240 },
            mart:                                                        {x: 385, y: 239 },
            house2:                                                      {x: 386, y: 357 },
            gym:                                                         {x: 167, y: 358 },
            rt6_1:                                                       {x: 605, y: 11, name: "Rt. 6" },
            rt6_2:                                                       {x: 607, y: 113, name: "Rt. 6" },
            rt6_3:                                                       {x: 747, y: 234, name: "Rt. 6" },
            rt11_1:                                                      {x: 606, y: 360, name: "Rt. 11" },
            rt11_2:                                                      {x: 712, y: 382, name: "Rt. 11" },
            rt11_3:                                                      {x: 829, y: 383, name: "Rt. 11" },
        },
        victory_road: {
            entrance1:                                                   {x: 240, y: 57, name: "Rt. 23" },
			door1:                                                       {x: 321, y: 29, name: "Rt. 23" },
			door2:                                                       {x: 427, y: 29, name: "Rt. 23" },
			door3:                                                       {x: 526, y: 26, name: "Indigo League" },
            entrance2:                                                   {x: 169, y: 435, name: "Victory Road 1F" },
			ladder1:                                                     {x: 20, y: 172, name: "Victory Road 1F" },
            ladder2:                                                     {x: 368, y: 295, name: "Victory Road 2F" },
            ladder3:                                                     {x: 389, y: 153, name: "Victory Road 2F" },
            ladder4:                                                     {x: 869, y: 414, name: "Victory Road 2F" },
            ladder5:                                                     {x: 827, y: 320, name: "Victory Road 2F" },
			ladder6:                                                     {x: 907, y: 269, name: "Victory Road 2F" },
			exit:                                                        {x: 934, y: 318, name: "Victory Road 2F" },
            ladder7:                                                     {x: 107, y: 543, name: "Victory Road 3F" },
            ladder8:                                                     {x: 503, y: 641, name: "Victory Road 3F" },
			ladder9:                                                     {x: 559, y: 662, name: "Victory Road 3F" },
			ladder10:                                                    {x: 584, y: 800, name: "Victory Road 3F" },
        },
        viridian: {
            center:                                                      {x: 231, y: 334 },
            mart:                                                        {x: 326, y: 238 },
            s_house:                                                     {x: 199, y: 174 },
            n_house:                                                     {x: 199, y: 78 },
            gym:                                                         {x: 375, y: 47 },
            r22:                                                         {x: 70, y: 50, name: "Rt. 22" },
        },
    },

    // Numbers are meant to be to check if exist any marks/progress in the maps
    // if null, then we don't do tracking
    // if undefined, then we don't draw the mark
    marks: [
        [["unknown",     0], ["corridor",    0], ["dead_end",  null], ["event",        0], ["center",        0], ["mart",       0], ["one_way",     null]],
        [["normal",      0], ["fighting",     0], ["flying",       0], ["poison",        0], ["ground",     0], ["rock",           0], ["bug",         0], ["ghost",        0], ["fairy", 0]],
        [["steel",       0], ["fire",         0], ["water",        0], ["grass",         0], ["electric",   0], ["psychic",        0], ["ice",         0], ["dragon",       0], ["dark",  0]],
        [["1",           0], ["2",            0], ["3",            0], ["4",             0], ["5",          0], ["6",              0], ["7",           0], ["8",            0]],
        [["team_rocket", 0], ["frlg_rival",   0], ["",     undefined], ["safari",        0], ["masterball", 0], ["c_legendary",    0]],
        [["frlg_bush",   0], ["frlg_surf",    0], ["frlg_boulder", 0], ["frlg_darkness", 0], ["frlg_rock",  0], ["frlg_waterfall", 0], ["bike_needed", 0], ["frlg_trainer", 0],],
    ],
    progress: [
        [["boulder_badge", 0], ["cascade_badge", 0], ["thunder_badge", 0], ["rainbow_badge", 0], ["soul_badge", 0], ["marsh_badge",  0], ["volcano_badge", 0], ["earth_badge",  0]],
        [["rb_lorelei",    0], ["rb_bruno",      0], ["rb_agatha",     0], ["rb_lance",      0], ["rb_blue",    0], ["",     undefined], ["",      undefined], ["",     undefined]],
        [["hm_cut",        0], ["hm_fly",        0], ["hm_surf",       0], ["hm_strength",   0], ["hm_flash",   0], ["",     undefined], ["",      undefined], ["",     undefined]],
        [["bike_voucher",  0], ["bike",          0], ["",      undefined], ["parcel",        0], ["poke_flute", 0], ["tea",          0], ["silph_scope",   0], ["gold_teeth",   0]],
        [["card_key",      0], ["lift_key",      0], ["secret_key",    0], ["plant_key",     0], ["mansion_key",0], ["",     undefined], ["",      undefined], ["ss_ticket",    0]],
    ],

    modifiers: [
		[["#ce4069", 0], ["#4d90d5", 0], ["#ff9c54", 0], ["#74cec0", 0], ["#f3d23b", 0], ["#90c12c", 0], ["#743683", 0], ["#ec8fe6", 0], ["#654321", 0], ["#5a5366", 0], ["#014f01", 0], ["#00146b", 0]]
	],
};