var emerald = {
    name: "emerald",
    locations: {
        // Cities
        oldale:         {x: 40,  y: 88,  w: 8,  h: 8,  scale: 2, name: "Oldale Town"                                                  },
        petalburg:      {x: 16,  y: 88,  w: 8,  h: 8,  scale: 2, name: "Petalburg City"                                               },
        rustboro:       {x: 8,   y: 56,  w: 8,  h: 16, scale: 1, name: "Rustboro City"                                                },
        dewford:        {x: 24,  y: 128, w: 8,  h: 8,  scale: 2, name: "Dewford Town"                                                 },
        slateport_r109: {x: 72,  y: 96,  w: 8,  h: 16, scale: 1, name: "Slateport City\nRoute 109", link_name: "Slateport City"       },
        mauville_r117:  {x: 72,  y: 64,  w: 16, h: 8,  scale: 1, name: "Mauville City\nRoute 117" , link_name: "Mauville City"        },
        verdanturf:     {x: 40,  y: 64,  w: 8,  h: 8,  scale: 2, name: "Verdanturf Town"                                              },
        fallarbor_r113: {x: 32,  y: 16,  w: 8,  h: 8,  scale: 2, name: "Fallarbor Town\nRoute 113", link_name: "Fallarbor Town"       },
        lavaridge:      {x: 48,  y: 40,  w: 8,  h: 8,  scale: 2, name: "Lavaridge Town"                                               },
        fortree:        {x: 104, y: 16,  w: 8,  h: 8,  scale: 1, name: "Fortree City"                                                 },
        lilycove:       {x: 152, y: 40,  w: 16, h: 8,  scale: 1, name: "Lilycove City"                                                },
        mossdeep_r124:  {x: 200, y: 56,  w: 16, h: 8,  scale: 1, name: "Mossdeep City\nRoute 124" , link_name: "Mossdeep City / R124" },
        sootopolis:     {x: 176, y: 72,  w: 8,  h: 8,  scale: 1, name: "Sootopolis City"                                              },
        pacifidlog:     {x: 144, y: 96,  w: 8,  h: 8,  scale: 3, name: "Pacifidlog Town"                                              },
        evergrande:     {x: 224, y: 80,  w: 8,  h: 16, scale: 2, name: "Ever Grande City"                                             },

        // Routes
        petalburgwoods_r104: {x: 8,   y: 78, w: 8, h: 8, scale: 1, name: "Petalburg Woods\nRoute 104", link_name: "Petalburg Woods/R104"  },
        rusturftunnel_r116:  {x: 27,  y: 56, w: 8, h: 8, scale: 1, name: "Rusturf Tunnel\nRoute 116" , link_name: "Rusturf Tunner / R116" },
        r110:                {x: 72,  y: 79, w: 8, h: 8, scale: 2, name: "Route 110"                                                      },
        r111_r112:           {x: 72,  y: 27, w: 8, h: 8, scale: 2, name: "Route 111\nRoute 112"      , link_name: "Route 111 / Route 112" },
        r114:                {x: 16,  y: 16, w: 8, h: 8, scale: 3, name: "Route 114"                                                      },
        r119_r123:           {x: 96,  y: 40, w: 8, h: 8, scale: 2, name: "Route 119\nRoute 123"      , link_name: "Route 119 / Route 123" },
        r120:                {x: 120, y: 40, w: 8, h: 8, scale: 3, name: "Route 120"                                                      },

        // Important locations
        granitecave_r105_r106:   {x: 8,   y: 120, w: 8, h: 8, scale: 1, name: "Granite Cave\nRoute 105/106", link_name: "Granite Cave/R105-106" },
        abandonedship_r108:      {x: 60,  y: 128, w: 8, h: 8, scale: 2, name: "Abandoned Ship\nRoute 108"  , link_name: "Abandoned Ship / R108" },
        miragetower:             {x: 72,  y: 51,  w: 8, h: 8, scale: 1, name: "Mirage Tower"                                                    },
        magmahideout_jaggedpass: {x: 62,  y: 40,  w: 8, h: 8, scale: 1, name: "Magma Hideout\nJagged Pass" , link_name: "Magma / Jagged Pass"   },
        meteorfalls_r115:        {x: 8,   y: 32,  w: 8, h: 8, scale: 1, name: "Meteor Falls\nRoute 115"    , link_name: "Meteor Falls / R115"   },
        mtpyre_r122:             {x: 136, y: 53,  w: 8, h: 8, scale: 1, name: "Mt. Pyre\nRoute 122"        , link_name: "Mt. Pyre"              },
        departmentstore:         {x: 152, y: 27,  w: 8, h: 8, scale: 2, name: "Department Store"                                                },
        aquahideout:             {x: 173, y: 40,  w: 8, h: 8, scale: 2, name: "Aqua Hideout"                                                    },
        seafloor_underwater:     {x: 200, y: 72,  w: 8, h: 8, scale: 1, name: "Seafloor Cavern\nUnderwater", link_name: "Seafloor / Underwater" },
        skypillar_r131:          {x: 169, y: 96,  w: 8, h: 8, scale: 1, name: "Sky Pillar\nRoute 131"      , link_name: "Sky Pillar"            },
        victoryroad:             {x: 237, y: 80,  w: 8, h: 8, scale: 1, name: "Victory Road"                                                    },
        navelrock:               {x: 206, y: 22,  w: 8, h: 8, scale: 2, name: "Navel Rock"                                                      },
    },

    // Undefined fields:
    // - link_type:     "warp"        / "mark"
    // - link:          warp_name     / mark_name
    // - link_location: location_name / <garbage>
    warps: {
        // Cities
        oldale: {
            left:   {x: 88,  y: 99 },
            mart:   {x: 232, y: 82 },
            center: {x: 103, y: 243},
            right:  {x: 248, y: 242},
        },
        petalburg: {
            wally:  {x: 120, y: 64 },
            gym:    {x: 248, y: 111},
            center: {x: 328, y: 242},
            mart:   {x: 408, y: 180},
            left:   {x: 168, y: 288},
            right:  {x: 328, y: 370},
        },
        rustboro: {
            corp:      {x: 192, y: 107},
            gym:       {x: 440, y: 165},
            rightgym:  {x: 535, y: 200},
            upcut:     {x: 213, y: 345},
            cut:       {x: 150, y: 520},
            upschool:  {x: 487, y: 312},
            school:    {x: 440, y: 410},
            center:    {x: 263, y: 472},
            leftmart:  {x: 86,  y: 680},
            mart:      {x: 262, y: 585},
            rightmart: {x: 422, y: 602},
        },

        dewford: {
            top:    {x: 56,  y: 31 },
            middle: {x: 135, y: 110},
            bottom: {x: 278, y: 208},
            center: {x: 38,  y: 144},
            gym:    {x: 135, y: 248},
        },

        slateport_r109: {
            contest:  {x: 168, y: 40 },
            rater:    {x: 85,  y: 148},
            club:     {x: 51,  y: 264},
            center:   {x: 310, y: 153},
            mart:     {x: 225, y: 267},
            museum:   {x: 494, y: 268},
            shipyard: {x: 424, y: 449},
            house:    {x: 342, y: 555},
            beach:    {x: 275, y: 731},
        },

        mauville_r117: {
            gym:     {x: 346, y: 53 },
            center:  {x: 571, y: 56 },
            bicycle: {x: 779, y: 55 },
            casino:  {x: 345, y: 175},
            left:    {x: 524, y: 197},
            mart:    {x: 596, y: 260},
            right:   {x: 731, y: 200},
            daycare: {x: 103, y: 156},
        },

        verdanturf: {
            contest: {x: 55,  y: 89 },
            tunnel:  {x: 135, y: 9  },
            mart:    {x: 208, y: 34 },
            center:  {x: 273, y: 14 },
            left:    {x: 24,  y: 204},
            middle:  {x: 167, y: 204},
            right:   {x: 281, y: 219},
        },

        fallarbor_r113: {
            move:    {x: 35,  y: 77 },
            contest: {x: 136, y: 130},
            center:  {x: 231, y: 96 },
            house:   {x: 103, y: 253},
            mart:    {x: 255, y: 223},
            ashes:   {x: 450, y: 156},
        },

        lavaridge: {
            center:      {x: 100, y: 78 , name: "Lavaridge (Outside)"},
            mart:        {x: 199, y: 61 , name: "Lavaridge (Outside)"},
            gym:         {x: 38,  y: 218, name: "Lavaridge (Outside)"},
            herbs:       {x: 140, y: 215, name: "Lavaridge (Outside)"},
            house:       {x: 230, y: 215, name: "Lavaridge (Outside)"},
            center_top:  {x: 325, y: 24 , name: "Lavaridge (Center)" },
            center_left: {x: 313, y: 99 , name: "Lavaridge (Center)" },
            center_bot:  {x: 398, y: 149, name: "Lavaridge (Center)" },
        },

        fortree: {
            center:  {x: 95,  y: 81 },
            top1:    {x: 168, y: 29 },
            top2:    {x: 280, y: 66 },
            top3:    {x: 408, y: 29 },
            top4:    {x: 521, y: 66 },
            mart:    {x: 79,  y: 225},
            gym:     {x: 359, y: 148},
            bottom1: {x: 199, y: 185},
            bottom2: {x: 599, y: 185},
        },

        lilycove: {
            department:   {x: 309, y: 75,  name: "Lilycove City"          },
            deleter:      {x: 453, y: 125, name: "Lilycove City"          },
            rightdeleter: {x: 552, y: 75,  name: "Lilycove City"          },
            leftcenter:   {x: 80,  y: 197, name: "Lilycove City"          },
            center:       {x: 261, y: 199, name: "Lilycove City"          },
            club:         {x: 501, y: 198, name: "Lilycove City"          },
            coast:        {x: 758, y: 212, name: "Lilycove City"          },
            lefthall:     {x: 80,  y: 325, name: "Lilycove City"          },
            hall:         {x: 243, y: 354, name: "Lilycove City"          },
            motel:        {x: 469, y: 356, name: "Lilycove City"          },
            harbor:       {x: 80,  y: 485, name: "Lilycove City"          },
            aqua:         {x: 970, y: 53 , name: "Lilycove (Aqua Hideout)"},
            hall_left:    {x: 487, y: 482, name: "Lilycove (Contest Hall)"},
            hall_right:   {x: 677, y: 480, name: "Lilycove (Contest Hall)"},
            hall_bot:     {x: 571, y: 587, name: "Lilycove (Contest Hall)"},
        },

        mossdeep_r124: {
            steven:     {x: 95,  y: 100, name: "Mossdeep City"},
            leftgym:    {x: 234, y: 65 , name: "Mossdeep City"},
            gym:        {x: 391, y: 65 , name: "Mossdeep City"},
            leftcenter: {x: 75,  y: 185, name: "Mossdeep City"},
            center:     {x: 239, y: 188, name: "Mossdeep City"},
            mart:       {x: 385, y: 222, name: "Mossdeep City"},
            botmart:    {x: 374, y: 315, name: "Mossdeep City"},
            space:      {x: 808, y: 160, name: "Mossdeep City"},
            botspace:   {x: 864, y: 330, name: "Mossdeep City"},
            leftspace:  {x: 574, y: 24 , name: "Mossdeep City"},
            r124:       {x: 73,  y: 314, name: "Route 124"    },
        },
        sootopolis: {
            mart:       {x: 192, y: 399, name: "Sootopolis (Left Side)" },
            left1:      {x: 39,  y: 495, name: "Sootopolis (Left Side)" },
            left2:      {x: 55,  y: 346, name: "Sootopolis (Left Side)" },
            left3:      {x: 56,  y: 201, name: "Sootopolis (Left Side)" },
            left4:      {x: 54,  y: 25 , name: "Sootopolis (Left Side)" },
            center:     {x: 608, y: 428, name: "Sootopolis (Right Side)"},
            right1:     {x: 726, y: 509, name: "Sootopolis (Right Side)"},
            right2:     {x: 760, y: 376, name: "Sootopolis (Right Side)"},
            right3:     {x: 678, y: 323, name: "Sootopolis (Right Side)"},
            right4:     {x: 615, y: 203, name: "Sootopolis (Right Side)"},
            right5:     {x: 631, y: 26 , name: "Sootopolis (Right Side)"},
            gym:        {x: 406, y: 442, name: "Sootopolis (Gym)"       },
            underwater: {x: 393, y: 682, name: "Sootopolis (Underwater)"},
        },
        pacifidlog: {
            center:    {x: 143, y: 83 },
            topleft:   {x: 39,  y: 46 },
            topright:  {x: 263, y: 70 },
            botleft:   {x: 55,  y: 209},
            botmiddle: {x: 200, y: 238},
            botright:  {x: 280, y: 191},
        },
        evergrande: {
            center:      {x: 278, y: 140, name: "Ever Grande (Victory R.)"},
            cave:        {x: 134, y: 28 , name: "Ever Grande (Victory R.)"},
            center_top:  {x: 178, y: 261, name: "Ever Grande (E4)"        },
            center_left: {x: 63,  y: 339, name: "Ever Grande (E4)"        },
            center_bot:  {x: 178, y: 381, name: "Ever Grande (E4)"        },
        },

        // Routes
        petalburgwoods_r104: {
            briney:         {x: 392, y: 510, name: "Route 104 (Bottom)"},
            woodsentrance:  {x: 289, y: 362, name: "Route 104 (Bottom)"},
            woodsbotexit:   {x: 641, y: 417, name: "Route 104 (Bottom)"},
            woods_entrance: {x: 111, y: 691, name: "Petalburg Woods"   },
            woods_botexit:  {x: 431, y: 691, name: "Petalburg Woods"   },
            woods_topexit:  {x: 79,  y: 216, name: "Petalburg Woods"   },
            woodstopexit:   {x: 420, y: 207, name: "Route 104 (Top)"   },
            flowers:        {x: 332, y: 89 , name: "Route 104 (Top)"   },
        },
        rusturftunnel_r116:  {
            house:       {x: 197, y: 70 , name: "Route 116"     },
            cave:        {x: 342, y: 130, name: "Route 116"     },
            cave_left:   {x: 70,  y: 390, name: "Rusturf Tunnel"},
            cave_middle: {x: 298, y: 550, name: "Rusturf Tunnel"},
            cave_right:  {x: 472, y: 486, name: "Rusturf Tunnel"},
        },
        r110:                {
            topcycle_left:  {x: 72,  y: 104, name: "R110 (Top Cycle Out)"},
            topcycle_right: {x: 119, y: 62 , name: "R110 (Top Cycle In)" },
            powerplant:     {x: 279, y: 88 , name: "R110 (Power Plant)"  },
            trickhouse:     {x: 71,  y: 251, name: "R110 (Trick House)"  },
            botcycle_left:  {x: 230, y: 360, name: "R110 (Bot Cycle Out)"},
            botcycle_right: {x: 279, y: 318, name: "R110 (Bot Cycle In)" },
        },
        r111_r112:           {
            jaggedentrance:  {x: 79,  y: 181, name: "Route 111 (Jagged Entr.)"},
            fieryentrance:   {x: 152, y: 73 , name: "Route 111 (Fiery Entr.)" },
            fieryexit:       {x: 295, y: 59 , name: "Route 111 (Fiery Exit)"  },
            cablecar:        {x: 398, y: 274, name: "Route 111 (Cable Car)"   },
            reststop:        {x: 391, y: 64 , name: "Route 111 (Heal Lady)"   },
            familyhouse:     {x: 72,  y: 411, name: "Route 112 (Family)"      },
            desert_mirage:   {x: 195, y: 421, name: "Route 112 (Mirage)"      },
            desert_regirock: {x: 358, y: 398, name: "Route 112 (Regirock)"    },
        },
        r114:                {
            fossilmaniac: {x: 264, y: 66 , name: "Route 114 (Dig TM)"      },
            lanette:      {x: 247, y: 190, name: "Route 114 (Lanette)"     },
            meteorfalls:  {x: 87,  y: 187, name: "Route 114 (Meteor Falls)"},
        },
        r119_r123:           {
            r119_house:       {x: 166, y: 287, name: "Route 119 (House)"  },
            weatherinstitute: {x: 103, y: 105, name: "Route 119 (Weather)"},
            berrymaster:      {x: 332, y: 207, name: "Route 123"          },
        },
        r120:                {
            scorchedslab: {x: 102, y: 48 , name: "Route 120 (Lab)" },
            ancienttomb:  {x: 103, y: 177, name: "Route 120 (Tomb)"},
        },

        // Important locations
        granitecave_r105_r106: {
            r105:            {x: 104, y: 332, name: "Route 105"    },
            graniteentrance: {x: 88,  y: 643, name: "Route 106"    },
            f1_entrance:     {x: 667, y: 191, name: "Granite (1F)" },
            f1_botstairs:    {x: 347, y: 158, name: "Granite (1F)" },
            f1_topstairs:    {x: 636, y: 79 , name: "Granite (1F)" },
            f1_steven:       {x: 154, y: 139, name: "Granite (1F)" },
            bf1_entrance:    {x: 299, y: 574, name: "Granite (1BF)"},
            bf1_exit:        {x: 683, y: 580, name: "Granite (1BF)"},
            bf1_optional1:   {x: 363, y: 366, name: "Granite (1BF)"},
            bf1_optional2:   {x: 428, y: 286, name: "Granite (1BF)"},
            bf1_optional3:   {x: 701, y: 323, name: "Granite (1BF)"},
            bf2_topstairs:   {x: 427, y: 721, name: "Granite (2BF)"},
            bf2_botstairs:   {x: 364, y: 801, name: "Granite (2BF)"},
        },
        abandonedship_r108: {
            r108_entrance:       {x: 365, y: 393, name: "Route 108 (Ship)"      },
            bedroom_left:        {x: 303, y: 321, name: "Abandoned Ship (Beds)" },
            bedroom_right:       {x: 448, y: 321, name: "Abandoned Ship (Beds)" },
            bedroom_top:         {x: 440, y: 116, name: "Abandoned Ship (Beds)" },
            line_stairs:         {x: 77,  y: 31 , name: "Abandoned Ship (Line)" },
            line_top:            {x: 54,  y: 64 , name: "Abandoned Ship (Line)" },
            line_bot:            {x: 55,  y: 113, name: "Abandoned Ship (Line)" },
            line_exit:           {x: 35,  y: 171, name: "Abandoned Ship (Line)" },
            block_stairs:        {x: 258, y: 32 , name: "Abandoned Ship (Block)"},
            block_topleft:       {x: 180, y: 45 , name: "Abandoned Ship (Block)"},
            block_topright:      {x: 233, y: 62 , name: "Abandoned Ship (Block)"},
            block_botleft:       {x: 183, y: 116, name: "Abandoned Ship (Block)"},
            block_botright:      {x: 231, y: 133, name: "Abandoned Ship (Block)"},
            block_exit:          {x: 144, y: 170, name: "Abandoned Ship (Block)"},
            hub_stairsleft:      {x: 35,  y: 230, name: "Abandoned Ship (Hub)"  },
            hub_stairsright:     {x: 149, y: 230, name: "Abandoned Ship (Hub)"  },
            hub_top1:            {x: 55,  y: 282, name: "Abandoned Ship (Hub)"  },
            hub_top2:            {x: 104, y: 265, name: "Abandoned Ship (Hub)"  },
            hub_locked:          {x: 184, y: 282, name: "Abandoned Ship (Hub)"  },
            hub_bot1:            {x: 86,  y: 340, name: "Abandoned Ship (Hub)"  },
            hub_bot2:            {x: 136, y: 323, name: "Abandoned Ship (Hub)"  },
            hub_bot3:            {x: 184, y: 340, name: "Abandoned Ship (Hub)"  },
        },
        miragetower: {
            f1_entrance:      {x: 168, y: 793, name: "Mirage Tower (1F)"},
            f1_stairs:        {x: 250, y: 640, name: "Mirage Tower (1F)"},
            f2_entrance:      {x: 248, y: 350, name: "Mirage Tower (2F)"},
            f2_stairs:        {x: 296, y: 454, name: "Mirage Tower (2F)"},
            f3_entrance:      {x: 295, y: 176, name: "Mirage Tower (3F)"},
            f3_stairsaaaaaaa: {x: 39,  y: 98 , name: "Mirage Tower (3F)"},
        },
        magmahideout_jaggedpass: {
            jagged_top: {x: 369, y: 602, name: "Jagged Pass (Top)"  },
            jagged_mid: {x: 554, y: 602, name: "Jagged Pass (Magma)"},
            jagged_bot: {x: 720, y: 602, name: "Jagged Pass (Bot)"  },
            f1_left:    {x: 90,  y: 233, name: "Magma Hideout (1F)" },
            f1_top:     {x: 248, y: 78 , name: "Magma Hideout (1F)" },
            f1_right:   {x: 329, y: 230, name: "Magma Hideout (1F)" },
            f2_top:     {x: 521, y: 76 , name: "Magma Hideout (2F)" },
            f2_mid:     {x: 566, y: 335, name: "Magma Hideout (2F)" },
            f2_bot:     {x: 664, y: 519, name: "Magma Hideout (2F)" },
            f3_top:     {x: 374, y: 370, name: "Magma Hideout (3F)" },
            f3_mid:     {x: 344, y: 465, name: "Magma Hideout (3F)" },
            f3_bot:     {x: 122, y: 614, name: "Magma Hideout (3F)" },
        },
        meteorfalls_r115: {
            r115_exit:        {x: 703, y: 570, name: "Route 115 (Meteor)"     },
            f1r1_entrance:    {x: 756, y: 440, name: "Meteor Falls (1F Room1)"},
            f1r1_exit:        {x: 512, y: 564, name: "Meteor Falls (1F Room1)"},
            f1r1_cave:        {x: 466, y: 430, name: "Meteor Falls (1F Room1)"},
            f1r2_cave:        {x: 536, y: 279, name: "Meteor Falls (1F Room2)"},
            f1r2_stairstop:   {x: 441, y: 80 , name: "Meteor Falls (1F Room2)"},
            f1r2_stairsmid:   {x: 490, y: 181, name: "Meteor Falls (1F Room2)"},
            f1r2_stairsright: {x: 715, y: 231, name: "Meteor Falls (1F Room2)"},
            f2_stairsbot:     {x: 54,  y: 336, name: "Meteor Falls (2F)"      },
            f2_stairstop:     {x: 89,  y: 128, name: "Meteor Falls (2F)"      },
            f2_stairsmid:     {x: 122, y: 213, name: "Meteor Falls (2F)"      },
            f2_stairsright:   {x: 296, y: 276, name: "Meteor Falls (2F)"      },
            f2_cavebot:       {x: 327, y: 573, name: "Meteor Falls (2F)"      },
            f2_cavetop:       {x: 280, y: 83 , name: "Meteor Falls (2F)"      },
        },
        mtpyre_r122: {
            r122_entrance:  {x: 654, y: 343, name: "Route 122 (Mt. Pyre)"},
            f1_entrance:    {x: 287, y: 270, name: "Mt. Pyre (1F)"       },
            f1_exit:        {x: 63,  y: 132, name: "Mt. Pyre (1F)"       },
            f1_stairs:      {x: 185, y: 48 , name: "Mt. Pyre (1F)"       },
            f1_fall:        {x: 313, y: 155, name: "Mt. Pyre (1F)"       },
            f2_stairsright: {x: 538, y: 10 , name: "Mt. Pyre (2F)"       },
            f2_stairsleft:  {x: 406, y: 45 , name: "Mt. Pyre (2F)"       },
            f2_hole:        {x: 550, y: 132, name: "Mt. Pyre (2F)"       },
            f2_fallleft:    {x: 478, y: 171, name: "Mt. Pyre (2F)"       },
            f2_fallright:   {x: 537, y: 216, name: "Mt. Pyre (2F)"       },
            f3_stairsright: {x: 761, y: 60 , name: "Mt. Pyre (3F)"       },
            f3_stairsleft:  {x: 632, y: 100, name: "Mt. Pyre (3F)"       },
            f3_fall:        {x: 741, y: 220, name: "Mt. Pyre (3F)"       },
            f3_hole:        {x: 759, y: 272, name: "Mt. Pyre (3F)"       },
            f4_stairsleft:  {x: 38,  y: 430, name: "Mt. Pyre (4F)"       },
            f4_stairsright: {x: 167, y: 360, name: "Mt. Pyre (4F)"       },
            f4_fall:        {x: 203, y: 494, name: "Mt. Pyre (4F)"       },
            f4_hole:        {x: 151, y: 463, name: "Mt. Pyre (4F)"       },
            f5_holetop:     {x: 501, y: 381, name: "Mt. Pyre (5F)"       },
            f5_holebot:     {x: 501, y: 459, name: "Mt. Pyre (5F)"       },
            f5_fall:        {x: 334, y: 421, name: "Mt. Pyre (5F)"       },
        },
        departmentstore: {
            f1_entrance: {x: 48,  y: 395},
            f1_stairs:   {x: 168, y: 325},
            f2_left:     {x: 120, y: 180},
            f2_right:    {x: 168, y: 150},
            f3_left:     {x: 120, y: 35 },
            f3_right:    {x: 168, y: 5  },
            f4_left:     {x: 328, y: 325},
            f4_right:    {x: 376, y: 295},
            f5_left:     {x: 328, y: 180},
            f5_right:    {x: 376, y: 150},
        },
        aquahideout: {
            small_stairs:     {x: 242, y: 183, name: "Aqua Hideout (Small)"},
            small_left:       {x: 210, y: 237, name: "Aqua Hideout (Small)"},
            small_right:      {x: 274, y: 267, name: "Aqua Hideout (Small)"},
            long_top:         {x: 55,  y: 331, name: "Aqua Hideout (Long)" },
            long_bot:         {x: 56,  y: 406, name: "Aqua Hideout (Long)" },
            long_right:       {x: 251, y: 395, name: "Aqua Hideout (Long)" },
            generator_stairs: {x: 72,  y: 43 , name: "Aqua Hideout (Big)"  },
            generator_left:   {x: 71,  y: 201, name: "Aqua Hideout (Big)"  },
            generator_right:  {x: 280, y: 120, name: "Aqua Hideout (Big)"  },
            hub_entrance:     {x: 426, y: 121, name: "Aqua Hideout (Hub 1)"},
            hub_row1left:     {x: 360, y: 169, name: "Aqua Hideout (Hub 1)"},
            hub_row1mid:      {x: 426, y: 152, name: "Aqua Hideout (Hub 1)"},
            hub_row1right:    {x: 480, y: 169, name: "Aqua Hideout (Hub 1)"},
            hub_row2left:     {x: 360, y: 233, name: "Aqua Hideout (Hub 2)"},
            hub_row2mid:      {x: 426, y: 216, name: "Aqua Hideout (Hub 2)"},
            hub_row2right:    {x: 480, y: 233, name: "Aqua Hideout (Hub 2)"},
            hub_row3left:     {x: 360, y: 297, name: "Aqua Hideout (Hub 3)"},
            hub_row3mid:      {x: 426, y: 279, name: "Aqua Hideout (Hub 3)"},
            hub_row3right:    {x: 480, y: 297, name: "Aqua Hideout (Hub 3)"},
            hub_row4left:     {x: 360, y: 361, name: "Aqua Hideout (Hub 4)"},
            hub_row4mid:      {x: 426, y: 344, name: "Aqua Hideout (Hub 4)"},
            hub_row4right:    {x: 480, y: 361, name: "Aqua Hideout (Hub 4)"},
        },
        seafloor_underwater: {
            underwater_r126: {x: 319, y: 793, name: "Route 126"          },
            underwater_r128: {x: 610, y: 848, name: "Route 128"          },
            room1_top:       {x: 104, y: 60 , name: "Seafloor (Room 1)"  },
            room1_right:     {x: 279, y: 207, name: "Seafloor (Room 1)"  },
            room1_left:      {x: 87,  y: 284, name: "Seafloor (Room 1)"  },
            room2_top:       {x: 409, y: 50 , name: "Seafloor (Room 2)"  },
            room2_right:     {x: 584, y: 193, name: "Seafloor (Room 2)"  },
            room2_left:      {x: 456, y: 268, name: "Seafloor (Room 2)"  },
            room3_topleft:   {x: 740, y: 50 , name: "Seafloor (Room 3)"  },
            room3_topright:  {x: 895, y: 50 , name: "Seafloor (Room 3)"  },
            room3_mid:       {x: 826, y: 186, name: "Seafloor (Room 3)"  },
            room3_bot:       {x: 840, y: 284, name: "Seafloor (Room 3)"  },
            room4_topleft:   {x: 104, y: 400, name: "Seafloor (Boulders)"},
            room4_topright:  {x: 186, y: 365, name: "Seafloor (Boulders)"},
            room4_botleft:   {x: 72,  y: 512, name: "Seafloor (Boulders)"},
            room4_botright:  {x: 167, y: 461, name: "Seafloor (Boulders)"},
            room5_top:       {x: 376, y: 400, name: "Seafloor (Surf)"    },
            room5_mid:       {x: 534, y: 510, name: "Seafloor (Surf)"    },
            room5_bot:       {x: 488, y: 684, name: "Seafloor (Surf)"    },
            room7_top:       {x: 841, y: 400, name: "Seafloor (Puzzle)"  },
            room7_left:      {x: 776, y: 590, name: "Seafloor (Puzzle)"  },
            room7_right:     {x: 856, y: 556, name: "Seafloor (Puzzle)"  },
        },
        skypillar_r131: {
            r131_entrance: {x: 184, y: 551, name: "Route 131 (Sky Pillar)"},
            f1_entrance:   {x: 111, y: 431, name: "Sky Pillar (1F)"       },
            f1_stairs:     {x: 167, y: 227, name: "Sky Pillar (1F)"       },
            f2_left:       {x: 56,  y: 50 , name: "Sky Pillar (2F)"       },
            f2_right:      {x: 168, y: 0  , name: "Sky Pillar (2F)"       },
            f3_left:       {x: 280, y: 287, name: "Sky Pillar (3F)"       },
            f3_mid:        {x: 360, y: 227, name: "Sky Pillar (3F)"       },
            f3_right:      {x: 435, y: 287, name: "Sky Pillar (3F)"       },
            f4_left:       {x: 280, y: 50 , name: "Sky Pillar (4F)"       },
            f4_mid:        {x: 360, y: 0  , name: "Sky Pillar (4F)"       },
            f4_right:      {x: 435, y: 50 , name: "Sky Pillar (4F)"       },
        },
        victoryroad: {
            bf1_topleft:  {x: 137, y: 82 , name: "Victory Road (1BF)"},
            bf1_midleft:  {x: 278, y: 230, name: "Victory Road (1BF)"},
            bf1_midright: {x: 330, y: 373, name: "Victory Road (1BF)"},
            bf1_botleft:  {x: 89,  y: 395, name: "Victory Road (1BF)"},
            bf1_botmid:   {x: 489, y: 440, name: "Victory Road (1BF)"},
            bf1_botright: {x: 678, y: 366, name: "Victory Road (1BF)"},
            bf2_top:      {x: 696, y: 540, name: "Victory Road (2BF)"},
            bf2_mid:      {x: 313, y: 701, name: "Victory Road (2BF)"},
            bf2_left:     {x: 86,  y: 860, name: "Victory Road (2BF)"},
            bf2_right:    {x: 484, y: 840, name: "Victory Road (2BF)"},
        },
        navelrock: {
            stairsleft:   {x: 74,  y: 76 },
            stairsright:  {x: 360, y: 76 },
            stairsbottom: {x: 184, y: 252},
        },
    },

    // Numbers are meant to be to check if exist any marks/progress in the maps
    // if null, then we don't do tracking
    // if undefined, then we don't draw the mark
    marks: [
        [["unknown", null], ["dead_end", null], ["event",  0], ["center", 0], ["mart",     0], ["one_way", null]],
        [["normal",     0], ["fighting",    0], ["flying", 0], ["poison", 0], ["ground",   0], ["rock",       0], ["bug",  0], ["ghost",   0]],
        [["steel",      0], ["fire",        0], ["water",  0], ["grass",  0], ["electric", 0], ["psychic",    0], ["ice",  0], ["dragon",  0], ["dark", 0]],
        [["1",          0], ["2",           0], ["3",      0], ["4",      0], ["5",        0], ["6",          0], ["7",    0], ["8",       0]],
        [["e_rock",     0], ["e_boulder",   0], ["e_surf", 0], ["e_dive", 0], ["e_bike",   0], ["e_trainer",  0]],
    ],
    progress: [
        [["stone_badge", 0], ["knuckle_badge", 0], ["dynamo_badge", 0], ["heat_badge", 0], ["balance_badge", 0], ["feather_badge", 0], ["mind_badge",    0], ["rain_badge",   0]],
        [["e4_dark",     0], ["e4_ghost",      0], ["e4_ice",       0], ["e4_dragon",  0], ["champ_water",   0], ["",      undefined], ["",      undefined], ["steven_steel", 0]],
        [["hm1",         0], ["hm2",           0], ["hm3",          0], ["hm4",        0], ["hm5",           0], ["hm6",           0], ["hm7",           0], ["hm8",          0]],
    ],
    obtained: new Set()
};